### ISSUE TITLE
Is 430 definitely working?

### ISSUE THREAD

**Issue by privatesam** [keylase/nvidia-patch#100]
Hi,

I am running Plex in a LXC container on proxmox 5.4 (debian).  With driver 418.56 I was able to transcode more than 2 streams but since setting 430 up and repatching it stops at 2 streams.  the patch says successful.  I have installed the Nvidia drivers and patch on both the host and the container and everything is working fine as far as I can tell because 2 streams are happily transcoded by the GPU.   Do you think I should revert to 418?

**Comment by Snawoot** [comment]
Hi!

Patch for 430 release by mistake was tested against 418 version and now I can confirm old byte string no longer works for 430. Some GDB work has to take place and probably today (if everything goes well) there will be release with fix .

**Comment by Snawoot** [comment]
Fixed via #101

**Comment by privatesam** [comment]
Thanks for fixing so quickly!
