### ISSUE TITLE
nVidia Vulnerabilities

### ISSUE THREAD

**Issue by avsoundguy** [keylase/nvidia-patch#105]
Hello,

My question is: ...Will this announcement about these newly discovered vulnerabilities kill the patches you have worked on so tirelessly?   https://www.forbes.com/sites/kevinmurnane/2019/05/11/update-your-drivers-right-now-if-you-have-an-nvidia-geforce-quadro-or-tesla-graphics-card/#7fe248733a55

**Comment by Snawoot** [comment]
Hello!

Announcement provides table with vulnerabilities and versions containing fix. This table designates driver version 430.64 for GeForce and Quadro as containing all fixes for latest 430 driver branch. And patch for this version (430.64) is already available in our repo both for Quadro and GeForce.

I think those fixes completely unrelated to our subject.
