### ISSUE TITLE
win1337 offset E2877 wrong

### ISSUE THREAD

**Issue by cleverchimp** [keylase/nvidia-patch#108]
Hello,

Seems to be the patch is only good for Windows 10, tried to patch Quadro P400 under Windows Server 2012 (driver is for Winserver 2012 R2 64bit from nVidia website) and Win1337 shows error 

"Offset [E2877] Wrong... Set 0x83 -> I expected 0x74"

nVidia driver link is https://www.nvidia.com/Download/driverResults.aspx/147468/en-us

**Comment by Snawoot** [comment]
Hi! Patch for Windows Server added via PR #109 

Patch links are now available on main page, so please check it and reopen issue if it doesn't works for you.

**Comment by cleverchimp** [comment]
Tried it, it successfully patched and reboot the server however when testing it with 6 Plex streams and only 2 showing (hw) encoded, looks like it still locked.

**Comment by Snawoot** [comment]
Please check out [note about Plex Media Server](https://github.com/keylase/nvidia-patch/tree/master/win#plex-media-server-d3d11-and-32-bit-apps-encoding-sessions) on the main page.
