### ISSUE TITLE
New driver support (version 435.27)

### ISSUE THREAD

**Issue by max06** [keylase/nvidia-patch#116]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: [e.g. 410.48] 435.27
- GPU Model: [e.g. GTX 1070] GTX 1080
- OS: [e.g. Ubuntu 18.04] Win10 1903 x64
- [x] I'm willing to participate in testing of new patch version: Sure I am.

Stupid windows update overwrote the previus installed 430.xx-Version. Latest Patch seems to be incompatible, wrong offset.

Otherwise: Awesome work!

**Comment by Snawoot** [comment]
Hi! Thanks!

I can't locate version 435.27 on any Nvidia download site, like it has been never released. Can you provide driver download link?

**Comment by ValZapod** [comment]
@Snawoot 
It is beta driver for insider (download only through microsoft update). I usually get such drivers from here https://github.com/CHEF-KOCH/nVidia-modded-Inf/releases/tag/435.27

**Comment by Snawoot** [comment]
Resolved via PR #117, patch for new version is now available on main page. 

@max06 Please test and reopen if problem occurs.

**Comment by max06** [comment]
@Snawoot Absolutely awesome. 

Patch applied, Session Limit Bumper didn't complain. Need to wait for actual encodes to happen, but I don't expect issues here. 

Talking about issues: While writing here, in exact this moment, windows update is installing 430.86... I guess I got the 435 by accident. And I'm really sorry I forgot about the insider builds I'm getting.

**Comment by Snawoot** [comment]
@max06 No problem. At least now we are aware about some private driver builds. I hope in future we'll able to track them automatically just like regular releases if there'll be reliable channel to discover such new private versions.
