### ISSUE TITLE
This is not a issue. This is a big thank you!

### ISSUE THREAD

**Issue by BenasPaulikas** [keylase/nvidia-patch#118]
It fixed my problems :) Thank you a lot!! Feel free to close this "issue"

**Comment by Shidapu** [comment]
I too want to say big thank you to the guys who managed this!! Im wondering if Windows server 2019 is possible?

**Comment by Snawoot** [comment]
Hi!

> Im wondering if Windows server 2019 is possible?
I think yes. Please open separate issue and fill details about requested driver version.
