### ISSUE TITLE
Does the ffmpeg 10 sessions trick support h265 as well?

### ISSUE THREAD

**Issue by rEd2k** [keylase/nvidia-patch#124]
Hello,

         I am curious if the ffmpeg 10 sessions trick also supports H265 as well. When I see it load I only see references to H264 sessions being loaded. If it already does support H265 and I do have the right idea to use it this way I hope to open sessions for H265 encodes/decodes as well. I hope I this possible as I have many H264 & H265 movies that always need real-time transcoding to H264/H265 vice versa etc. Do I even need to worry about this? I am sorry my knowledge of the ffmpeg script process for what is fully supported is limited and any help would be apprecieated. Also, sorry if I am asking about this in the wrong place, I did not know where else to ask :P

**Comment by Snawoot** [comment]
Hi!

It's OK to ask here, maybe some other users will search through issues and find answer they need.

Yes, it should work for h265 also. NVENC sessions are accounted without distinction by codec, so it doesn't matter which codec is used to bump session limit.

The goal of this trick is to open some number of concurrent NVENC sessions with 64bit app (like 64bit ffmpeg or NvencSessionLimitBump built for this purpose), so 32bit app shall be able to use same amount of sessions. It is some sort of workaround for patch which touches only 64bit driver library. Also note: this session bump trickery is required only if you plan to use D3D or 32bit apps (like Plex Media Server). Normally, you just need to apply patch.

**Comment by Saentist** [comment]
Simple test
```
ffmpeg -y -f lavfi -i nullsrc=s=256x256:d=5 -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null -
```
change to H265 and test

**Comment by rEd2k** [comment]
Thank you so much for your support Snawoot I really appreciate it! I am doing exactly what you stated and I am using the session limit patch for my plex server. I am unsure how to actually tell if the limit patch is working outside of using plex itself to try and transcode many videos at the same time. Any tips for this, or am I stuck using plex server as the only medium to find out?

**Comment by Snawoot** [comment]
@rEd2k there are few available options to check if patch is working on your system. Essentially all methods is "just try multiple sessions".
If you are already using ffmpeg to bump limit, check console output of program and see if there are any errors. **Hint**: to see console output before command line window closes you should run script in cmd.exe command line or just add `pause` line at end of script.
Also note: session limit bump has to be applied after each system restart, so it is recommended to add it to autorun.

**Comment by rEd2k** [comment]
Hi again, so the only thing close to an error I get is "EOF timestamp not reliable" in yellow color text, but that's it. I guess it's working just fine then! Thank you so much for all of your help Snawoot! :) We are so grateful in the community for people like you!
