### ISSUE TITLE
How do you determine these patches?

### ISSUE THREAD

**Issue by rlewkowicz** [keylase/nvidia-patch#125]
In your script, you're doing a sed on these encoded strings of some sort:

```
's/\x85\xC0\x89\xC5\x75\x18/\x29\xC0\x89\xC5\x90\x90/g'
```

Where's your entry point in searching for these things? Where can I start, what topics do I need to read on? The reason I ask, is because I'd like to do a patch to remove nvidia's sensitivity to virtualized environments. What is this string, and how did you start to find it?

**Comment by Snawoot** [comment]
Hi!

Here is post with original research behind this patch: [russian](https://habr.com/ru/post/262563/), [3rd party english translation](https://weekly-geekly.github.io/articles/262563/index.html). Basically, it's a regular GDB debugging of x86 assembly.

Speaking of virtualized environments, there exists [nvidia-kvm-patcher from sk1080](https://github.com/sk1080/nvidia-kvm-patcher), and I use his [recipe](https://github.com/sk1080/nvidia-kvm-patcher#preferred-alternative-for-recent-libvirt--qemu) for KVM on my testbed.

**Comment by rlewkowicz** [comment]
Thanks @Snawoot! Unfortunately that's for patching windows hosts. I'm trying to patch an Ubuntu guest running in hyperv with pci passthrough

**Comment by Snawoot** [comment]
FYI sk1080 patch also works for my ubuntu guest on KVM host (tested on Debian 9 and Fedora 30). As it seems from config parameters, it hides presence of KVM hypervisor and poses as Hyper-V hypervisor, so I thought it works out of the box on Hyper-V.
