### ISSUE TITLE
Working on Debian 9 Stretch?

### ISSUE THREAD

**Issue by shimmerdark** [keylase/nvidia-patch#133]
So I got this working on Debian the only problem I had was figuring out how to get the source for the kernel to get the nvidia driver to compile. 

Your patch and instructions were flawless except for how to install kernel source on debian. Could you maybe add this bit of instruction for debian users.

To install kernel source use
apt install linux-headers-$(uname -r)

So I can say for certain tested on Debian 9 Stretch as well. Below is a screen shot of nvidia-smi, on my server with a Quadro P1000

![2019-07-20 (2)](https://user-images.githubusercontent.com/48850427/61583313-10b09800-aafc-11e9-8acc-d7ded713a3e5.png)

**Comment by Snawoot** [comment]
Hello!

Patch doesn't require kernel sources directly, they are only needed for driver installer to build nvidia kernel module. So, kernel sources rather related to nvidia driver installation, not to patch.

As far as I can see from screenshot, you have already installed driver, so you may proceed straight to running `patch.sh`. Probably it is already installed by some deb package.

Speaking of kernel sources, I recommend installing `dkms` package. It'll pull all required dependencies required for building kernel modules, including kernel sources (headers), compiler and so on. Also Nvidia driver should detect DKMS presense and establish automatic module rebuild via DKMS framework when needed.

**Comment by Snawoot** [comment]
Sorry, I probably missed the point of issue, but now I get it. Pull request pending.

**Comment by Snawoot** [comment]
Closed via #134
