### ISSUE TITLE
Windows Server 2012 R2 - Wrong Offsets GTX 1070

### ISSUE THREAD

**Issue by NeSmo1** [keylase/nvidia-patch#136]
Heya!

First off wanted to say - This looks awesome and i cannot wait to try it.

However, with windows server 2012 r2 i am getting an offset [E35F7] Wrong...... Set 0x5 -> I Expected 0x74.

Bare in mind, Server 2012 r2 runs on a windows 8 kernel meaning i have to install the windows 8 GTX 1070 driver for it to work properly.

Using the 431.60 driver also.

Thanks and i am looking forward to your reply and insights!

**Comment by Snawoot** [comment]
Hi!

Try [this one](https://raw.githubusercontent.com/Snawoot/nvidia-patch/win7_431.60/win/win7_x64/431.60/nvcuvid.1337) and tell me if it works. I'll merge it into master branch then and consider support for legacy systems on regular basis.

**Comment by NeSmo1** [comment]
Hi Snawoot,

Worked a dream!

May i ask, what is this actually doing? Is it changing certain hexadecimal code that allows it to unlock?

**Comment by Snawoot** [comment]
Hi!

Thanks, that means we can proceed with Win7-Win8 support.

> May i ask, what is this actually doing? Is it changing certain hexadecimal code that allows it to unlock?

It's an edit of conditional jump in x86 assembly. ["See Also" section on main page](https://github.com/keylase/nvidia-patch#see-also) contains link to original research behind this patch, which briefly describes how this patch was inferred on Linux 4 years ago. Long story short: [GDB](https://en.wikipedia.org/wiki/GNU_Debugger) and direct assembly edit.
