### ISSUE TITLE
Offset [E29C7] Wrong

### ISSUE THREAD

**Issue by wesmannmsu** [keylase/nvidia-patch#157]
Hello, first, me and my "plex life" thank you for all your hard work on this patch!

I followed the instruction on a Windows 10 install (not VM) and got:

Offset [E29C7] Wrong
Set 0x79 -> I expected 0x74

My card is the:
ASUS TUF Gaming GeForce GTX 1660 Overclocked 6GB
During the install, it said it was NVIDIA Graphic Driver Version 430.86

The ASUS driver is "430.86-desktop-win10-64bit-international-whql.exe" from their website.

Is there more information I can provide to help with this?

Thank You

<img width="439" alt="Screen Shot 2019-09-12 at 7 05 14 PM" src="https://user-images.githubusercontent.com/55263090/64829036-491aa280-d590-11e9-898c-cb80cfffed84.png">

**Comment by wesmannmsu** [comment]
Yes sir, here it is

Thank you

[nvcuvid.dll.zip](https://github.com/keylase/nvidia-patch/files/3610243/nvcuvid.dll.zip)

**Comment by Snawoot** [comment]
As I can see this lib indeed belongs to 430.86 driver and `0xE29C7` (or `0xE35C7` in coordinates of .1337 file) is a correct offset for this file. I just tested and patched this file with patch utility and 430.86 patch file.

Probably you attempted to apply patch before library was actually updated by driver installer (like if file was in use by running application and upgrade took place after reboot). Please try applying patch again and ensure following items:

* "Fix Offset" checkbox is checked
* File path is correct (`%WINDIR%\system32\nvcuvid.dll`, same path which you get this file from when submitted it to me). Note: there also exists file `nvcuvid.dll` in `%WINDIR%\syswow64` directory and in maybe in some other - those are not the right one.

**Comment by wesmannmsu** [comment]
Thank you for your assistance, I tried it again and it worked. 

The only thing I changed was that I: 
Turned off Plex (that no one was accessing at the time) and 
Removed the HDMI Dummy Plug that was in the NVIDIA card. 

I think it was the dummy plug but can't say for sure.
