### ISSUE TITLE
New driver support (version 430.50)

### ISSUE THREAD

**Issue by dalgibbard** [keylase/nvidia-patch#159]
Hi! Thanks for helping the community with these patches!
A new driver has been released for Linux, details as follows.

- Nvidia driver version: [430.50]
- GPU Model: [Quadro P400]
- OS: [Ubuntu 18.04.03]
- [x] I'm willing to participate in testing of new patch version

Download URL:
https://www.nvidia.com/drivers/results/151568

Thanks in advance!

**Comment by Snawoot** [comment]
@dalgibbard 

Hello,

Thank you for information! It seems we missed this version because it was shadowed by other drivers with higher version number (like recent 435.21). I hope patch will be merged to master in a matter of hours.

**Comment by Snawoot** [comment]
Delivered to master branch via #160

**Comment by dalgibbard** [comment]
Super fast responses! Thank you so much- tested and working OK, have a great weekend!
