### ISSUE TITLE
Unraid 430.50 issues

### ISSUE THREAD

**Issue by Cessquill** [keylase/nvidia-patch#166]
Hi - I'm using a User Script to wget the patch and run it.  It is set to auto-run, and was just working.  However, I've noticed today that I get the message...

```
root@unRAID1:/opt/nvidia# bash ./patch.sh
Detected nvidia driver version: 430.50
Backup exists and driver file differ from backup. Skipping patch.
```

I'm on Unraid 6.7.3rc4 (Nvidia version), which is reporting 430.50 as installed, and patch.sh -c 430.50 is supported.  My full user script (minus the echos) is...

```
#!/bin/bash

mkdir -p /opt/nvidia
cd /opt/nvidia
rm -f patch.sh
wget --no-hsts https://raw.githubusercontent.com/keylase/nvidia-patch/master/patch.sh
bash ./patch.sh
```

I'm guessing I've missed something along the line, but not sure what.  Any help greatly appreciated.

**Comment by Snawoot** [comment]
Hello,

Recently patch.sh was modified to skip repeated patch attempt explicitly if file already differ from original.

So, this message is probably OK if patch already applied.

**Comment by Cessquill** [comment]
Ahh, thank you
