### ISSUE TITLE
New driver support (version 418.87.01)

### ISSUE THREAD

**Issue by shinctl** [keylase/nvidia-patch#169]
- Nvidia driver version: [418.87.01]
- GPU Model: [GTX 1060]
- OS: [e.g. Ubuntu 16.04]
- [x] I'm willing to participate in testing of new patch version

Driver download: http://us.download.nvidia.com/tesla/418.87/nvidia-driver-local-repo-ubuntu1604-418.87.01_1.0-1_amd64.deb

**Comment by Snawoot** [comment]
Hello,

Please test patch on [branch linux_418.87.01](https://github.com/keylase/nvidia-patch/tree/linux_418.87.01) and tell if it is OK.

**Comment by shinctl** [comment]
Detected nvidia driver version: 418.87.01
Attention! Backup not found. Copying current libnvcuvid.so to backup.
567d6e86e0478938a31400005acfdcb6b5fceb18  /opt/nvidia/libnvidia-encode-backup/libnvcuvid.so.418.87.01
f53e1b5658c6245da4f0f0a5182e8415a3d5bba5  /usr/lib/nvidia-418/libnvcuvid.so.418.87.01
Patched!

---

Also tested multiple ffmpeg instances, working perfectly fine. 

Thank you @Snawoot for your hard work!
