### ISSUE TITLE
Question: ubuntu 18.04, must I run the .run?

### ISSUE THREAD

**Issue by sfatula** [keylase/nvidia-patch#181]
Hello,

My question is: I am running ubuntu 18.04. The instructions say to download the nvidia run driver such as https://international.download.nvidia.com/XFree86/Linux-x86_64/430.40/NVIDIA-Linux-x86_64-430.40.run and run it, which fails for me (says pre-install script fails). But I am already running the ubuntu dist nvidia driver. Must I still do this step, I can't just run the patch against the ubuntu distribution version?

Supposedly I have to disable nouveau and other things on ubuntu, wanting to avoid.

**Comment by Snawoot** [comment]
Hello,

This is common misconception, so I think we need to outline this in our guide and adjust documentation accordingly.

You should skip .run installation step if you already have compatible driver installed by other means. The list of these links to .run installers is maintained for sake of universal approach which doesn't depend on specific distro packages.

I'll keep this issue open till the moment documentation will be fixed.

**Comment by sfatula** [comment]
Excellent, thanks! Was not clear to me if somehow their version might be different, etc.

**Comment by Snawoot** [comment]
@sfatula It's not clear for us either, but we haven't seen examples of really different drivers shipped with same version label through different package types.

**Comment by sfatula** [comment]
One more point for clarity, no system restart is needed after the patch?

**Comment by Snawoot** [comment]
Usually restart is not needed, but all processes using this library has to be restarted.
