### ISSUE TITLE
Changing limit to 5

### ISSUE THREAD

**Issue by phaelon74** [keylase/nvidia-patch#184]
Good afternoon, is there a way instead of removing the limit all together, we can change it to 5?  What we're seeing when using the removed limit is it's not falling back to CPU without a substantial detrimental experience.  On a GTX 1050ti, at 8 Streams, we see buffer on 1-2 devices.  At 10+ satreams everyone buffers.  We'd love it if we could set how many streams get HW encoded like the 2 limit.  the 2 Limit works really well faling back to CPU, so it'd be awesome if we could set it at 5 or 6 so the 1050Ti could do it's magic but then fall back to CPU for the next streams.

If this is not viable or very difficult no worries and thanks for all your hard work as this is an awesome project!  We're using Windows Server 2016 with the .dll from the Windows 10 64bit file.

**Comment by Snawoot** [comment]
Dup of #74 

Impractical / might have better imlementation on application side.
