### ISSUE TITLE
Running Windows 2016, ESXI VMware, passthrough 1050 TI.  patch not working.

### ISSUE THREAD

**Issue by nafeasonto** [keylase/nvidia-patch#187]
I used the x86 library patch, and the x64 patch.  According to the instructions i patched the wow64 file with the x86 patch, and x64 patch to the system32 file.

Plex is not breaking the two limit Hardware transcode.  I am running 441.20, and the card passthrough fine to WIndows 2016.

Is there something that I am missing here?

Running ESXI 6.7.

**Comment by Snawoot** [comment]
Hello,

It seems Plex encoder used NVENC encoder indirectly, via DX3D API. Please try following:

1. Try to bump limit with ffmpeg or NvencSessionBump utility: https://github.com/keylase/nvidia-patch/tree/master/win#d3d11-and-32-bit-apps-encoding-sessions
2. If it will not work, try the same with Nvidia driver version 431.94 or earlier.

**Comment by nafeasonto** [comment]
Am I supposed to be using the QUADRO drivers, even though I am  using a 1050 TI? Is that the case, because I tried already step one, many times.

Because there is no 431.94 driver available in GEFORCE.

**Comment by Snawoot** [comment]
Use 436.48 in this case. Any driver which works on your system with version number lower than 440.97.

**Comment by Snawoot** [comment]
Also we have issue #179 which suggests session bump technique doesn't works with newest drivers. I think your case is similar.

**Comment by nafeasonto** [comment]
Okay, I will try and report back.

**Comment by nafeasonto** [comment]
I installed the older drivers, patched them, ran NVECdumb,  and now nothing is HW transcoding.

**Comment by nafeasonto** [comment]
It's not hardware transcoding anything now.  Anything else i can try.

**Comment by Snawoot** [comment]
At least 2 sessions has to be HW transcoded either way, even without patch. Do you have HW transcoding enabled in your Plex server and Plex Pass account?

**Comment by nafeasonto** [comment]
yes, correct.

**Comment by Snawoot** [comment]
What is your output of `NvencSessionLimitBump.exe`? Does it opens 32 sessions successfully?

Hint, just in case: you can make console application output persist on screen if you are running it from `cmd.exe`.

**Comment by nafeasonto** [comment]
yes it says "succeeded"

**Comment by Snawoot** [comment]
It looks to me like some Plex issue, because driver and NVENC is OK, and it is easily verifiable with ffmpeg or some other NVENC-enabled video transcoder.

Is it possible you are transcoding to some codec which is not supported by HW transcoder (e. g. not H.264/H.265/VP9)? You should have at least 2 transcoding sessions enabled, try asking Plex support about that.

**Comment by nafeasonto** [comment]
I honestly don't know.  I am going to try a new install on a Windows 10 VM. And see if anything improves.  I have always had issues using Plex on a W2016 machine. Maybe it will make a difference, IDK.  But it can't hurt to try.

**Comment by Snawoot** [comment]
OK. Please tell us about any outcome of your trials. It's still unclear, if Plex is OK with new drivers.

**Comment by nafeasonto** [comment]
I will keep you posted.

**Comment by nafeasonto** [comment]
I am at a loss now.  It's not hardware transcoding anything now.  Either I missed something, or something is screwed up. Idk.

**Comment by Snawoot** [comment]
I don't think there is something to mess up. Try to transcode some movie with NVENC using ffmpeg to dispel your doubts about NVENC operability.

**Comment by nafeasonto** [comment]
I got it working, but its still limiting to 2. So no idea whats going on.
