### ISSUE TITLE
Doesn't work with 384.66

### ISSUE THREAD

**Issue by vmag** [keylase/nvidia-patch#2]
This patch doesn't work with Nvidia drivers version 384.66.

**Comment by keylase** [comment]
New drivers are not planned to be supported. Please, use 375.39

**Comment by m0hamedessam** [comment]
why not supported ?

**Comment by kotuk** [comment]
А не подскажете почему не хотите ковырять новые дрова? если нет на чем могу проедоставить доступ к машине для блага народа и моего тоже :)))

**Comment by p0rsche** [comment]
You guys should open up the disassembler and do it on your own. You could check out related article on habr.com.

**Comment by keylase** [comment]
please, check last version
