### ISSUE TITLE
Q: Is NvencSessionLimitBump necessary with latest patches? 

### ISSUE THREAD

**Issue by BIFFTAZ** [keylase/nvidia-patch#200]
Hi, Just asking is it necessary to use NvencSessionLimitBump (Have it in my startup folder) to bump the limit with the latest patches? Im only asking because ATM, I dont have enough devices to test this, & Opening multiple pages on the browsers always default back to direct stream. So it quite difficult to test right now until my friends/family start to use Plex.

Either way, Thanks for updating these patches to work with newer driver & removing the limit!!

**Comment by Snawoot** [comment]
Hi!

I believe NvencSessionLimitBump is not needed anymore for any available patch for Windows drivers. All past versions was reworked to get rid of earlier issues and required workarounds.
