### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY: out of memory

### ISSUE THREAD

**Issue by vans163** [keylase/nvidia-patch#201]
Is this normal 440.36 driver on Ubuntu 19.10.  Randomly happens. GTX 1660 Turing cards.  Before I used 1060s and never had this error, could even run 20 decoding/encoding sessions.  

```
[h264_nvenc @ 0x561355b9bcc0] dl_fn->cuda_dl->cuCtxCreate(&ctx->cu_context_internal, 0, cu_device) failed -> CUDA_ERROR_OUT_OF_MEMORY: out of memory
[h264_nvenc @ 0x561355b9bcc0] No NVENC capable devices found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```

**Comment by paulhothersall** [comment]
19.10 seems to use like 1GB of Ram just using the desktop. 
Each transcode even on a different GPU seems for me to be taking a 55MB resource hit on GPU0 thats additional to the actual encode, so in my case with 2 x Quadro 2GB cards its very easy to hit a ram limit. 

I have also found if you are doign lots of short transcodes, that the ram Lingers before being released. So you might be hitting that issue?

I charitably believe this might be why Nvidia might want to limit the number of sessions. They for sure don;t seem to overly care on the drivers so long as it "works" for the amount specified on the matrix. 

Are you doing some extra steps?

**Comment by Snawoot** [comment]
Hi!

Please verify you have enough VRAM to fit your encoding session. In order to do that:
1. Take a look at estimates for required VRAM amount here: https://www.elpamsoft.com/?p=Plex-Hardware-Transcoding ("Streams for VRAM" paragraph)
2. Check available VRAM with `nvidia-smi` utility.

**Comment by vans163** [comment]
Using -surfaces 8 on the decoder or not does not affect anything.

The VRAM is 6GB, I am only running 1 FFMPEG process per card with at most 2-3 multiplexed encodes.

![image](https://user-images.githubusercontent.com/3028982/69883924-33ba3800-12a4-11ea-9871-ba5af9ceb6db.png)

![image](https://user-images.githubusercontent.com/3028982/69883929-3ae14600-12a4-11ea-9476-ebdd8fdb5323.png)

I do have a lot of short transcodes for certain use cases, maybe I should sleep some time between them? But overall it seems to just crap out randomly, even though the cards have 4gb+ free VRAM available.

This is how the command looks like, I am thinking maybe its due to the scale_npp?

```
/root/ffmpeg -y -hide_banner -loglevel error  -hwaccel_device 1 -hwaccel cuvid -c:v h264_cuvid -gpu 1 -surfaces 8 -i "51e81a07-be48-4e68-a8da-47adc8c5f7ba.mp4"        -ss 00:09:00.0 -t 00:03:00.0 -vf scale_npp=1920:960:interp_algo=lanczos      -acodec aac -b:a 192000      -vcodec h264_nvenc -gpu 1 -b:v 1500000 -bufsize 1500000*2 -profile:v high         -preset slow -rc vbr_hq -rc-lookahead 20 -temporal-aq 1 -bf 3 -b_ref_mode 2 -coder:v cabac     -movflags +faststart "51e81a07-be48-4e68-a8da-47adc8c5f7ba/bd242a18-1f3b-43b9-b36a-8dec6d9ce7c9.mp4"    -ss 00:09:00.0 -t 00:03:00.0 -vf scale_npp=2560:1280:interp_algo=lanczos      -acodec aac -b:a 192000      -vcodec h264_nvenc -gpu 1 -b:v 10000000 -bufsize 10000000*2 -profile:v high         -preset slow -rc vbr_hq -rc-lookahead 20 -temporal-aq 1 -bf 3 -b_ref_mode 2 -coder:v cabac     -movflags +faststart "51e81a07-be48-4e68-a8da-47adc8c5f7ba/5cb87c30-5d02-4a8c-ae1d-38cf70b6b302.mp4"
```

```
[AVHWDeviceContext @ 0x55eb23d9ad00] cu->cuDeviceGet(&cu_device, device_idx) failed -> CUDA_ERROR_INVALID_DEVICE: invalid device ordinal 
[h264_cuvid @ 0x55eb24690640] Error creating a CUDA device cuvid hwaccel requested for input stream #0:0, but cannot be initialized.
[h264_cuvid @ 0x55eb24690640] ff_get_format failed: -1 Error while opening decoder for input stream #0:0 : Operation not permitted
```

**Comment by Snawoot** [comment]
I'm not quite sure about memory consumption, but I feel like indication may not display all allocated memory or there is something like 2GB memory limit per CUDA process. Can't say if `scale_npp` filter is the reason. But I found some info pointing out `scale_npp` is not needed in your case: [https://lists.ffmpeg.org/pipermail/ffmpeg-user/2017-November/037740.html](https://lists.ffmpeg.org/pipermail/ffmpeg-user/2017-November/037740.html). If you use `-hwaccel cuvid`, plain `-resize` should work on GPU if specified as a decoder option before input file name. So, it may be a good first step to try.

> Everything worked perfectly smooth and fine with ubuntu 16.04 and 6GB 1060s, same driver.

As far as I know 1660 is based on Turing architecture and it's NVENC engine pretty much different from 1060 counterpart. It may have different memory requirements from Pascal ones.

Here is some things to try:
1. Try to revert current patch and try `patch.sh` from commit [f674380a0b0](https://github.com/keylase/nvidia-patch/tree/f674380a0b0e3d1af54640ddb1091f4ef40f76a7). Recently patch was reworked and I'm not sure if it is the reason.
2. Compare ffmpeg versions used then and now. ffmpeg may have different way of handling CUDA things in newer versions.
3. Try to reproduce error on files with significantly larger or smaller resolution. It may give a clue if this error is truly related to amount of buffer memory.
4. Try to split ffmpeg processing pipeline into multiple processes. Namely, no more than one stream per process and maybe even separate process for decoding and resampling piped into encoder process. It probably may help if there is indeed a per-process limit for CUDA memory.
5. If it possible, try 1060 in place of your current configuration.

```
[AVHWDeviceContext @ 0x55eb23d9ad00] cu->cuDeviceGet(&cu_device, device_idx) failed -> CUDA_ERROR_INVALID_DEVICE: invalid device ordinal 
[h264_cuvid @ 0x55eb24690640] Error creating a CUDA device cuvid hwaccel requested for input stream #0:0, but cannot be initialized.
[h264_cuvid @ 0x55eb24690640] ff_get_format failed: -1 Error while opening decoder for input stream #0:0 : Operation not permitted
```

This one is clearly related to decoder. It complains about incorrect gpu number. If this error describes situation correctly, it means:
* It doesn't related to NVENC or patch.
* It'll take a deep digging into code of ffmpeg to figure out how it enumerates available GPUs and what causes GPU with valid number to disappear from this list.

**Comment by vans163** [comment]
Seems like will have to keep digging, also -resize does work but not for multiplexed outputs.  I seem to have fixed a bit of my issues using -vsync 2, really strange, but I need to confirm the video audio i synced.  That last error yea, just showing how maybe the card itself gets unstable.

**Comment by vans163** [comment]
So I was just testing a few things manually and randomly starting a session got
```
[h264_nvenc @ 0x55c69582ca00] CreateBitstreamBuffer failed: out of memory (10)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[aac @ 0x55c69582e580] Qavg: 65536.000
[aac @ 0x55c69582e580] 2 frames left in the queue on closing
[aac @ 0x55c695829100] Qavg: 65536.000
[aac @ 0x55c695829100] 2 frames left in the queue on closing
```

Then immediatly tried again the same ffmpeg command and everything worked. So weird and inconsistent.

**Comment by Snawoot** [comment]
That's clearly a memory allocation error. Without regard to memory-related error code, practically nvEncCreateBitstreamBuffer does nothing more than a memory allocation. What is your stream resolution?

**Comment by vans163** [comment]
```
width=3840
height=1920
fps=90
```

Its weird I run it again and everything works. Like a 1 time error, even tho the card has 0 processes on it and 0 used vram.

**Comment by Snawoot** [comment]
It's worth trying to modify ffmpeg source (I guess you built from source for NVENC support) and log amount of memory requested by nvEncCreateBitstreamBuffer. I think this number may vary.

**Comment by vans163** [comment]
So the out of memory seems sporadic, the fix is just to restart the job if it appears. Everything works fine there is enough memory, maybe my system is unstable / bad ACPI / bad PCIE slot?

**Comment by Snawoot** [comment]
Can't say for sure. You can try files with larger and smaller resolution and if issue never reproduces with smaller files and always reproduces with larger files, it's not that sporadic.

**Comment by 1265578519** [comment]
https://developer.nvidia.com/video-encode-decode-gpu-support-matrix

**Comment by vans163** [comment]
> Can't say for sure. You can try files with larger and smaller resolution and if issue never reproduces with smaller files and always reproduces with larger files, it's not that sporadic.

Like the same exact ffmepg commandline (job), on the same GPU, if it gets the out of cuda memory error, and I start the job again 100ms after, it works fine, nothing changed on the GPU itself in regards to memory.  Its like a random bug which makes me thing its related to shoddy hardware.

**Comment by 1265578519** [comment]
Max # of concurrent sessions 2

error
[h264_nvenc @ 000001dd6c5400c0] OpenEncodeSessionEx failed: out of memory (10)
[h264_nvenc @ 000001dd6c5400c0] No NVENC capable devices found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

你补丁未使用成功，就会提示这种错误，达到并发数量2，你重新安装patch sh试一下

**Comment by vans163** [comment]
@1265578519 It seems to be the case, randomly triggered, I just make it restart the job, and its fine the error is gone. Maybe some kind of race condition with the patch and driver interaction?

**Comment by 1265578519** [comment]
@vans163 我个人认为是Crack 不完整，得让开发者寻找BUG做更新解决

**Comment by vans163** [comment]
It only started happening for me on Turing cards, Pascal cards did not have this problem.

**Comment by Snawoot** [comment]
@vans163 Is there a change you have two drivers installed in your system? Like system packaged driver from repos and driver installed by run-file from Nvidia site?

@1265578519 Could you please use English? I guess no one will be happy if I'll speak exclusively in my native Russian.

**Comment by vans163** [comment]
@Snawoot You guess wrong!

Maybe something is funky, I installed the official ubuntu package driver, noticed the issue, removed it placed NVIDIA blob driver, same issue (theres like a set of 3 different errors, but they all are non-critical).  I could keep an eye on and eventually report if I build another rig, it might be some hardware issue?

**Comment by Snawoot** [comment]
Well, I had hardware issues only with power supply unit and it peeped out when encoding stops. It seems sometimes it caused one of PSU voltages rapidly go back to normal level and system hang. But no hardware issues I had were causing clear software error code CUDA_ERROR_OUT_OF_MEMORY (which, I admit, is indeed inherent to session limit).

However, there are few notable points in problems you described:
* `cuDeviceGet` sometimes fails like wrong device number was specified or so. Patch doesn't touch anything around it.
* When unpatched encoder is out of sessions it throws error `CUDA_ERROR_OUT_OF_MEMORY` in `nvEncOpenEncodeSessionEx` but not in `cuCtxCreate`. It's a big difference. As far as I understand that context isn't even NVENC-specific. In other words, it fails even before program says "I'd like to encode, please".
* `CreateBitstreamBuffer` is also not a function where encoding sessions semaphore is acquired. We had issues with it in past (#13), but I can't recall any recent complaint on it.

So, yes, I believe your issue is specific to your platform, but I can't rectify reason.

But I've got some fresh idea for you: best patch is no patch at all. You said before normally you have one or so video encoding session per GPU. I guess only reason why you have to use this patch is multiple GeForce GPUs still have total limit in 2 encoding sessions (also, this situation effectively invalidates hypothesis that there is any real reason for 2 sessions restriction). But if your system is VT-x capable, you can create few virtual machines, each for one GPU, and assign GPUs to VMs with pci-passthrough. You'll have separate systems with distinct limits for each card in one physical box. BTW, pci-passthrough into KVM virtual machine is how I do tests: I have Linux host system on my PC, and assign GTX 1080 to Win10 or Ubuntu VM for tests. Here is resources which might be helpful:
* https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF - about PCI passthrough in QEMU-KVM
* https://github.com/sk1080/nvidia-kvm-patcher#preferred-alternative-for-recent-libvirt--qemu - libvirtd config to hide virtualization and make Nvidia driver work inside VM (otherwise it refuses).

**Comment by vans163** [comment]
This is what works for me

```elixir
String.contains?(error_text, "CreateBitstreamBuffer failed: out of memory (10)")
or String.contains?(error_text, "CUDA_ERROR_OUT_OF_MEMORY: out of memory")
or String.contains?(error_text, "CUDA_ERROR_NOT_INITIALIZED: initialization error")
or String.contains?(error_text, "CUDA_ERROR_INVALID_DEVICE: invalid device ordinal") ->
        IO.inspect "retrying transcode.."
```

Those are the 4 errors I an simply restarting the transcode on, and everything works.  Let me eventually circle back if the problem goes away changing hardware / disabling patch. 

My tests showed that keeping the limit at 2, even with patch, there is no problem. The errors dont occur.
