### ISSUE TITLE
Question: Similar patch possible for NvFBC? (video capturing)

### ISSUE THREAD

**Issue by juicefreak** [keylase/nvidia-patch#202]
Hello,

My question is: Has anyone looked into the possibility of enabling unrestricted use of this feature on GeForce cards?

Nvidia says NvFBC is only supported on Quadros (and trying some examples from the Capture SDK they indeed don't work on my GeForce card), but somehow magically GeForce Experience on Windows uses NvFBC for streaming/recording. Steam's InHome Streaming also uses it on both Linux and Windows.

OBS performance on Linux honestly sucks versus the Windows version due to X limitations (though it's still usable in many cases). Having this method to capture video available could possibly help a lot.

(also NvIFR could be nice for capturing games running in windowed mode, but it seems Nvidia has deprecated it starting from Capture SDK v7.1 so who knows how long it'll stay...)

**Comment by Snawoot** [comment]
Hello,

I personally didn't looked into that, but [it looks like it is possible](https://github.com/keylase/nvidia-patch/issues/128#issuecomment-507314655). Maybe @vans163 knows more about it.

**Comment by vans163** [comment]
Lol why would I know more about it? Oh just google it, https://pastebin.pl/view/45421e05.

**Comment by juicefreak** [comment]
I tried adding

`uint32_t magic[] = { 0x0D7BC620, 0x4C17E142, 0x5E6B5997, 0x4B5A855B };`

and

```
createHandleParams.prilibnvidia-vateData = &magic;
createHandleParams.privateDataSize = sizeof(magic);
```

just before `fbcStatus = pFn.nvFBCCreateHandle(&fbcHandle, &createHandleParams);` in NvHBCHwEnc.c from Capture SDK 7.1 samples, but it's still saying "This hardware does not support NvFBC". Maybe the password is different on Linux or I'm doing something wrong...

The error message is from code in libnvidia-fbc.so.440.31.

For the record, my card is a GTX770. It's old but it should have NvFBC support AFAIK, Kepler is the first gen with it actually. I have a 2070S card coming in the mail currently, so soon I will be able to test this on Turing too.

There seems to be no equivalent of NvFBCEnable.exe included with the Linux Capture SDK.

**Comment by Snawoot** [comment]
OK, I'm on it. I'll post some feedback soon.

**Comment by Snawoot** [comment]
Please try `patch-fbc.sh` from [fbc branch of my fork](https://github.com/Snawoot/nvidia-patch/tree/fbc) and inform us about your results.

**Comment by juicefreak** [comment]
It works great! Thanks!

Now I just need to get OBS with NvFBC support working. :)

**Comment by juicefreak** [comment]
For anybody else possibly interested in using NvFBC for streaming in Linux, [this](https://gitlab.com/fzwoch/obs-nvfbc) source plugin for OBS Studio was very easy to compile and works with this driver hack. Performance seems better than Xcomposite and especially XSHM capture methods as expected.

Closing the issue, thanks again for your time.
