### ISSUE TITLE
Windows crash when running 16 ffmpeg codec sessions simultaneously

### ISSUE THREAD

**Issue by oyzw0720** [keylase/nvidia-patch#214]
**Describe the bug**
When I run 16 ffmpeg encoding sessions simultaneously on Windows 2019 (there are 8 GPU cards of RTX2080Ti, each GPU run 2 sessions), the windows system will crash in hours, there is no dump core created and system log shows nothing. Have you met this issue?

**To Reproduce**
1. install nvidia driver 441.41
2. install the patch for 441.41
3. run ffmpeg encoding session: 
set /a count=0
:loop
set /a count+=1
echo ===========count:%count%===========
echo --------test1--------
.\ffmpeg.exe -hwaccel cuvid -hwaccel_device %1 -c:v hevc_cuvid -y -vsync 0 -i ./egs-test/input/Ghost_Towns_8k.mp4 -c:v hevc_nvenc -preset fast ./egs-test/output/Ghost_Towns_8k_hevc_nvenc+fast.mp4
timeout 2
echo --------test2--------
.\ffmpeg.exe -hwaccel cuvid -hwaccel_device %1 -c:v hevc_cuvid -y -vsync 0 -i ./egs-test/input/Ghost_Towns_8k_10le.mp4 -c:v hevc_nvenc -preset medium ./egs-test/output/Ghost_Towns_8k_10le_hevc_nvenc+medium.mp4
timeout 2
echo --------test3--------
.\ffmpeg.exe -hwaccel cuvid -hwaccel_device %1 -c:v hevc_cuvid -y -vsync 0 -i ./egs-test/input/Ghost_Towns_8k_12le.mp4 -c:v hevc_nvenc -preset fast ./egs-test/output/Ghost_Towns_8k_12le_hevc_nvenc+fast.mp4
timeout 2
echo --------test4--------
.\ffmpeg.exe -hwaccel cuvid -hwaccel_device %1 -c:v h264_cuvid -y -vsync 0 -i ./egs-test/input/ducks_take_off_1080p50_10times_h264_6M.mp4 -c:v hevc_nvenc -preset fast ./egs-test/output/ducks_take_off_1080p50_10times_h264_6M_hevc_nvenc+fast.mp4
timeout 2
echo --------test5--------
.\ffmpeg.exe -hwaccel cuvid -hwaccel_device %1 -c:v hevc_cuvid -y -vsync 0 -i ./egs-test/input/ducks_take_off_1080p50_10times_hevc_6M.mp4 -c:v hevc_nvenc -preset fast ./egs-test/output/ducks_take_off_1080p50_10times_hevc_6M_hevc_nvenc+fast.mp4
timeout 2
echo --------test6--------
.\ffmpeg.exe -hwaccel cuvid -hwaccel_device %1 -c:v h264_cuvid -y -vsync 0 -i ./egs-test/input/ducks_take_off_2160p50_3times_h264_40M.mp4 -c:v h264_nvenc -preset fast ./egs-test/output/ducks_take_off_2160p50_3times_h264_40M_h264_nvenc+fast.mp4
timeout 2
echo --------test7--------
.\ffmpeg.exe -hwaccel cuvid -hwaccel_device %1 -c:v h264_cuvid -y -vsync 0 -i ./egs-test/input/ducks_take_off_2160p50_3times_h264_40M.mp4 -c:v hevc_nvenc -preset fast ./egs-test/output/ducks_take_off_2160p50_3times_h264_40M_hevc_nvenc+fast.mp4
timeout 2
echo --------test8--------
.\ffmpeg.exe -hwaccel cuvid -hwaccel_device %1 -c:v h264_cuvid -y -vsync 0 -i ./egs-test/input/ducks_take_off_2160p50_3times_h264_40M.mp4 -c:v hevc_nvenc -preset medium ./egs-test/output/ducks_take_off_2160p50_3times_h264_40M_hevc_nvenc+medium.mp4
goto loop
4. about 2~3 hours the windows crashed

**Expected behavior**
encoding sessions runs stably

**Output listings**
If applicable, add output listings or screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: Windows server 2019 DC
 - GPU model: RTX 2080Ti
 - Patch commit used: 
https://raw.githubusercontent.com/keylase/nvidia-patch/master/win/win10_x64/441.41/nvencodeapi64.1337
https://raw.githubusercontent.com/keylase/nvidia-patch/master/win/win10_x64/441.41/nvencodeapi.1337
 - Nvidia driver version: 441.41

**Additional context**

**Comment by Snawoot** [comment]
Hi,

Sometimes I had my system hang when video transcoding gets finished (it was single-GPU system). Probably in my case GPU was causing slight voltage spike when it was stopping short. I feel like your issue is also power related.

**Comment by oyzw0720** [comment]
Hi Snawoot,
Thanks for your reply. I've upgrade my GPU driver to 441.66 recently, until now the ffmpeg runs fine. So maybe it's the GPU driver which is not stable caused this issue. I'll keep testing this codec and if the problem no longer occurs I'll close this issue.
