### ISSUE TITLE
New driver support (version 440.43.01)

### ISSUE THREAD

**Issue by EdLovecraft** [keylase/nvidia-patch#216]
- Nvidia driver version: 440.43.01
- GPU Model: GTX 1080 Ti
- OS: Arch Linux
- I'm willing to participate in testing of new patch version

**Comment by Snawoot** [comment]
Hi!

Where can I download this driver? I can't find it on Nvidia site.

**Comment by EdLovecraft** [comment]
> Hi!
> 
> Where can I download this driver? I can't find it on Nvidia site.

https://developer.nvidia.com/vulkan-driver

**Comment by Snawoot** [comment]
Merged via #217
