### ISSUE TITLE
Suggestion not so much of an issue. 

### ISSUE THREAD

**Issue by SmoothAdmin** [keylase/nvidia-patch#220]
Sorry I don't see a link anywhere to a forum to make this suggestion. 

We all know that Plex as it currently with unrestricted graphics cards for transcoding doesn't push over to CPU trandcoding if he GPU is maxed out. The only way it will do this is if the GPU is set to only allow x number of transcodes as we see in the Nvidia list of graphics cards. So my suggestion is to create some way to allow the user to lock the card at 10 transcodes instead of unrestricted with your patch this way when the hit the max the rest of the trancodes will all over to the CPU. 

Maybe this is too hard to achieve right now, I am not a programmer.

**Comment by Snawoot** [comment]
Duplicates #74, #184
