### ISSUE TITLE
Question: Am I missing something w/r/t capitalization?

### ISSUE THREAD

**Issue by camh** [keylase/nvidia-patch#222]
Hello,

I'm trying to apply this patch on Windows 10 with a GTX 1080. I've tried driver version 440.97 and 441.66 (clean install each time). Both times I download the x64 and x86 patches, but when I try to apply them, the DLL files do not show up in the Win_1337_Apply_Patch tool.

Took a look at the DLL files and they are `nvEncodeAPI.dll` and `nvEncodeAPI64.dll`. Does capitalization matter? The patches are named `nvencodeapi.1337` and `nvencodeapi64.1337`, so I assume the patch tool is looking for an exact match for filename and can't find it.

**Comment by Snawoot** [comment]
Hello,

No, it shouldn't matter. Files should appear as you choose directory containing them in file select dialogue. If they are not there, please attach screenshot of file select dialogue, so we can seek for any clues.

**Comment by camh** [comment]
<img width="994" alt="Screen Shot 2020-01-10 at 1 37 01 PM" src="https://user-images.githubusercontent.com/58625/72212875-38812700-34b3-11ea-85b9-1ff20d4acdcf.png">

It looks like this. The dialog is scrolled all the way to the bottom and nothing shows up.

**Comment by Snawoot** [comment]
You are looking for nvencodeapi.dll in system32 directory, but it is located in C:\WINDOWS\SysWOW64\nvencodeapi.dll. And nvencodeapi64.dll is located in system32. It's kind of controversial, yes.

**Comment by camh** [comment]
Ahhh I see. Yeah they are not in the place you'd think.
