### ISSUE TITLE
Error (Problem occuered when Patching...) 

### ISSUE THREAD

**Issue by grandmst20** [keylase/nvidia-patch#231]
Windows 10 x64 (1809 Build 17763.973)
NVIDIA GeForce GTX 960 (2GB)
Driver version: 441.87

The patcher works for nvencodeapi64, but gives an error with nvencodeapi. This happened on a previous driver as well, so I changed the driver to the newer one and am still receiving the error. Tried running as admin as well, same issue.

**Comment by Snawoot** [comment]
Hello,

Could you please attach screenshot with error somehow?
