### ISSUE TITLE
10 ffmpeg encode the linux computer Crash in 10 or 15days

### ISSUE THREAD

**Issue by gaopeipeiok** [keylase/nvidia-patch#235]
I have run 10 ffmpeg to decode rtsp stream，and then run 10 ffmpeg to encode the streams，push the streams to rtsp server and rtmp server，after 10 or 15 days the computer cash。The network is disable and the computer have no response，I have to force restart the computer。 
The CPU and GPU run normal before 5 seconds，and I cannot find any fault logs。
**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - GPU model: 2080Ti
 - Patch commit used: Commits on Dec 8, 2019 4d0c1e33f22b4396544e4bd505a22da5ab09fdfc
 - Nvidia driver version: 410

**Comment by Snawoot** [comment]
Hello,

It's most likely a hardware problem. First of all you should check your power supply unit.

**Comment by gaopeipeiok** [comment]
Thanks for your response. When the server crash,the screen can show the last picture,so the server have power。 Do you have any  other idea about the crash, thank you very much！

**Comment by Snawoot** [comment]
Hi!

> When the server crash,the screen can show the last picture,so the server have power.

Power issues not necessarily lead to complete power failure, so it still can be it. Have you tried monitoring output voltages of your PSU?

**Comment by vans163** [comment]
journalctl -n and check for any errors from nvidia driver. This seems like to me nvidia driver is crashing, an easy way to know is if you can open a TTY (instead of relying on X11 or Wayland if your using that, which will deadlock along with the driver), since you mentioned last picture is visible.

**Comment by gaopeipeiok** [comment]
thanks for your reply.but the mouse and keyboard cannot use when the server crash,the network  cannot use too.

**Comment by gaopeipeiok** [comment]
I change the system to Ubuntu16.04.6  nvidia driver 440.59, cuda 10.2,ffmpeg the latest and the nv-codec-header the latest too, the encode speed change very slow. almost 10ms encode one frame .who can help me.

**Comment by Snawoot** [comment]
Try to catch panic output (if any) with Netconsole module: https://wiki.archlinux.org/index.php/Netconsole That's ArchWiki, but usable for ubuntu too.

Generic recommendation: use latest software. Ubuntu 16.04 is quite old.

Either way, I still do not see connection between patch and your crashes. Obviously, debugging crashes of one particular system is out of scope for this project. Closing issue.
