### ISSUE TITLE
Question: Proxmox lxc or kvm or esxi

### ISSUE THREAD

**Issue by barhom** [keylase/nvidia-patch#251]
Hello,

Does this patch work in proxmox KVM or ESXI? 
I have a server with several GPUs. And I want to launch one VM with one GPU each.

Is this possible ? 

(Also, does it work with lxc container to give access to only 1 gpu?)

**Comment by nerijus** [comment]
This patch works everywhere where nvidia drivers work.
I don't think it is possible for lxc container to have access to gpu, but it is not a question for this project.

**Comment by ezonakiusagi** [comment]
For lxc the host has to have the Nvidia driver. Then you apply this patch to the host once you have the Nvidia driver installed. To pass gpu to lxc container, you can see this video:

https://youtu.be/n7U1DLLGquY

That's what you want to do right?

⁣Get BlueMail for Android ​

**Comment by barhom** [comment]
> For lxc the host has to have the Nvidia driver. Then you apply this patch to the host once you have the Nvidia driver installed. To pass gpu to lxc container, you can see this video: https://youtu.be/n7U1DLLGquY That's what you want to do right? ⁣Get BlueMail for Android ​


I have a server with multiplex GPUs. And I want to assign each "virtual server" its own dedicated gpu.

One way would be LXC, if possible, the other way would be through KVM where I would pass the entire pcie device.

Do you know if it's possible to run this patch inside a KVM and have the Nvidia drivers run properly ? 
I heard that Nvidia blocks virtualization.

**Comment by nerijus** [comment]
How does nvidia block virtualization?
Again, if you install nvidia drivers in a KVM VM and they work (they worked for me last time), then the patch will work too.

**Comment by barhom** [comment]
> How does nvidia block virtualization?

I googled a bit more now. Seems they block vGPU and not passthrough.

> Again, if you install nvidia drivers in a KVM VM and they work (they worked for me last time), then the patch will work too.

Great! I will try this then. 

Closing the ticket.

**Comment by barhom** [comment]
I am reopening this question because I am failing to load the nvidia driver inside a KVM.
This is what happens,

root@:~# nvidia-smi 
Unable to determine the device handle for GPU 0000:00:10.0: Unknown Error

I think this is because nvidia specifically forbids GPUs from running in a KVM.

Any ideas?

**Comment by Snawoot** [comment]
@barhom this subject is covered by a separate project from other people: https://github.com/sk1080/nvidia-kvm-patcher

Personally I use KVM config method: https://github.com/sk1080/nvidia-kvm-patcher#preferred-alternative-for-recent-libvirt--qemu

Closing issue since it is out of our scope.

**Comment by gordan-bobic** [comment]
You need to hide the hypervisor from the checks the driver performs. You will need something like this on your qemu-kvm command line:
```
-cpu ' host,kvm=off,hv_vendor_id=null'
```
The driver will only initialise specific Quadro/Tesla/Grid devices that Nvidia deems expensive enough to be allowed to run in a VM when it detects a hypervisor.
