### ISSUE TITLE
Question: Is there any windows Project that makes use of nvfbcwrp?

### ISSUE THREAD

**Issue by Spamm00r** [keylase/nvidia-patch#261]
Hello,

My question is: 

I have patched my NVIDIA Drivers on WIndows 10 per instructions and tested it with 5 multiple NVENC sessions running at the same time and maxing out my GTX 1060.

So everything is runing fine.

I also replaced the dll's for nvfbcwrp.

But how do I test nvfbcwrp now?  Is there any Windows application that makes use of the nvfbcwrp patch/wrapper and can capture using NVFBC?

I couldn't find any.

**Comment by Snawoot** [comment]
Hello,

Usually NVFBC on Windows was tested with examples compiled from [Nvidia Capture SDK](https://developer.nvidia.com/capture-sdk). I guess NVFBC is also supported by [Looking Glass](https://looking-glass.hostfission.com/) and maybe it is possible to port [NVFBC plugin for OBS on Linux](https://gitlab.com/fzwoch/obs-nvfbc) to Windows.

**Comment by gordan-bobic** [comment]
I seem to recall that Steam has a tick box to use it if available.

**Comment by Spamm00r** [comment]
Yes there is this steam setting but how do  people use it without the patch and wrapper?

**Comment by Snawoot** [comment]
> Yes there is this steam setting but how do people use it without the patch and wrapper?

On high-end Quadro cards, obviously

**Comment by ValZapod** [comment]
Guys, can we support fork of looking glass with support for nvfbc?

**Comment by Snawoot** [comment]
@ValZapod 

Unlikely anyone will answer. I'm not maintaining this project anymore, but was still subscribed to this issue. Create new issue with your question to ask new maintainer.
