### ISSUE TITLE
New driver support (version 418.113)

### ISSUE THREAD

**Issue by ggnull35** [keylase/nvidia-patch#262]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 418.113
- GPU Model: All series
- OS: Ubuntu 14.04, 16.04, 18.04
- [x] I'm willing to participate in testing of new patch version

http://us.download.nvidia.com/XFree86/Linux-x86_64/418.113/NVIDIA-Linux-x86_64-418.113.run

**Comment by ggnull35** [comment]
Adding 2 lines makes a working patch:
    
`
["418.87.00"]='s/\x00\x00\x00\x84\xc0\x0f\x84\x0f\xfd\xff\xff/\x00\x00\x00\x84\xc0\x90\x90\x90\x90\x90\x90/g'
    ["418.87.01"]='s/\x00\x00\x00\x84\xc0\x0f\x84\x0f\xfd\xff\xff/\x00\x00\x00\x84\xc0\x90\x90\x90\x90\x90\x90/g'
    ["418.88"]='s/\x00\x00\x00\x84\xc0\x0f\x84\x0f\xfd\xff\xff/\x00\x00\x00\x84\xc0\x90\x90\x90\x90\x90\x90/g'
    + ["418.113"]='s/\x00\x00\x00\x84\xc0\x0f\x84\x0f\xfd\xff\xff/\x00\x00\x00\x84\xc0\x90\x90\x90\x90\x90\x90/g'
`

`
    ["418.87.00"]='libnvcuvid.so'
    ["418.87.01"]='libnvcuvid.so'
    ["418.88"]='libnvcuvid.so'
+    ["418.113"]='libnvcuvid.so'

`

**Comment by Snawoot** [comment]
Thanks! Merged via #263
