### ISSUE TITLE
Offset [2EE3A] Wrong... Set 0CC -> I expected 0x8B [Windows 10 Enterprise, 445.87]

### ISSUE THREAD

**Issue by FreiherrKenny** [keylase/nvidia-patch#264]
Specs

- GeForce GT710

- i7 2600k

- Windows 10 Enterprise (10.0.18363.778)

After installing the latest nVidia driver (445.87) and restarting the system i tried to apply the "GeForce 445.87 x64 library Patch - nvencodeapi64.1337" file to "c:\Windows\System32\nvEncodeAPI64.dll".

But the patcher returns with "Offset [2EE3A] Wrong...\nSet 0CC -> I expected 0x8B"

Here is my [nvEncodeAPI64.dll](https://github.com/keylase/nvidia-patch/files/4569963/nvEncodeAPI64.zip) zipped

**Comment by Snawoot** [comment]
Hi!

It does not look like this file belongs to 445.87 version. Check your actual installed driver version with a `nvidia-smi` utility or by the other means.

Pattern in file you have provided looks matching to one of these versions:

```
./win/ws2016_x64/quadro_431.94/nvencodeapi64.1337
./win/ws2016_x64/quadro_431.86/nvencodeapi64.1337
./win/ws2016_x64/quadro_431.70/nvencodeapi64.1337
./win/win10_x64/431.60/nvencodeapi64.1337
./win/win10_x64/quadro_431.94/nvencodeapi64.1337
./win/win10_x64/quadro_431.86/nvencodeapi64.1337
./win/win10_x64/nsd_431.86/nvencodeapi64.1337
./win/win10_x64/quadro_431.70/nvencodeapi64.1337
./win/win10_x64/nsd_431.70/nvencodeapi64.1337
```

**Comment by FreiherrKenny** [comment]
`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 432.00       Driver Version: 432.00       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 710     WDDM  | 00000000:01:00.0 N/A |                  N/A |
| 50%   37C    P0    N/A /  N/A |    178MiB /  1024MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
!
`
But windows tells me this:
[nvidia 445.87](https://user-images.githubusercontent.com/64729610/80914894-dfcde680-8d4e-11ea-9af0-717e8d3c94e8.png)

Should i just go for the GeForce 431.60 patch then?

**Comment by Snawoot** [comment]
I guess you should try the Display Driver Uninstaller, remove all drivers completely and prevent Windows Updates from installing it's version of driver (this option should be available in DDU). Then install latest Nvidia driver and proceed to usual patch flow.
