### ISSUE TITLE
Sometimes happens "Something went wrong. Check nvidia driver" inside docker

### ISSUE THREAD

**Issue by vBLFTePebWNi6c** [keylase/nvidia-patch#267]
**Describe the bug**
Sometimes patch failed to apply inside docker container with error message "Something went wrong. Check nvidia driver".

**To Reproduce**
I wrote simple bash script to check if problem exists and run in on two different machines.
Bash script:
```
#!/bin/bash
COUNTER=0
for i in {1..25}
do
   CATCH=$(docker run --gpus all --rm nvidia-patch:latest | grep "Something went wrong.")
   if [ -z "$CATCH" ]
    then
        COUNTER=$COUNTER
    else
        COUNTER=$(($COUNTER + 1))
    fi
done

echo "Catched $COUNTER/25"
```

There is almost always about 3-5/25 cases of failure.

**Expected behavior**
I expect that the patch script will work always correctly or at least will raise more descriptive error message that can help understand the problem.

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - GPU model: GTX 1080Ti
 - Patch commit used: aed35c39028ed4ec2250176e84fa3beea67f35c5
 - Nvidia driver version: 418.67, 418.87.00

**Comment by Snawoot** [comment]
Hi!

That means `nvidia-smi` utility sometimes fails to run inside container.

**Comment by vBLFTePebWNi6c** [comment]
@Snawoot hi! Thanks for the explaination!

Do you have any thoughts why `nvidia-smi` could fail inside a container and how I can make the error message more informative?

**Comment by Snawoot** [comment]
@vBLFTePebWNi6c Nope. Try running it manually to see what error it throws.
