### ISSUE TITLE
I installed this nvidia-patch but still has two encode limit on 2080ti

### ISSUE THREAD

**Issue by lialin86** [keylase/nvidia-patch#278]
Hello,

Here is the patch libs:
ls /patched-lib/
libnvcuvid.so  libnvcuvid.so.1  libnvcuvid.so.418.87.00
I link them to my projects, then it failed to call avcodec_send_frame if I add more than two videos on a 2080ti machine.(it is ok at T4 machine)

what is the problem?
it didn't patch libnvidia-encode.so.418.87.00, is it ok?

**Comment by Snawoot** [comment]
Hi,

How exactly you specified path to `/patched-lib/` as an override to system libraries?

**Comment by lialin86** [comment]
Hi,

I copy them to my specifiied folder and link to it:
ldd ./video_analyze | grep libnvcuvid
        libnvcuvid.so.1 => /home/videoanalyze/nvidia_lib/libnvcuvid.so.1 (0x00007f4f206f1000)
[root@325d8f50d5eb videoanalyze]# md5sum nvidia_lib/libnvcuvid.so.418.87.00
a5b5ba551f28676a696054860ccf4725  nvidia_lib/libnvcuvid.so.418.87.00
[root@325d8f50d5eb videoanalyze]# md5sum /patched-lib/libnvcuvid.so.418.87.00
a5b5ba551f28676a696054860ccf4725  /patched-lib/libnvcuvid.so.418.87.00

**Comment by Snawoot** [comment]
I think this is not going to work. Nvidia libraries use `dl_open` extensively and load binary image of dependent library via dynamic linker. No matter if library with the same name already linked to process image, it's functions referenced by handle returned by dl_open.

You should try to link your app as usual, but override search path of dynamic linker with `LD_LIBRARY_PATH` variable. Something like this:

```sh
LD_LIBRARY_PATH=/home/videoanalyze/nvidia_lib/ ./video_analyze
```

I'm pretty sure this trick should work: such technique worked with docker containers where it was not possible to patch system library directly (see bottom of #131, we did same override to LD_LIBRARY_PATH).

**Comment by lialin86** [comment]
Hi,

I already has path /home/videoanalyze/nvidia_lib in my LD_LIBRARY_PATH.
you mean nvidia dl_open load an old library not the patch one?

ls /usr/lib64/libnvcuvid.so.* -lh
lrwxrwxrwx 1 root root   36 Jun 17 11:24 /usr/lib64/libnvcuvid.so.1 -> /patched-lib/libnvcuvid.so.418.87.00
-rwxr-xr-x 1 root root 3.1M Jun 17 02:18 /usr/lib64/libnvcuvid.so.418.87.00

/usr/lib64/libnvcuvid.so.418.87.00 is the old library which I failed to delete it, I link /usr/lib64/libnvcuvid.so.1 to the patch library but it is still had the limit.

**Comment by Snawoot** [comment]
> do you mean nvidia dl_open load an old library not the patch one?

Yes, I think it is very likely

In your application which value has `NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS::device` parameter of `NvEncOpenEncodeSessionEx`? Is it `NV_ENC_DEVICE_TYPE_CUDA` or `NV_ENC_DEVICE_TYPE_OPENGL`?

**Comment by Snawoot** [comment]
Also please attach output of `env` and `ldconfig -v` from your session within which you run your application.

**Comment by lialin86** [comment]
deviceType = NV_ENC_DEVICE_TYPE_CUDA

 env
HOSTNAME=325d8f50d5eb
NVIDIA_REQUIRE_CUDA=cuda>=10.0 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411
TERM=xterm
LIBRARY_PATH=/usr/local/cuda/lib64/stubs
OLDPWD=/usr/lib64
LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64/:/home/videoanalyze/alg_plugin/mix_plugin/:/home/videoanalyze/alg_plugin/video_stream/:/home/videoanalyze/nvidia_lib:/home/videoanalyze/third_party:/home/videoanalyze/ext_lib:/home/videoanalyze:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/home/videoanalyze
CUDA_PKG_VERSION=10-0-10.0.130-1
CUDA_VERSION=10.0.130
HOME=/root
SHLVL=1
_=/usr/bin/env

ldconfig -v
ldconfig: Can't stat /usr/local/nvidia/lib: No such file or directory
ldconfig: Can't stat /usr/local/nvidia/lib64: No such file or directory
ldconfig: Can't stat /libx32: No such file or directory
ldconfig: Path `/usr/lib' given more than once
ldconfig: Path `/usr/lib64' given more than once
ldconfig: Can't stat /usr/libx32: No such file or directory
/patched-lib:
        libnvcuvid.so.1 -> libnvcuvid.so.418.87.00
/usr/local/cuda-10.0/targets/x86_64-linux/lib:
        libcudart.so.10.0 -> libcudart.so.10.0.130
        libnvrtc.so.10.0 -> libnvrtc.so.10.0.130
        libnvrtc-builtins.so.10.0 -> libnvrtc-builtins.so.10.0.130
        libnvjpeg.so.10.0 -> libnvjpeg.so.10.0.318
        ......
/lib:
/lib64:
        libz.so.1 -> libz.so.1.2.7
        libxml2.so.2 -> libxml2.so.2.9.1
        libverto.so.1 -> libverto.so.1.0.0
        libuuid.so.1 -> libuuid.so.1.3.0
        libutil.so.1 -> libutil-2.17.so
        libutempter.so.0 -> libutempter.so.1.1.6
        libustr-1.0.so.1 -> libustr-1.0.so.1.0.4
       ......
ldconfig: /lib64/libgraphite2.so.3 is not a symbolic link

        libgraphite2.so.3 -> libgraphite2.so.3.0.1
        libgdk_pixbuf-2.0.so.0 -> libgdk_pixbuf-2.0.so.0
        libgdk-x11-2.0.so.0 -> libgdk-x11-2.0.so.0
        libfribidi.so.0 -> libfribidi.so.0
        libfreetype.so.6 -> libfreetype.so.6
        libfontconfig.so.1 -> libfontconfig.so.1
        libdrm.so.2 -> libdrm.so.2

**Comment by lialin86** [comment]
if it defaults to read /usr/lib64/libnvcuvid.so.418.87.00, how to avoid this?

**Comment by Snawoot** [comment]
Thanks!

> if it defaults to read /usr/lib64/libnvcuvid.so.418.87.00, how to avoid this?

Usually LD_LIBRARY_PATH or ld.so.conf modification is sufficient. I'm not sure what is going wrong in your case. I'm pretty sure there no hardcoded or absolute paths to libraries. Looks like libraries from `/usr/local/cuda-10.0/lib64` take precedence.

`ldconfig -v` looks good as far as `/patched-lib` contains patched libnvcuvid as well. Please try to move `/home/videoanalyze/nvidia_lib` into beginning of path list specified in `LD_LIBRARY_PATH`.

If it will not work you'll have to follow any of these options:
* Debug your app with GDB. Set breakpoint on `NvEncOpenEncodeSessionEx` invocation and check which libraries are actually loaded (`info sharedlibrary` or `i proc map` command)
* Try to build `ffmpeg` on that server and test multiple encoding streams with it.
* Try to resolve issues with patching system libraries and apply patch system-wide. You may find processes holding files with `fuser` command

**Comment by lialin86** [comment]
"Please try to move /home/videoanalyze/nvidia_lib into beginning of path list specified in LD_LIBRARY_PATH."
What is beginning of path list  in LD_LIBRARY_PATH

do you mean /usr/local/cuda-10.0/lib64/?

LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64/:/home/videoanalyze/alg_plugin/mix_plugin/:/home/videoanalyze/alg_plugin/video_stream/:/home/videoanalyze/nvidia_lib:/home/videoanalyze/third_party:/home/videoanalyze/ext_lib:/home/videoanalyze:/usr/local/nvidia/lib:/usr/local/nvidia/lib64

**Comment by lialin86** [comment]
Debug your app with GDB. Set breakpoint on NvEncOpenEncodeSessionEx invocation and check which libraries are actually loaded (info sharedlibrary or i proc map command)

info sharedlibrary:
0x00007fffe9f41310  0x00007fffea028528  Yes (*)     /home/videoanalyze/nvidia_lib/libnvcuvid.so.1

**Comment by Snawoot** [comment]
Good, thanks! Let's try to build ffmpeg and encode 3+ streams simultaneously to check it.

**Comment by Snawoot** [comment]
> do you mean /usr/local/cuda-10.0/lib64/?

I mean move /home/videoanalyze/nvidia_lib into beginning of path list specified in LD_LIBRARY_PATH, so `/home/videoanalyze/nvidia_lib` comes first.

**Comment by lialin86** [comment]
“Try to build ffmpeg on that server and test multiple encoding streams with it.“

I build ffmpeg on this server, it can run three encode streams by h264_nvenc

then I recompile my project with these ffmpeg libs, there is still two encode limit.

**Comment by Snawoot** [comment]
Then I'd say what you call encode limit is unrelated to real session limit. All limiting happens on NvEncOpenEncodeSessionEx invocation.
