### ISSUE TITLE
New driver support (version 451.48)

### ISSUE THREAD

**Issue by Shidapu** [keylase/nvidia-patch#280]
**Please provide details about your environment (please complete the following information)**
- GPU Model: [e.g. GTX 1080]
- OS: [e.g. Windows 10 Enterprise Build: 2004]
- [x] I'm willing to participate in testing of new patch version

Please add support for latest Windows driver 451,48, added Directx 12 Ultimate support for latest Windows 10 build.

**Comment by Snawoot** [comment]
Merged via #281 and #282
