### ISSUE TITLE
New driver support (version 451.52)

### ISSUE THREAD

**Issue by coggy9** [keylase/nvidia-patch#287]
- Nvidia driver version: 451.52
- GPU Model: RTX 20160 SUPER
- OS: Windows 10 Pro build 19042.330
- [x] I'm willing to participate in testing of new patch version

Appears to only be available through Windows Update at the moment. [Extracted setup from WU download](https://mega.nz/file/VjxTDDYT#qag_O5NyOiPEdOYnsXPzj0YBQ8ZLczEfgwcJz_Au7f8)

**Comment by Snawoot** [comment]
Resolved via #288
