### ISSUE TITLE
Filtering of supported version

### ISSUE THREAD

**Issue by saltydk** [keylase/nvidia-patch#300]
Greetings!

Would just like to ask if it would be possible to implement a filter for the -l flag that outputs all the supported versions. Want to grab the newest driver supported by your wonderful patch using Ansible but obviously it is not immediately apparent which versions are referring to CUDA/Tesla/GeForce.

**Comment by Snawoot** [comment]
Hi! Such flag already exists.

**Comment by Snawoot** [comment]
P.S Also take a look to https://github.com/keylase/nvidia-patch/tree/master/tools/nv-driver-locator

**Comment by saltydk** [comment]
I knew that the -l flag existed just wanted a filtering option on it. But I'll have a look at your link, thanks!

**Comment by Snawoot** [comment]
For Linux we distiguish drivers only with its version. If you like to pick latest regular Nvidia you need to lookup `drivers.json` and pick highest version which has non-empty `driver_url` and this URL doesn't contain work `tesla`. Versions compared like this:

```python3
sorted(versions, key=lambda ver: tuple(map(int, ver.split('.'))))
```

**Comment by saltydk** [comment]
```                {
                    "version": "450.51.05",
                    "nvenc_patch": true,
                    "nvfbc_patch": true,
                    "driver_url": "https://international.download.nvidia.com/tesla/450.51.05/NVIDIA-Linux-x86_64-450.51.05.run"
                }``` would suggest that isn't always true, or did I misunderstand what you just said.

**Comment by saltydk** [comment]
ah, missed the part about checking for tesla. My bad.
