### ISSUE TITLE
New driver support (version 452.06)

### ISSUE THREAD

**Issue by aterriblegamer** [keylase/nvidia-patch#305]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 452.06
- GPU Model: 2080 TI RTX
- OS: Windows 10
- I'm willing to participate in testing of new patch version

**Comment by Jaybonaut** [comment]
Oh good, someone asked about this.  I'll just check back every day to see if there is an update.  I think this driver is roughly a couple weeks old now.

**Comment by aterriblegamer** [comment]
Yes and it was a required patch for Flight Simulator 2020 :)

**Comment by Jaybonaut** [comment]
Did something change that prevents the regular updates we normally see?

**Comment by NoXPhasma** [comment]
Nothing has changed to the patch needed for `450.66` on Linux, you can just copy the `450.57` lines and replace the version with `450.66`. It works fine. No idea why this simple change hasn't been done yet.

**Comment by Jaybonaut** [comment]
Yeah that's an older driver and I am on Windows

**Comment by amnesia0287** [comment]
Now even these ones are old cause 30xx cards and floods of new drivers weeeeee
