### ISSUE TITLE
Question: ... ? GTX1660 video encoding

### ISSUE THREAD

**Issue by johnvick** [keylase/nvidia-patch#307]
Hello,

My question is: ...I use this card to encode TV rips using Staxrip and NVENC. Will using your patch increase fps any? I get 120 fps on 1080 encoding to 10 bit HEVC using high quality settings.

**Comment by Saentist** [comment]
No it allows to use more then 2 calculation's in same time.
With 120fps you can RIP and transcode in real-time.
