### ISSUE TITLE
Question: Is it possible to unlock Turing's multiple NVDECs?

### ISSUE THREAD

**Issue by santomet** [keylase/nvidia-patch#310]
Hello,

If I understand it correctly, some Turing chips have multiple NVDECs [as seen in this presentation.](https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9331-nvidia-gpu-video-technologies-overview-applications-and-optimization-techniques.pdf)

Do you know, is it possible to unlock these capabilities on TU104 and TU106 GeForces?

**Comment by amnesia0287** [comment]
It doesn't include GeForce cards, only Quadro and Tesla, consumer cards only get 1 and that has been the case for a few years now.

![image](https://user-images.githubusercontent.com/1837355/93544494-13329b80-f913-11ea-861e-348f26cd99b4.png)

**Comment by santomet** [comment]
Sorry for reopening, I did not have time to respond. I can read the official statements as well. But playing with GPUs in our company just keeps me wondering: aren't NVENC and NVDEC de facto physical parts of these chips?

I have noticed a small hint when benchmarking RTX 2060 SUPER (TU106) performance and GTX 1080 Ti (GP102) and checking stats in nvidia-smi:
While decUtil on 1080 shows 100% load
![1080](https://user-images.githubusercontent.com/13346000/94118264-968d4900-fe4d-11ea-863a-e20e6849798d.png)

decUtil on 2060 shows only 33% which would correspond with three NVDEC units TU106 might have
![2060](https://user-images.githubusercontent.com/13346000/94118383-c50b2400-fe4d-11ea-8b5c-2682585898dd.png)

However, I tried it with RTX 2080 Ti (TU102, which should have only 1 NVDEC anyway) and decUtil also maxes up to 33%. And with Quadro RTX 4000 (TU104, should have 2NVDECs) i could get up to 66% of decUtil.

That would suggest that "Turings have up to 3 NVDECs, always show decUtil based on that" is somehow hardcoded in nvidia-smi stats regardless of actual capabilities of one particular card. But also (of course much less likely) that these chips have all 3 NVDECs and some of them are just disabled (either in firmware or drivers). 

This is why I am asking, ideally someone who has been throughout the drivers - is the latter somehow possible? Can I find technical details somewhere? Thanks again

**Comment by 1988fido** [comment]
in Nvidia official matrix
TU106 Quadro  like RTX 3000 it supports 3 at the same time "NVDEC "
so in theory there could be a way like how Nvenc was done to make the cards do 3 NVDEC if they are TU106
its weird how a higher Teir chips like Tu104,Tu102 can do lower number
https://developer.nvidia.com/video-encode-decode-gpu-support-matrix

**Comment by Snawoot** [comment]
Nobody seem to be inclined doing this. Sorry, looks like it's not going to happen.
