### ISSUE TITLE
New driver support (version 456.38)

### ISSUE THREAD

**Issue by reloxx13** [keylase/nvidia-patch#311]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 456.38
- GPU Model: 1060
- OS: Win10x64
- [x] I'm willing to participate in testing of new patch version

Patch self-generated: 
[nvidia_patch_win10x64_456_38.zip](https://github.com/keylase/nvidia-patch/files/5244081/nvidia_patch_win10x64_456_38.zip)

**Comment by Jaybonaut** [comment]
Yes I guess we can skip the previous two requests due to this newer one

**Comment by Killgannon117** [comment]
Has anyone successfully tested the above patch? I'd be willing to but I'm new here and don't know the worst case scenario. If it's easily reversible I'm all for it. Any insight would be amazing, thank you!

**Comment by morpheus2n2** [comment]
Yeah worked fine for me
