### ISSUE TITLE
Can you help me how to use docker

### ISSUE THREAD

**Issue by 17702513221** [keylase/nvidia-patch#315]
my docker :docker run --name ubuntu18  -it --runtime=nvidia kunyoung92/cuda:10-7-devel18.04 /bin/bash
git clone https://github.com/keylase/
cd nvidia-patch 
 bash docker-entrypoint.sh 
Detected nvidia driver version: 440.100
ERROR: cannot detect driver directory
/home

**Comment by Snawoot** [comment]
docker-entrypoint is not intended to be run by hand. See [instruction](https://github.com/keylase/nvidia-patch#docker-support) on main page. Also you may find historical reference on subject at issue which introduced docker support: #131

**Comment by Joeharrison94** [comment]
> docker-entrypoint is not intended to be run by hand. See [instruction](https://github.com/keylase/nvidia-patch#docker-support) on main page. Also you may find historical reference on subject at issue which introduced docker support: #131

How would you implement this when you use Docker Compose?

**Comment by nerijus** [comment]
It is really a docker, not nvidia-patch question.
