### ISSUE TITLE
Windows Patch Notice 

### ISSUE THREAD

**Issue by ggnull35** [keylase/nvidia-patch#317]
If you use Windows Patch tool with the corresponding diff files for the driver version and always getting error, even you select the correct files, please note:

On Windows 10 (I do not know when and how it gets started), but Windows Patch tool is looking for the exact dll name in case sensitivity. So;

You need to edit diff file and match the dll file name as it is. Example:

if filename is C:\WINDOWS\system32\nvEncodeAPI64.dll than edit diff file to match case sensitivity.

**Comment by Snawoot** [comment]
I think it's a good case to open issue in repo of patch utility project: https://github.com/Deltafox79/Win_1337_Apply_Patch/
