### ISSUE TITLE
New driver support (version 391.35)

### ISSUE THREAD

**Issue by IamGimli** [keylase/nvidia-patch#324]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 391.35
- GPU Model: GTX 1080 Ti
- OS: Windows Server 2016 (using Windows 10 64-bit driver)
- [x] I'm willing to participate in testing of new patch version

The reason I'm requesting this is because that's the lastest driver version I have found that can be installed on Windows Server 2016 and supports the 1080 Ti. Generally only Quadro drivers are compatible with Windows Server 2016 because it's stuck on WDDM 2.1 but this older Geforce driver can be installed and is compatible. I run Windows Server 2016 as a home server and have Emby and Plex installed on it, I would like to be able to use my 1080 Ti to perform hardware transcoding for more than two streams.

**Comment by Snawoot** [comment]
Hi! What is your Windows Server build number? You can check it with `winver` command.

**Comment by IamGimli** [comment]
It's 14393. It cannot be updated past that because later builds only apply to Server Core versions, not the version with a GUI.

**Comment by Snawoot** [comment]
I've merged patch for 391.35 into master. However, this driver version itself supports only NVENC API version 8.1 and it might be insufficient for modern ffmpeg or Plex.

**Comment by IamGimli** [comment]
Awesome thank you very much! Thanks for the heads up too, I'll try and confirm whether it works well or not.

**Comment by IamGimli** [comment]
So I can confirm that the hardware encoding works with Plex, although not all the time. It works fine if I stream from a media box but not from a browser window, which I assume is a Plex issue and not one with the drivers/encoder. 

Works well in Emby too. Haven't been able to confirm that I can encode more than two streams at a time yet but since encoding in general works I'll assume it works.

Thanks again!
