### ISSUE TITLE
Question: Plex Docker Container and GPU Passthrough

### ISSUE THREAD

**Issue by Joeharrison94** [keylase/nvidia-patch#328]
I am currently using a Windows VM which runs Plex on my ESXi host, this uses modified nvidia drivers to unlock the transcoding limits on my GTX 1050, working like a dream, however I want to retire the VM and move it into my other VM (Ubuntu Server 20.04.1).

Here is the plan:

I want to use GPU passthrough to the Ubuntu Server 20.04.1 VM as I do for Windows, I then plan to install the patched drivers from here which will unlock the gpu transcoding limits again. Here is the big question will these unrestricted drivers still take effect in the Plex container or will it revert to using the stock nvidia drivers with the restriction of 3 transcodes still in place?

Thank you in advance.

Here is the yml I plan to use;

````
# Plex - Media Server
  plexms:
    image: plexinc/pms-docker:public
    container_name: plexms
    restart: unless-stopped
    networks:
      - proxy_net
    devices:
      - /dev/dri:/dev/dri # for harware transcoding
    security_opt:
      - no-new-privileges:true
    ports:
      - "$PLEX_PORT:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp" # conflicts with xTeVe
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "$PLEX_WEB_TOOLS_PORT:33400"
    volumes:
      - $DOCKERDIR/plexms:/config
      - $USERDIR/Downloads:/Downloads
      - /media:/nas
      - /dev/shm:/transcode # Offload transcoding to RAM
    #   - $USERDIR/Downloads/plex_tmp:/transcode
    environment:
      TZ: $TZ
      HOSTNAME: "nucPlex"
      PLEX_CLAIM_FILE: /run/secrets/plex_claim
      PLEX_UID: $PUID
      PLEX_GID: $PGID
      ADVERTISE_IP: http://$SERVER_IP:$PLEX_PORT/
    secrets:
      - plex_claim
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.plexms-rtr.entrypoints=https"
      - "traefik.http.routers.plexms-rtr.rule=Host(`nucplex.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.plexms-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.plexms-rtr.service=plexms-svc"
      - "traefik.http.services.plexms-svc.loadbalancer.server.port=32400"

**Comment by nerijus** [comment]
Please see https://github.com/keylase/nvidia-patch/issues/251

**Comment by Joeharrison94** [comment]
> Please see #251

Im not sure this covers the use in docker, I know I can get it working in the ubuntu vm I just want to know if it will work in the docker containers on that vm without having to change anything if i map /dev/dri to the container

**Comment by nerijus** [comment]
Please see https://github.com/keylase/nvidia-patch/issues/315

**Comment by Snawoot** [comment]
Hi! nvidia-docker runtime mounts drivers from host system, so if you patched them it applies to docker container as well. AFAIK this method is often used by people for Plex docker containers on Unraid.

If for some reason you can't apply patch on your host system, use LD override method for Docker described on main page (README.md).
