### ISSUE TITLE
New driver support (version 457.09)

### ISSUE THREAD

**Issue by reloxx13** [keylase/nvidia-patch#337]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 457.09
- GPU Model: 1060
- OS: win10x64
- [x] I'm willing to participate in testing of new patch version

selfmade:
[patch_win10_geforce_457_09.zip](https://github.com/keylase/nvidia-patch/files/5468837/patch_win10_geforce_457_09.zip)

**Comment by Snawoot** [comment]
This one was already added 2 days ago via PR #335.

**Comment by reloxx13** [comment]
ahh damn, i just checke closed issues for this version :p
