### ISSUE TITLE
Question: Has anyone tested RTX 30 series?

### ISSUE THREAD

**Issue by MartLeib** [keylase/nvidia-patch#339]
Hi!

I'm wondering, has anyone tested RTX 30 series with this patch already? At the moment I use RTX 2060 SUPER in the streaming server which can transcode 11 "streams" which all of them have 1080p50, 720p50, 480p50, 360p50 feeds (44 streams in total).

Now I'm wondering, will RTX 3070, for example, increase the number of streams I could transcode? It seems to have the same generation of NVENC chip as 2060 SUPER, do any other specs of the 3070 make it more powerful for NVENC encoding than 2060?

**Comment by Siyabent** [comment]
Hello, 

I just tried this with my new Asus Geforce RTX 3090 TUF-RTX3090-O24G card. 

The limit bypass works as expected. 

I tried encoding 17 1080p streams with 3500-4000 bitrate.

These are the stats i got:

5982MB/24265MB - 16%

Hope this helps!

**Comment by MartLeib** [comment]
> Hello,
> 
> I just tried this with my new Asus Geforce RTX 3090 TUF-RTX3090-O24G card.
> 
> The limit bypass works as expected.
> 
> I tried encoding 17 1080p streams with 3500-4000 bitrate.
> 
> These are the stats i got:
> 
> 5982MB/24265MB - 16%
> 
> Hope this helps!

Thanks! Was the 17 streams the limit (stability issues etc) or dis you just did not test more?

**Comment by Siyabent** [comment]
Definitely not the limit. I had over 20 streams running super stable but took a screenshot of the statistics when i had 17 streams running!

**Comment by MartLeib** [comment]
> Definitely not the limit. I had over 20 streams running super stable but took a screenshot of the statistics when i had 17 streams running!

Thank you very much!

**Comment by ExDominatus** [comment]
@Siyabent Just wondering if you've tried to push it the max and what # of streams you could get? Does it scale linearly with the vram numbers you presented?

> 5982MB/24265MB - 16% - 17 streams

@MartLeib Apologies for bumping this issue, but did you ever get your hands on a RTX 3070? or any of the other GPUs. Is there a significant improvement over the 1060/2060. Need to decide on a card to chuck into my server and if the 3070 can do way more, that might just push me over the edge to get one.
