### ISSUE TITLE
Is it possible to get a video walkthrough for Docker patch?

### ISSUE THREAD

**Issue by arich1055077** [keylase/nvidia-patch#341]
Hello,

My question is: ...

I was wondering if it is possible to get a video walkthrough on how to implement this patch in dockers. Specifically, on unraid with a plex docker. I was using this patch for windows, but recently decided to switch to a docker for plex. However, I am brand new to anything with dockers and trying to understand how to actually implement the steps previously mentioned has proven unsuccessful for a noob such as myself. I'm hoping its possible for someone to make a video showing how to do it, like there is for the windows version. 

If this is not possible, is it possible to get step by step instructions on how to get this working on a linuxserver.io plex docker running on unraid. (I already have the nvidia unraid pluggin and have downloaded and installed the nvidia unraid version 6.8.3).

Thank you for the help, and I'm sorry because I know this kind of question has been asked before but I wasn't able to figure it out after about an hour and a half of searching online and in previous questions.

Thanks in advance,

Austin

**Comment by Snawoot** [comment]
Hi!

Take a look at https://www.reddit.com/r/unRAID/comments/dm2phn/unraid_680rc1_wnvidia_remove_2_stream_limit/f4wedux/

Reddit also has a lot of topics regarding this patch, so just search "keylase"

**Comment by MRobi1** [comment]
A video would be great, or even a step by step procedure to follow.

I've got a proxmox server with the driver installed and patched. GPU is passed through to an lxc container, and then docker running in the lxc container. I then have Emby, Plex and Unmanic taking advantage of the GPU, but even with the patch applied to the proxmox host, I'm limited to 3 streams in the docker container.

Looking at the dockerfile, I've got no clue what to do with it. The link above doesn't even mention docker.

**Comment by Snawoot** [comment]
Yep, in Docker case you basically need to just patch host and you are done.

However there are some [cases](https://github.com/keylase/nvidia-patch/issues/131) when you can't patch docker host because you don't own it or something like this. For that reason [this paragraph exists](https://github.com/keylase/nvidia-patch#docker-support).
