### ISSUE TITLE
offset wrong

### ISSUE THREAD

**Issue by BenRulez** [keylase/nvidia-patch#347]
Tried patching my GTX 750ti drivers, get offset error

Offset [2F3BA] Wrong...
set 0xCC -> I expected 0X8B

Driver 457.30

**Comment by Snawoot** [comment]
Hi!

Please check following:

* You are using correct patch version for your drivers version.
* You are using appropriate .1337 file for .dll file.
* You have checkbox "Fix offset" set.

If nothing helps, please attach .dll file you're trying to patch and .1337 file you're using for it.

**Comment by BenRulez** [comment]
Heres the files, i used the 1337 for 457.30
[Patch Files BenRulez.zip](https://github.com/keylase/nvidia-patch/files/5599105/Patch.Files.BenRulez.zip)

**Comment by Snawoot** [comment]
This .dll file definitely doesn't belongs to 457.30. Looks more like 431.XX series.

Check your driver version with nvidia-smi command:

https://stackoverflow.com/questions/57100015/how-do-i-run-nvidia-smi-on-windows
https://www.youtube.com/watch?v=yCMFygZ5SBA&feature=youtu.be

If there are some artifacts of older driver, try to remove it with Display Driver Uninstaller tool.
