### ISSUE TITLE
New driver support (version 465.21)

### ISSUE THREAD

**Issue by natephysics** [keylase/nvidia-patch#354]
Really love the project. I know this might be a difficult ask but I'd be very grateful if you'd consider it. I really need support for multiple NVENC streams with a developmental driver version. I'm happy to beta test the patch. I'm in a situation where I really need support for Tensorflow GPU through the WSL 2 virtual machine and to utilize that feature I need the 465.21 Nvidia driver. The driver is available through the developer site for Nvidia: https://developer.nvidia.com/cuda/wsl/download

Right now I have to choose between Tensorflow GPU WSL 2 support and multiple NVENC streams.  If you'd be willing to patch this driver version it would save me a lot of headaches. If there's something I can do to help out, please don't hesitate to message me. 

- Nvidia driver version: 465.21
- GPU Model: GTX 1080TI
- OS: Windows 10 Build 20279.1
- [x] I'm willing to participate in testing of new patch version

**Comment by Snawoot** [comment]
Usually it's pretty easy to introduce support for new Windows driver version with an automation script we have: https://github.com/keylase/nvidia-patch/tree/master/win/tools/autopatch

Problem is: it doesn't work for 465.21. It seems pattern has changed, and probably at some point all future versions will be affected as well. In addition, I don't have GPU right now to debug this and update pattern.

All in all, it is possible to have support for WSL driver when someone will hold debug session on newest driver series and automation pattern will be updated.

**Comment by natephysics** [comment]
Understandable. If there is some way I can help I'm happy to.

**Comment by Snawoot** [comment]
@natephysics How can I contact you directly? My contacts are available on [my profile page](https://github.com/Snawoot/).

**Comment by didyouexpectthat** [comment]
Hi @Snawoot, I can contact you on Telegram. I have 2080 Ti and Windows and can install 465.21.
