### ISSUE TITLE
New driver support (version 460.27.04)

### ISSUE THREAD

**Issue by vercas** [keylase/nvidia-patch#357]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 460.27.04
- GPU Model: GTX 1070, GTX 1050Ti, GTX 960
- OS: Ubuntu 20.04
- [x] I'm willing to participate in testing of new patch version

**Comment by Aluminite** [comment]
To add to this, I tried adding the new version number to the patch.sh file but it didn't make any difference for me. So some further work is probably needed to make the patch work.

**Comment by jcostom** [comment]
Suggest focusing instead on 460.32.03, as it includes the recent security fixes Nvidia released. That's the current 460 release available from Ubuntu repos as of just now when I updated. Announcement details: https://nvidia.custhelp.com/app/answers/detail/a_id/5142/~/security-bulletin%3A-nvidia-gpu-display-driver---january-2021

**Comment by Snawoot** [comment]
Can anyone provide shell access to a Linux box with Nvidia GTX/RTX GPU and 460.32.03 driver? I do not have HW at this moment.

**Comment by Snawoot** [comment]
460.27.04 and 460.32.03 have same sha256 sum of libnvidia-encode.so, so I guess we can handle them both at once:

```
b4dfb3e0bb701702944fe65fa241986e8e3ba6d103b73264ec32f4bc166c092c  NVIDIA-Linux-x86_64-460.27.04/libnvidia-encode.so.460.27.04
b4dfb3e0bb701702944fe65fa241986e8e3ba6d103b73264ec32f4bc166c092c  NVIDIA-Linux-x86_64-460.32.03/libnvidia-encode.so.460.32.03
```

**Comment by vercas** [comment]
Sadly I cannot provide shell access to my server, but I can help with testing. I've got many terabytes of video to transcode.

**Comment by Snawoot** [comment]
KVM virtual machine with [GPU PCI passthrough](https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF) will work as well.

**Comment by Snawoot** [comment]
Resolved via #364. Thanks to @vercas for provided lab!

**Comment by jackz314** [comment]
What about NvFBC support? Is there a separate process for it?

**Comment by Snawoot** [comment]
@jackz314 

Can't test it right now, but it'll be nice if you can test it. Check out this branch: https://github.com/Snawoot/nvidia-patch/tree/nvfbc_test

**Comment by jackz314** [comment]
I just tried it out, and it doesn't seem to work, when I use NvFBC features it says "This hardware does not support NvFBC".

My driver version: 460.32.03
OS: Ubuntu 20.10

**Comment by Snawoot** [comment]
@jackz314 opened new issue for this: #365 

Hope we'll factor this out soon.

**Comment by jackz314** [comment]
Thanks, you can update the issue with the GPU model, I updated it in my comment, although I'm not sure if that's relevant here.
