### ISSUE TITLE
nvfbcwrp: registry entry to allow NvFBC use

### ISSUE THREAD

**Issue by Snoop05** [keylase/nvidia-patch#359]
For software like Steam to be able to use NvFBC it is required to also set
`DWORD` value `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\nvlddmkm\NVFBCEnable` to `1`
(needs reboot / driver restart)

Would be good to mention it in nvfbcwrp readme

**Comment by Snawoot** [comment]
I don't know what this registry does. Is it same as https://github.com/vparitskiy/enable-disable-NVFBC ?

Can you please edit that README file and submit pull request?

**Comment by Snoop05** [comment]
Yes, that tool also sets the value, but i think having it at least a bit documented is better than running some random executable that doesn't come with source.

**Comment by Snawoot** [comment]
Right, I didn't mean it's better anyhow, I just was curious to understand if it is the same thing or not.

**Comment by Snawoot** [comment]
Fixed via #360
