### ISSUE TITLE
New driver support (NvFBC component) (version 460.32.03)

### ISSUE THREAD

**Issue by Snawoot** [keylase/nvidia-patch#365]
- Nvidia driver version: 460.32.03
- GPU Model: GTX 1080
- OS: Ubuntu 20.10
- [ ] I'm willing to participate in testing of new patch version

From https://github.com/keylase/nvidia-patch/issues/357#issuecomment-757397929 (@jackz314)

**Comment by Snawoot** [comment]
Branch with current NvFBC patch candidate: https://github.com/Snawoot/nvidia-patch/tree/nvfbc_test

**Comment by ValZapod** [comment]
Did you see https://github.com/trevor403/get-priv-data-gfe, BTW? Any comments?

**Comment by Snawoot** [comment]
@ValZapod 

Never seen before, but I think our [nvfbcwrp](https://github.com/keylase/nvidia-patch/tree/master/win/nvfbcwrp) already provides similar function, allowing to dump magic from existing installation (and even replay it for any app). See [Advanced Usage](https://github.com/keylase/nvidia-patch/tree/master/win/nvfbcwrp#advanced-usage) section of it's README file for more details.

Brief comparison of these two solutions:

* nvfbcwrp is little bit older, it was presented 16 months ago. get-priv-data-gfe is 7 months old.
* get-priv-data-gfe relies on specific sequence of instructions in particular .dll file of GFE. nvfbcwrp traps dll calls like dll proxy and relies only on stable FBC API interface which it mocks. It allows to record magic UUID from any app.

Summarizing the above, get-priv-data-gfe doesn't contain techniques that we should consider adopting. However, their disclaimer about DMCA is quite interesting and useful.
