### ISSUE TITLE
Question: MMIO patch for 32bit

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [keylase/nvidia-patch#366]
Hello,

i see that you are doing patched for the 32bit version of nvidia drivers...
i wanted to know about the possibility of patching the MMIO issue that cause the driver to not work on "windows sever 2008" (32bit) or... "windows 7 32bit with PAE >64gb patch"

i'm a (low level programmer myself) and i would love to even help generating such if possible, altough i didnt worked on a video driver before, but i can learn tons, specially for such noble goal :)

**Comment by Snawoot** [comment]
Hello!

Here is some background on this subject.

We cover only x86_64 drivers. 64-bit drivers for Windows contain 32-bit libraries for compatibility with legacy apps, so we cover that too. This way apps like Plex-ffmpeg work too.

As far as I know Nvidia discontinued releases of driver packages for 32-bit x86 systems two years ago. Last driver version for x32 Windows 7 version was [391.35](https://www.nvidia.com/Download/driverResults.aspx/132839/en-us).

From my point of view 32-bit platform is just outdated and I'm not inclined to put efforts to expand on it or to provide ongoing support for anything on it.

Answering to your initial question, I'm not expecting something like that to be done. There are few reasons for that:

* It's a little bit out of scope for this project.
* x32 is a legacy with no audience need for it.

I'm not proficient in the subject of your problem, however, if you need some directions I'll try to answer questions I can answer.
