### ISSUE TITLE
Question: nvidia deb/rpm repo ?

### ISSUE THREAD

**Issue by Saentist** [keylase/nvidia-patch#367]
Hello,

Some side question
https://us.download.nvidia.com/tesla/450.80.02/nvidia-driver-local-repo-ubuntu1804-450.80.02_1.0-1_amd64.deb
https://us.download.nvidia.com/tesla/450.80.02/nvidia-driver-local-repo-rhel7-450.80.02-1.0-1.x86_64.rpm
https://us.download.nvidia.com/tesla/450.80.02/nvidia-driver-local-repo-rhel8-450.80.02-1.0-1.x86_64.rpm
is someone use/patch/repack thouse DEB/RPM files?

**Comment by Snawoot** [comment]
Hello,

I think it's not OK to distribute modified binaries due to legal reasons. Even if someone does repacking, I'd like to not have links anywhere near this repo.
