### ISSUE TITLE
461.40 - failed to patch nvencodeapi.1337

### ISSUE THREAD

**Issue by didyouexpectthat** [keylase/nvidia-patch#375]
Windows 10 x64
Upgraded to 461.40.
nvencodeapi64.1337 patched successfully.
nvencodeapi.1337 failed to patch.
![image](https://user-images.githubusercontent.com/1329077/106030630-37ea0d00-6083-11eb-8ca7-566dc17dfcca.png)
Tried reinstalling the original driver and repatching and also rebooting the system but both produce a failed to patch message.

**Comment by Snawoot** [comment]
Usually if .1337 file doesn't match to patched file it shows other error with expected bytes which differ.

I suspect it's some generic error with file access. Please check that patched file is not held by some running application (e.g. stop everything what may use it and retry).
