### ISSUE TITLE
Question: 4k 4:4:4 NVENC Limit ?

### ISSUE THREAD

**Issue by wronglebowsk** [keylase/nvidia-patch#383]
Hello,

My question is: Hello, I was recently testing a GTX 1650 with the NVENC patch applied. 1080p and 4k SDR content worked correctly, but 4k HDR content seemed limited to two streams. I have a 4GB card so there was VRAM left to utilize. Streams after 3 still appeared when running "nvidia-smi" but had reduced usage and there was a heavy load on the CPU. Is there perhaps another limit for 4k 4:4:4 content this patch doesn't cover?

![image](https://user-images.githubusercontent.com/25129624/109215645-73aaec00-7781-11eb-83fc-b73715dc0a48.png)

**Comment by Snawoot** [comment]
Hi!

Not sure if it's anyhow related to this patch and software restrictions imposed by driver. Check this chart: https://www.elpamsoft.com/?p=Plex-Hardware-Transcoding

It indicates 3 streams for GTX 1650. Can't say for sure why.

**Comment by ValZapod** [comment]
> 4k HDR content seemed limited to two streams

What it has to do with YCbCr 4:4:4? HDR is just PQ or HLG transfer. HDR HEVC file can be even 8 bit or there is a possibility to have BT.2020 colorspace in SDR, BT.2020 is SDR only, BTW. HDR was defined in BT.2100.

**Comment by wronglebowsk** [comment]
> > 4k HDR content seemed limited to two streams
> 
> What it has to do with YCbCr 4:4:4? HDR is just PQ or HLG transfer. HDR HEVC file can be even 8 bit or there is a possibility to have BT.2020 colorspace in SDR, BT.2020 is SDR only, BTW. HDR was defined in BT.2100.

Nvidia's NVENC Matrix documents list these features out for support differently. 8k HEVC and 4:4:4 HEVC are much newer in their support and only work on newer GPUs. I'm curious if using these encoding functions are limited in different ways than the older ones, making this patch not applicable to them. I've recently acquired a RTX 3080 which I will try and test on.

**Comment by ValZapod** [comment]
> recently acquired a RTX 3080

I have a 2080 Ti, it has tje same HEVC engine with 4:4:4 stuff. The only dufference is AV1. So I can test it too if you want.

**Comment by wronglebowsk** [comment]
I can confirm this is just a weird VRAM limit with the 1650 4GB. Testing with a 1080 Ti and 3080 I had no issues going far past 2 streams. I suspect the card is reserving some amount of VRAM for other use cases which causes this to be limited to 2 streams despite having enough VRAM for the third.
