### ISSUE TITLE
Nvidia GEFORCE GAME READY Driver 461.92 doesn't work with patch

### ISSUE THREAD

**Issue by Anuruddha094** [keylase/nvidia-patch#388]
Hi I have installed Nvidia Geforce Game Ready Driver 461.92 for my MSI Geforce GTX Armor 1660 OC and installed the relavent x64 patch. I'm running my Plex server on Windows 10 Pro with latest updates. But unfortunately I can't get more than 3 hardware transcode streams. Forth stream is doing software transcoding. It worked perfectly until 461.72 patch.

Please help me.

Thank you

**Comment by Snawoot** [comment]
Looks like autopatch script is picking up wrong sequence. Unfortunately, I don't have any working nvidia GPU to test and debug it.

**Comment by Anuruddha094** [comment]
@Snawoot Thank you very much for your reply. I have completely uninstalled and reinstalled Nvidia drives. But still No luck. I guess your explanation is correct. Shall I install the previous 461.72 drives until this issue sorted.  

cheers

**Comment by Snawoot** [comment]
>Shall I install the previous 461.72 drives until this issue sorted.

Yes, I think it is the only option for now.

**Comment by Snawoot** [comment]
For everyone else: we need to confirm that issue. Can someone also please try patches with 461.72 driver?

**Comment by Anuruddha094** [comment]
@Snawoot Hi I downgraded my Nvidia drivers for 461.72 version. But still I couldn't get more than 3 hardware transcoding in Plex. Previously it worked with 461.72 but It wasn't anymore. Yesterday I installed a latest update for windows 10 pro 20H2 build KB5001567 

My current server specs as follows:
Plex server: plex 1.22.1.4200-c073686f2
Windows 10 Pro 20H2: 19042.868

I can't understand what cause this issue. I highly doubt 461.92 patch has as a issue because now 461.72 works same way as 461.92.

please I need your advice.

Thank you.

**Comment by Snawoot** [comment]
@Anuruddha094 that may mean Windows ships it's own version of Nvidia driver. Try using some tool like [Display Driver Uninstaller](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html). It may clean up existing drivers and if I remember correctly allows to prevent Windows install it's version of driver in future.

**Comment by Anuruddha094** [comment]
@Snawoot I will try to install that tool. Today what I did is, I completely uninstalled and reinstall drivers with Nvidia installer with fresh installation option. I think there isn't any windows drivers installed on Nvidia card. Please have a look my photos.

thank you.
![plex-hw-transcoding-nividia-issue-01](https://user-images.githubusercontent.com/31022230/111496538-4de98500-8738-11eb-9fc0-74638cf7dd47.png)
![plex-hw-transcoding-nividia-issue-02](https://user-images.githubusercontent.com/31022230/111496539-4e821b80-8738-11eb-8fa8-e93e8b53aa16.png)
![plex-hw-transcoding-nividia-issue-03](https://user-images.githubusercontent.com/31022230/111496540-4e821b80-8738-11eb-966b-7d1da3e7fbe0.png)
![plex-hw-transcoding-nividia-issue-04](https://user-images.githubusercontent.com/31022230/111496542-4f1ab200-8738-11eb-847d-97c03bba5ae7.png)

**Comment by Anuruddha094** [comment]
@Snawoot Thank you very much for the clarification. Do you think Plex server doesn't cause any problem in HW transcoding? or it just windows generic drivers conflict with Nvidia drivers cause this issue. It looks like Geforce 1660 has Nvidia drivers installed.

Shall I follow the instruction explained on that thread?

cheers

**Comment by Snawoot** [comment]
> Do you think Plex server doesn't cause any problem in HW transcoding? 

I can't know for sure. Anyway Plex support is out of scope for us.

> or it just windows generic drivers conflict with Nvidia drivers cause this issue.  It looks like Geforce 1660 has Nvidia drivers installed.

Not generic driver. Windows distributes Nvidia drivers via Windows Update channel as well. That may be the case.

**Comment by Anuruddha094** [comment]
@Snawoot I already started  thread in Plex too [https://forums.plex.tv/t/plex-hardware-transcoding-failed-with-nvidia-geforce-1660-with-geforce-game-ready-driver-461-72-patched-drivers/701218](url)

I used to do windows update while Nvidia patch drives installed and never had any issues until yesterday. I believe yester windows update KB5001567 did something to break Nvidia update process. I really wonder nobody still didn't report this issue but just me.

cheers

**Comment by Anuruddha094** [comment]
**Hi I'm back. I found the solution for the problem.** Actually Plex transcoder uses 32bit version of nvencodeapi.dll located in `C:\WINDOWS\SysWOW64\nvencodeapi.dll` but I patched only `C:\WINDOWS\system32\nvencodeapi64.dll` file. After I patched  `C:\WINDOWS\SysWOW64\nvencodeapi.dll`,  I can do more than 3 HW transcodes without any issues. Still I'm using **461.72** of Nvidia Game Ready drive.  I will try  Nvidia 461.92 drives tomorrow.

**But still I can't understand one thing. Previously I patched just only `C:\WINDOWS\system32\nvencodeapi64.dll` and Plex was able to do more than 3 HW transcodes without any problem.  Even after windows updates  or Nvidia driver updates. But its not working anymore. When plex was doing transcoding I checked windows task manager. Plex transcoder is 32bit and definitely it was using unpatched `nvencodeapi.dll` of Nvidia encoder and it worked for more than 3 HW transcodes without any issues.** 

If you can please explain this.

thank you.
