### ISSUE TITLE
performance degradation

### ISSUE THREAD

**Issue by Ivanezko** [keylase/nvidia-patch#39]
**Describe the bug**
Increasing the number of sessions leads to corresponding decrease of performance of each session.
For example, we have a video file to convert, and 1 session converts it in 10 seconds
2 sessions will convert 2 files in 10 seconds each - so in 10 seconds we have 2 result files
But if we use 4 sessions - we will have 4 result files in 20 seconds, not 10.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.1
 - GPU model:  GTX 1050ti
 - Patch commit used: ffd8f15fbd2eaea232350fe9f435517c8840c4c3
 - Nvidia driver version: 410.78

**Additional**

| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   50C    P0    N/A /  95W |    551MiB /  4039MiB |     19%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     14840      C   ffmpeg                                       152MiB |
|    0     14851      C   ffmpeg                                       152MiB |
|    0     14864      C   ffmpeg                                       127MiB |
|    0     14874      C   ffmpeg                                       108MiB |

**Comment by Snawoot** [comment]
Could you replace `h264_cuvid` with `h264_nvenc` in order to use same encoder for all outputs?

**Comment by Ivanezko** [comment]
h264_cuvid is a decoder, not encoder
Looks like you are right, no magic and nvenc chip is limited.
in my case 1 process takes 60% of nvenc according to "nvidia-smi dmon"
2 processes take 100% and FPS of each drops a lite
3 processes take 100% and FPS drops heavily
So using more then 2 processes is logical only for light tasks
`ffmpeg -decoders |grep 264
ffmpeg version N-92308-g32d021cfa6 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --enable-cuda --enable-cuvid --enable-nvenc --enable-nonfree --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64
  libavutil      56. 21.100 / 56. 21.100
  libavcodec     58. 34.100 / 58. 34.100
  libavformat    58. 19.102 / 58. 19.102
  libavdevice    58.  4.106 / 58.  4.106
  libavfilter     7. 38.100 /  7. 38.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
 VFS..D h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 decoder wrapper (codec h264)
 V..... h264_cuvid           Nvidia CUVID H264 decoder (codec h264)`

`ffmpeg -encoders |grep 264
ffmpeg version N-92308-g32d021cfa6 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --enable-cuda --enable-cuvid --enable-nvenc --enable-nonfree --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64
 ...
 V..... h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 encoder wrapper (codec h264)
 V..... nvenc                NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc_h264           NVIDIA NVENC H.264 encoder (codec h264)`

**Comment by Snawoot** [comment]
> h264_cuvid is a decoder, not encoder

Sorry, my bad

FFmpeg users [report](https://ffmpeg.org/pipermail/ffmpeg-user/2018-July/040609.html) 60 realtime SD channels with GTX 1070Ti. It's hard to say whether GTX 1050Ti has same NVENC chip or not.

**Comment by roderrooder** [comment]
Just to chime in,

while the GTX 1070Ti has 2 NVENC chips only one is active, in my tests the 1070Ti is very comparable with the 1050Ti.

**Comment by vans163** [comment]
Lol, really? Did you expect to run 1000 sessions on 1 GPU and have them all compete in 10 seconds too?  If so NVIDIA would be out of business as they would only need to sell 1 GPU, and ofc the laws of physics would be broken and Nvidia will rule over all due to their secret technology.
