### ISSUE TITLE
Window's 10 x64 Driver Version 470.05

### ISSUE THREAD

**Issue by supermanz87** [keylase/nvidia-patch#397]
Hi, requesting a few new driver's to the support list.

Window's 10 x64 Driver Version 470.05 WDDM3.0  "this driver version was the one that unlocked mining for the 3060 rtx card's, nvidia removed from there site but can be located easly"
Window's 10 x64 DEV Driver Version 470.14  WDDM3.0
Window's 10 x64 DEV Driver Version 470.15 WDDM3.1

More nvidia driver based information which could help increase task's etc "can be located by using nvidia inspector"

Buffers
What to expect when changing all these values: The lower, the better input and the worse fps. The higher, the better fps and the worse input.

OGL_PULL_MEM_BUFFER_SHARED_THRESHOLD - This controls a dynamic threshold by setting a value to which the memory pull buffer "moves". Not adviced to set this below 0x00000080.

OGL_PULL_MEM_DEFAULT_BUFFER_SIZE - Default memory pull buffer size (starting value). Not adviced to set this below 0x00000080.

MCFORCEHOSTSTAGINGBUFFERSIZE - Sets the Host Staging Buffer Size. This is a global buffer that changes pretty much everything in the GPU queue. Not adviced to set this below 0x00000020.

MAX_PENDING_CMD_BUFFERS - Sets the max pending command buffers that are allowed at the same time. Not adviced to set this below 0x00000001.

Async Values
What to expect when changing all these values: Async values on OFF or Force Sync always provide the best input, but might cause fps drops, stuttering or frametimes issues depending on the game.

ASYNC10_ENABLE - Controls Async10 mode (technically for DX10 and higher).

ASYNC10_NVAPI_MODE - Controls Async10 NVAPI Mode (use 0x00000000 when forcing off).

ASYNC10_OOO_QUERY_LIMIT - Query limit when using Async10 (the maximum amount of elements in the async buffer, before discharging). Not adviced to set this below 0x00000020.

ASYNC10_PRESENT_MODE - Present mode for Async10 (WARNING: crashes NVIDIA Inspector after applying if used in latest graphics drivers).

ASYNC9_ENABLE - Controls Async9 mode (technically for DX9, 9.x, 9Ex, Aero Extensions in Win7 and below).

ASYNC9_PRESENT_MODE - Present mode for Async9.

**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: [e.g. 470.05]
- GPU Model: [e.g. GTX 980 TI]
- OS: [Windows10 x64 Devbuild]
- [YES] I'm willing to participate in testing of new patch version

**Comment by Snawoot** [comment]
Too narrow audience needs this. I'm not inclined to work on it.

However, I'll be glad to process pull request from anyone who is. Maybe it's even viable to fund work on this issue on bountysource.

I'm closing this issue for now because we do not expect any actions be taken with it.
