### ISSUE TITLE
New driver support (version 417.71)

### ISSUE THREAD

**Issue by simonerni** [keylase/nvidia-patch#40]
- Nvidia driver version: [e.g. 417.71]
- GPU Model: [RTX 2060]
- OS: [Ubuntu 18.04]
- [x] I'm willing to participate in testing of new patch version

https://www.nvidia.com/en-us/geforce/news/geforce-rtx-2060-g-sync-compatible-game-ready-driver/

**Comment by Snawoot** [comment]
This article and header of your issue are mentioning driver version which already supported.

https://github.com/keylase/nvidia-patch/tree/master/win
