### ISSUE TITLE
if my gpu usage is at 90% I drop frames/encoder overload

### ISSUE THREAD

**Issue by flameboi900** [keylase/nvidia-patch#401]
Hello,

I love this NVENC patch as it lets me record at the same time while streaming with the same PC with little to no performance dips and drops. But recently I have noticed if my gpu usage is over 90-99% on 3d I drop frames/encoder overload is there a reason for this? as I do remember it working in the past when I used it before with other games and it worked fine but some games that pin the gpu make it drop. My question is does this tweak only allow for multiple nvenc streams or does it reduce usage as well as I noticed it did a little bit but this issue is quite annoying or is there something I am doing wrong?

**Comment by Snawoot** [comment]
Hello!

It does only allow multiple nvenc streams, no hardware performance emerges out of nowhere.

Framedrop may occur for two reasons:

1. Encoder doesn't catching up with video source (performance).
2. FPS mismatch between source video streams and transcoded stream. E.g. conversion of 30 fps video to 24 fps will have frame drop.

**Comment by flameboi900** [comment]
ah makes sense I understand maybe I will just turn a few settings down I mean I was trying really hard to push it recording 1080p 60 at a 15,000 bitrate and streaming in a 6000 bitrate may have just gone a bit overboard I will try to drop them down maybe thanks.

**Comment by Saentist** [comment]
> ah makes sense I understand maybe I will just turn a few settings down I mean I was trying really hard to push it recording 1080p 60 at a 15,000 bitrate and streaming in a 6000 bitrate may have just gone a bit overboard I will try to drop them down maybe thanks.

Learn how to give information
Hardware, Software, reproduction case 

Before all, read what can do your GPU
https://www.elpamsoft.com/?p=Plex-Hardware-Transcoding
