### ISSUE TITLE
NVIDIA GameStream does not work if the driver is patched

### ISSUE THREAD

**Issue by 1011025m** [keylase/nvidia-patch#403]
I use Moonlight to mirror my computer screen to my mobile device. What I realize is, if the patch is applied, it will output errors on the Moonlight client (on my mobile device) instead of working.

It would be great if this behavior is put up in the README.md as a disclaimer.

**To Reproduce**
1. Configure Moonlight Game Streaming
2. Attempt to connect on client

**Expected behavior**
The computer screen should be properly mirrored to the client.

**Environment (please complete the following information):**
 - OS: Windows 10 20H2 Build 19042.928
 - GPU model: GTX 1080 Ti
 - Patch commit used: Not sure.
 - Nvidia driver version: 466.27

**Comment by Snawoot** [comment]
Have you applied skip_sig_check.reg to your system registry?

**Comment by 1011025m** [comment]
Oops, seems like I have to check that out.

**Comment by 1011025m** [comment]
Okay, it works.... sorta. For some reason, it's mirroring my side monitor rather than my main. It might be because of the numbering of the monitors (my side monitor is no.1). However, it does not perform like this without the patch. My main monitor would be mirrored to my mobile device without issues.

I'm not too sure if this is a "me problem", I've even tried swapping ports on the graphics card.

**Comment by Snawoot** [comment]
Regarding documentation, there is explicit notice for moonlight users:

![moonlight notice](https://user-images.githubusercontent.com/3524671/116704952-ad43e180-a9d4-11eb-80f7-9389560e2a1a.png)

> However, it did not perform like this without the patch.

I don't see what is connection between NVENC session instantiation logic which patch affects and video grab source. I advise to rollback patch and do tests again. If there is a difference, file a new issue.
