### ISSUE TITLE
1080 Ti no longer unlocks resizable bar

### ISSUE THREAD

**Issue by S33V33** [keylase/nvidia-patch#406]
I have 2 Nvidia cards RTX 3090 and a GTX 1080 Ti. As of the past 2 driver releases, your unlock patch is no longer working on the 1080Ti. This is the card: https://www.gigabyte.com/us/Graphics-Card/GV-N108TAORUS-X-11GD#kf

Installed the past 2 releases multiple times but no unlock. If I install driver version 466.11 it will unlock.

Both PC's have Win 10X64 PRO 20H2 19042.868 aside from having 2 different vid cards.

**Comment by Snawoot** [comment]
Can anyone else confirm this?

**Comment by Snawoot** [comment]
Not confirmed.

**Comment by S33V33** [comment]
Sorry, wasn't trying to spam, the github site had something whacky happened so I posted it is questions area instead of here. 

I don't see how you can say it is not confirmed when I confirm with every patch release you put out? New driver, new patch release, still doesn't work (when it was successfully working for me in the past). Just because no one else confirmed it doesn't mean it is not happening and should be closed. You threw the towel in pretty quick on it and didn't even ask me for any other info or offer any advice. It may be specific to the hardware manufacturer I have for my GPU and Mobo that no longer successfully patch... I don't know for sure. What I do know is my hardware meets the requirements, I follow your instructions which is super easy but no luck on these 2 systems I have.

I patched my friends PC and it worked on his. The hardware however is different manufacturer.

**Comment by Snawoot** [comment]
Sure, I can provide clarifications on this.

> I don't see how you can say it is not confirmed when I confirm with every patch release you put out? New driver, new patch release, still doesn't work (when it was successfully working for me in the past). Just because no one else confirmed it doesn't mean it is not happening and should be closed.

There are two things to consider:

1. Issues are tool for project development, not for offering users free support. Therefore issues which affects small amount of users (or even problems specific to single user) are irrelevant. Even in case when there is some issue which affects many users or an other room for improvement, but noone wants to work on it for some reasons, issue can be closed. It clearly indicates other people that they should not expect progress on this.
2. At this moment I'm single developer who maintains this repo. For this reason it's easy for me to have a consensus on what will be done and what will should not expect to be done.

> You threw the towel in pretty quick on it and didn't even ask me for any other info or offer any advice. It may be specific to the hardware manufacturer I have for my GPU and Mobo that no longer successfully patch... I don't know for sure. What I do know is my hardware meets the requirements, I follow your instructions which is super easy but no luck on these 2 systems I have.

I've already got enough info. Resizable bar never was something this patch is intended to unlock. It's pretty clear that your success activating it depends on driver version or your PCI bus speed or whatever. It has nothing to do with this the patch.

**Comment by S33V33** [comment]
OK, well that was a much better response than simply closing without info added.

Thank you for the closure, I appreciate it.
