### ISSUE TITLE
Question: Hypervisor detection ?

### ISSUE THREAD

**Issue by Saentist** [keylase/nvidia-patch#407]
Hello,

Is there a way to remove Hypervisor detection for non Quadro cards /this is not SR-IOV relayed/
for example real to virtual PC, VMDirectPath I/O pass-through
for VMWARE there is a undescribed way by adding 
```
hypervisor.cpuid.v0 = FALSE
```

**Comment by Snawoot** [comment]
Hello!

There is a project dedicated to this subject: https://github.com/sk1080/nvidia-kvm-patcher

**Comment by Saentist** [comment]
Outdated and out of support, 
only old version of Windows, and old drives.
