### ISSUE TITLE
Does the patch work for the Headless drivers? No need for a gui.

### ISSUE THREAD

**Issue by DistractedCanuck** [keylase/nvidia-patch#408]
**Environment**
 - OS: [Ubuntu 20.04 Server]
 - GPU model: [GTX 960]
 - Patch commit used: [78f150e6d6d010d1ef6cbffbcb8f56dc5b9d0d66]
 - Nvidia driver version: [460.73.01]
 - Driver typer:  nvidia-headless-460-server
 - 
Hello,

My question is does this patch support headless drivers? I am looking to use the patch for hardware encoding on a home server running jellyfin in docker. I have installed the headless meta driver since I do not need a gui on the server.  

I installed the nvidia drivers with the following command: 	`sudo apt install nvidia-headless-460-server  `

When I run `nvidia-smi` it seems to print that everything is working.

![image](https://user-images.githubusercontent.com/29359986/120034174-09e5ec80-bfd3-11eb-9036-da36377b08ed.png)
  
I cloned the repo to my user and ran from the repo location. It game me to following output: 

```
Detected nvidia driver version: 460.73.01
ERROR: cannot detect driver directory
```
I also tried running it from `/usr/lib/x86_64-linux-gnu`

That being said I don't seem to have most of the drivers that are in the list at the start of the patch.  I've only got: 

```
libnvidia-cfg.so
libnvidia-cfg.so.1
libnvidia-cfg.so.460.73.01
libnvidia-compiler.so.460.73.01
libnvidia-opencl.so.1
libnvidia-opencl.so.460.73.01
libnvidia-ptxjitcompiler.so
libnvidia-ptxjitcompiler.so.1
libnvidia-ptxjitcompiler.so.460.73.0.1
```

So I'm wondering if there is something I'm missing in the installation process or if the headless version is just to different.   

So would running `apt install nvidia-driver-460` and accepting the gui work? Ideally I would like to continue running the server with terminal only.  

Thank you so much for your help!

**Comment by Saentist** [comment]
Install driver from nvidia site, rest is experimenting.

**Comment by Snawoot** [comment]
Hi!

Version 460.73.01 is supported. But it seems you're missing package `libnvidia-encode-460`.
