### ISSUE TITLE
New driver support (version 410.93)

### ISSUE THREAD

**Issue by CmdrDatux** [keylase/nvidia-patch#41]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 410.93
- GPU Model: RTX 2070
- OS: Xubuntu 18.04 LTS
- [x] I'm willing to participate in testing of new patch version

Greetings everyone! I have made a patch (see attachment) to support the driver version 410.93 (current long lived branch version, see: [Nvidia Unix page](https://www.nvidia.com/object/unix.html)). Tested on a Nvidia RTX 2070 with Xubuntu 18.04 and FFmpeg compiled from the sources (with cuda support). Right now, I am running 6 NVenc at the same time without a problem.
[410.93.txt](https://github.com/keylase/nvidia-patch/files/2827151/410.93.txt)

**Comment by Snawoot** [comment]
Great, thank you! Would you like to fork this repo, commit and send us pull request?

**Comment by CmdrDatux** [comment]
You are welcome! Done here: https://github.com/keylase/nvidia-patch/pull/42

**Comment by Snawoot** [comment]
Thanks! Merged.
