### ISSUE TITLE
Used to work, but now doesn't...

### ISSUE THREAD

**Issue by S33V33** [keylase/nvidia-patch#411]
Hi,

Does the PC's bios have anything to do with making this work, or could it stop it from working?

I have 3 PC's, all have AMD ryzen CPU. 

PC 1 does not need this patch to get resizable bar working because it has latest gigabyte bios update that enables bar and it has an RTX 3090 card. Mobo is Gigabyte Aorus Elite X570. Works without patching.

PC 2 has 1080Ti GPU and B450M mobo. Both are gigabyte Aorus line. Mobo has the bios that allows for resizable bar. The patch used to work on this PC but seems to no longer have an effect.

PC 3 has 2080Ti and X470 mobo with latest bios for resizable bar support. Both also gigabyte Aorus line. Patching has no effect.

If I put my 3090 card in PC 2 or PC 3 resizable bar works.

All the PC's I have have the bios settings activated for the resizable bar support.  Do you think there is something in the gigabyte bios that is not allowing the older cards to activate resizable bar? Maybe it is hardcoded for model type and since it is seeing a 1080Ti or 2080Ti it shuts off??? I don't know, I am at a loss. I am obviously doing the patch correct as my friend has a 2080Ti, different mobo (asus I think) and I could get his to activate.

Thank you for your time!

**Comment by Snawoot** [comment]
Duplicates #406 

Please do not spam with issues.
