### ISSUE TITLE
How do i use NVFBC in obs windows 10? please help.

### ISSUE THREAD

**Issue by manjit24** [keylase/nvidia-patch#420]
Hello,

i have nvidia gtx 1050Ti on my laptop geforce 471.41 patched and now i want to capture games in obs using nvfbc because i have very low end processor obs nvfbc plugin is available on linux but not windows. How do i do this can somebody please help me any help will be appreciated thank you.

**Comment by Snawoot** [comment]
Here is documentation: https://github.com/keylase/nvidia-patch/tree/master/win/nvfbcwrp
