### ISSUE TITLE
Generated .so file is 32-bit

### ISSUE THREAD

**Issue by kiwec** [keylase/nvidia-patch#421]
I'm on an x86_64 system, but the generated .so file is 32-bit. Because of this, I can't load it from 64-bit programs (unless I'm mistaken).

```
$ file /usr/lib/libnvidia-fbc.so.470.57.02
/usr/lib/libnvidia-fbc.so.470.57.02: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=fefe17b6f54db432bb73513539242545608f5107, stripped
```

**Environment:**
 - OS: Void linux
 - GPU model: GTX 960
 - Patch commit used: c6e9950d8913e11276b3dc85faa6e91d638c4cfa (master)
 - Nvidia driver version: 470.57.02 (same issue on 460.56)

**Additional context**

I'm trying to use [obs-nvfbc](https://gitlab.com/fzwoch/obs-nvfbc) - here are the OBS logs that made me end up here : 
```
05:07:20 PM.197: os_dlopen(libnvidia-fbc.so.1->libnvidia-fbc.so.1): libnvidia-fbc.so.1: wrong ELF class: ELFCLASS32
05:07:20 PM.197: 
05:07:20 PM.197: Unable to load NvFBC library
05:07:20 PM.197: Failed to initialize module 'nvfbc.so'
```

```
$ file /bin/obs
/bin/obs: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=5adfe156924a22706b1bf06e141d7b8774761051, for GNU/Linux 3.2.0, stripped
```

```
$ file ~/.config/obs-studio/plugins/nvfbc/bin/64bit/nvfbc.so
/home/kiwec/.config/obs-studio/plugins/nvfbc/bin/64bit/nvfbc.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=295a2884aea1d6152fec59f5b86497d48e5ed634, with debug_info, not stripped
```

**Comment by Snawoot** [comment]
Patch doesn't generate any files, it only changes few bytes in 64-bit FBC library already existing in system. Probably obs plugin tries to locate library by wrong path and picks up 32-bit library instead.

**Comment by kiwec** [comment]
Thanks, you're right, package manager was the issue.

For people that might land on this issue : I had both nvidia-libs and nvidia-libs-32bit installed, but it looks the latter package overwrites libnvidia-fbc.so. Fixed by installing that library manually from the official nvidia .run file.
