### ISSUE TITLE
Not working on Debian 11

### ISSUE THREAD

**Issue by Tachi107** [keylase/nvidia-patch#422]
**Describe the bug**
When running `patch-fbc.sh` I get `ERROR: cannot detect driver directory`

**To Reproduce**
1. Install `nvidia-driver` and `libnvidia-encode1` from the Debian repos
2. Run `./patch-fbc.sh` (or `bash patch-fbc.sh`) as root

**Expected behavior**
The patch script should find the driver and patch it

**Output listings**
```shell
Detected nvidia driver version: 460.73.01
ERROR: cannot detect driver directory
```

**Environment (please complete the following information):**
 - OS: Debian 11/Testing
 - GPU model: GTX 1060
 - Patch commit used: `c6e9950d8913e11276b3dc85faa6e91d638c4cfa`
 - Nvidia driver version: 460.73.01

**Additional context**
This seems similar to #256, but installing the "Nvenc codec" (`libnvidia-encode1`, I guess) didn't solve the issue

**Comment by Snawoot** [comment]
In your case you're missing package `libnvidia-fbc1`.

**Comment by Saentist** [comment]
Debian and Ubuntu propaganding to install his super duper limited diver... this is result.

**Comment by Tachi107** [comment]
Thanks @Snawoot! Would a PR adding "install instructions" (the required packages to install) for Debian-based distros be accepted?

**Comment by Snawoot** [comment]
@Tachi107 for number of reasons we stick with installation of driver from site via .run-file. Namely:

* Because this way we ensure we patching exactly what we've seen in run-file
* Because debian package auto-updates wipe changes made by patch

Patching over debian package is simply out of scope for us. We don't aim to support it.

**Comment by Tachi107** [comment]
Okay, thanks for the answer (and for the patch!)
