### ISSUE TITLE
Will your project be helpful to the camera decode?

### ISSUE THREAD

**Issue by Rain-Main** [keylase/nvidia-patch#426]
Hello,

My question is: 

I am now decoding more than 12 cameras by nvidia GPU 1660s. It worked when the camera is less than 12. If more,  the spare threads will break up. 

I checked my computer device, the GPU had a lot space to use, the CPU was  the same.

So , I want to know whether the GPU have limit on decoding camera.
 And I have tried your method,  I can patched successful, but it doesn't raise the decoding camera number.

thank you.

**Comment by Saentist** [comment]
NVDEC/NVENC are not equal to GPU performance capabilities.
install https://github.com/Syllo/nvtop and monitor load of GPU.

**Comment by Rain-Main** [comment]
> NVDEC/NVENC are not equal to GPU performance capabilities.
> install https://github.com/Syllo/nvtop and monitor load of GPU.

Thanks for your reply.
I'm working on the win10, I check the usage by explore. 

![a0750bf7148b55903e7125ee23d25a7](https://user-images.githubusercontent.com/58506571/129309064-822afa4d-5f95-48af-8735-0d4e53a3acf0.png)

If I patched successed, will the GPU could decode more cameras?

**Comment by Saentist** [comment]
We talk about different chips in video card
**GPU-Z** can show more info about your GPU
**nvidia-smi** in terminal also
