### ISSUE TITLE
Don't see NvFBC source in windows 10

### ISSUE THREAD

**Issue by ishansaini** [keylase/nvidia-patch#431]
I have followed steps to patch Nvenc as well as nvfbc on windows but I still don't see NVFBC appearing as a source on OBS. Do I need some additional steps?

**Comment by Snawoot** [comment]
Hello,

I think the only additional step is this: https://github.com/keylase/nvidia-patch/tree/master/win/nvfbcwrp#3rd-party-software

Probably OBS itself also needs some sort of plugin to use NVFBC, but AFAIK it exists only for Linux. I'm not sure, though.
