### ISSUE TITLE
Unsupported driver

### ISSUE THREAD

**Issue by JustCryen** [keylase/nvidia-patch#432]
Hi. the driver version I have is 470.62.02-1 but all recent drivers, and drivers in between (70.57.02 and 470.63.01) have the same variables assigned to them.
Can I safely assume I could manually add my driver version to your script and duplicate the wariables used in other versions?
If it won't work, would I still be able to load the backup?
What it the worst that could happen after such modification?
Thanks for providing such a patch, great work!

**Comment by Snawoot** [comment]
> Can I safely assume I could manually add my driver version to your script and duplicate the wariables used in other versions?
If it won't work, would I still be able to load the backup?

You definitely should try. At most it'll cause ffmpeg crash. In case if it'll not work for you, just rollback: `./patch.sh -r`

In case if it'll work for you, submit PR to add new patch version.
