### ISSUE TITLE
Patch not working on Quadro Driver Version 471.68

### ISSUE THREAD

**Issue by Kung-Foo-Kamel** [keylase/nvidia-patch#436]
**Describe the bug**
Error while patching nvencodecAPI64.dll, I get "Offset [42BAC] Wrong... Set 0x48 -> I expected 0x8B"

**To Reproduce**
1. Install driver version Quadro 471.68 from the link in the table
2. Run the patch tool linked on the Git page
3. Try to patch the dll file using the nvencodecapi64.1337 linked in the table corresponding to the driver 471.68
4. 

**Expected behavior**
To proceed without error

**Output listings**
![Screenshot](https://user-images.githubusercontent.com/20825418/134661802-4f7a079a-ad10-4e87-8f5a-f9323a0ea9de.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10
 - GPU model: Quadro P620
 - Patch commit used: [e.g. 5b828a6d91a14e7bf4f93b31d220e7687ceb638c]
 - Nvidia driver version: 471.68

**Additional context**

**Comment by Snawoot** [comment]
Hello!

Such error occurs if patch applied to wrong version of driver. You can check actual version using nvidia-smi utility: https://stackoverflow.com/a/57100016

Sometimes driver installed by nvidia driver package gets shadowed by driver from Windows updates. If such conflict is the case, use [Display Driver Uninstaller](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) to remove Nvidia drivers, disable nvidia drivers from "Windows update", and then install driver from Nvidia package from Nvidia site.
