### ISSUE TITLE
Can you do a similar driver patch for removing LHR limitation? how do you find out which binary codes to change in the driver

### ISSUE THREAD

**Issue by salmarvasti2020** [keylase/nvidia-patch#445]
Hello,

My question is:  Isntr the nvidia driver encrypted?
So how do you apply these patches without tripping the encryption / decryption?

**Comment by Saentist** [comment]
Hope Nvidia make hardware impossible to do coin digging with GPU.
Cannot found card for transcoding because someone thing will stay billionaire.
