### ISSUE TITLE
supp to 496.49?

### ISSUE THREAD

**Issue by Stolk3r** [keylase/nvidia-patch#447]
hi, i check 2 weeks and dont see supp for the last two drivers, can say what happen?

**Comment by Anuruddha094** [comment]
> > > You might be interested in my project which aims to be a future-proof alternative to `[patch.sh](http://patch.sh)` & `[patch-fbc.sh](http://patch-fbc.sh)`: [illnyang/nvlax](https://github.com/illnyang/nvlax)
> > > Works fine with 470-496, not sure about other versions.
> > 
> > 
> > Thank you for your hard work. Why don't your contribute to Keylase project and release new nvidia patches with your script. It looks neat when everything in one place. +1
> 
> nvlax does only the most essential subset of the _stuff_ that keylase does and could be integrated in place of current solution (i.e preserving existing CLI options and what not). as for the near future, i'm more interested in improving nvlax itself rather than hastily integrate it into a mature project like this in an unstable state

Alright. Then can you please release patches for Windows and Linux Nvidia drivers. Most of the people who is installing those are not coming from technical background. It will be really helpful, if you can release complete parches according to Nividia driver version for Windows and Linux. Good luck on your project. Thank you again for your contribution to the community.

**Comment by iriecolorado** [comment]
> 
> 
> > but how can patch in windows?, i see your post but dont see how do it.
> 
> It does work now, instructions included.

I'm not seeing anything for Windows.  "just use WSL" means literally nothing to me.

**Comment by illnyang** [comment]
> > > but how can patch in windows?, i see your post but dont see how do it.
> > 
> > 
> > It does work now, instructions included.
> 
> I'm not seeing anything for Windows. "just use WSL" means literally nothing to me.

that's unfortunate

**Comment by iriecolorado** [comment]
> 
> 
> > > > but how can patch in windows?, i see your post but dont see how do it.
> > > 
> > > 
> > > It does work now, instructions included.
> > 
> > 
> > I'm not seeing anything for Windows. "just use WSL" means literally nothing to me.
> 
> that's unfortunate

No doubt.

**Comment by phedders** [comment]
@iriecolorado being demanding and rude to those giving their time to help without financial reward is very churlish. I would suggest you have a look to see what you kind find out able WSL without expecting everyone else to spoon-feed you. Worse it is frustrating, demoralising and timewasting for those who have to respond.

The world is not your slave. There are very helpful resources called "search engines" that will almost certainly garner you with the intelligence assist that you require to understand "use WSL".

**Comment by oysteinkrog** [comment]
I created an updated patch, see #464

**Comment by iriecolorado** [comment]
> 
> 
> @iriecolorado being demanding and rude to those giving their time to help without financial reward is very churlish. I would suggest you have a look to see if you can find find out for yourself WSL is and how it will help without expecting everyone else to spoon-feed you. Worse it is frustrating, demoralising and timewasting for those who have to respond.
> 
> The world is not your slave. There are very helpful resources called "search engines" that will almost certainly garner you with the intelligence assist that you require to understand "use WSL".

When did I "demand" anything from anybody?
