### ISSUE TITLE
New driver support (version 470.82.00)

### ISSUE THREAD

**Issue by jak3z** [keylase/nvidia-patch#448]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 470.82.00
- GPU Model: GTX 1050
- OS: Pop OS/Ubuntu 21.04
- [x] I'm willing to participate in testing of new patch version

**Comment by leillo1975** [comment]
Count me in

**Comment by mauricioquintela** [comment]
Count me in as well! More than willing to test the new patch

**Comment by LethalManBoob** [comment]
same here

**Comment by specializedtom** [comment]
Nvidia driver : 470.82.00
GPU Model: MSI GeForce RTX 2070 Super; MSI GeForce RTX 3070 Gaming
OS: Linux/ Fedora 34

Consider me in when testing new patch.

**Comment by rpodcast** [comment]
Nvidia driver: 470.82.00
GPU Model: GeForce RTX 2060 Super with 2176 CUDA Cores
OS: Linux / Pop OS 20.04

Eager to help test!  I rely on using this patch to enable NvENC within OBS

**Comment by rpodcast** [comment]
Good news everyone: I found [this post](https://forum.level1techs.com/t/update-setting-up-nvfbc-for-obs-on-ubuntu-with-troubleshooting-steps/176193) on Levelonetechs demonstrating that simply editing the `patch.sh` or `patch-fbc.sh` scripts to include new lines for the `470.82.00` driver enables the patching to complete. I tested this by adding the following lines in the `patch_list` and `object_list` arrays (while preserving the previous driver records):

### `patch_list`

```
["470.82.00"]='s/\x83\xfe\x01\x73\x08\x48/\x83\xfe\x00\x72\x08\x48/'
```

### `object_list`

```
["470.82.00"]='libnvidia-fbc.so'
```

I have tested this with `patch-fbc.sh` as that was my immediate need, so I haven't tried this with the nvenc `patch.sh` script. After running `sudo ./patch-fbc.sh` I was able to get my scene that uses the NvFBC source to function normally again!

**Comment by LethalManBoob** [comment]
This works!!!

**Comment by mauricioquintela** [comment]
@rpodcast 's fix also works for me. Both for `patch-fbc.sh` and for `patch.sh`. Only difference for `patch.sh` is that the line added to its `object_list` array is different, reading

### `object_list`
 ```
 ["470.82.00"]='libnvidia-encode.so'
 ```

**Comment by umitakkaya** [comment]
> Good news everyone: I found [this post](https://forum.level1techs.com/t/update-setting-up-nvfbc-for-obs-on-ubuntu-with-troubleshooting-steps/176193) on Levelonetechs demonstrating that simply editing the `patch.sh` or `patch-fbc.sh` scripts to include new lines for the `470.82.00` driver enables the patching to complete. I tested this by adding the following lines in the `patch_list` and `object_list` arrays (while preserving the previous driver records):
> 
> ### `patch_list`
> ```
> ["470.82.00"]='s/\x83\xfe\x01\x73\x08\x48/\x83\xfe\x00\x72\x08\x48/'
> ```
> 
> ### `object_list`
> ```
> ["470.82.00"]='libnvidia-fbc.so'
> ```
> 
> I have tested this with `patch-fbc.sh` as that was my immediate need, so I haven't tried this with the nvenc `patch.sh` script. After running `sudo ./patch-fbc.sh` I was able to get my scene that uses the NvFBC source to function normally again!

I can also confirm that it works.

**Comment by leillo1975** [comment]
Yes, it works. Can dev include it on the code?

**Comment by pschroedl** [comment]
Not working for me, on 470.82.00 after pulling main - ran both patch-fbc.sh and patch.sh, same result "cannot allocate memory"

**Comment by specializedtom** [comment]
Same here. Getting a 'cannot allocate memory' error message when running livepool after applying the patch.

**Comment by leillo1975** [comment]
What patch fails, patch.sh or patch-fbc.sh? I don't have problems with no one:
```
Detected nvidia driver version: 470.82.00
Attention! Backup not found. Copying current libnvidia-encode.so to backup.
18b4249e6513b77a69b26c3212c5779736d749a3  /opt/nvidia/libnvidia-encode-backup/libnvidia-encode.so.470.82.00
18b4249e6513b77a69b26c3212c5779736d749a3  /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.470.82.00
Patched!
```

**Comment by specializedtom** [comment]
Patch.sh - using Livepool on Fedora 34.

**Comment by leillo1975** [comment]
Sorry, I only did a Pull Request with the changes shown in this thread...

**Comment by pschroedl** [comment]
Are there other changes somewhere necessary for this to work? both .sh files run successfully, but still produce 'cannot allocate memory' error when trying to run a program that depends on this patch. Has worked fine on every other version.

**Comment by jailuthra** [comment]
Looks like the driver update is done correctly for NVFBC but not for NVENC here https://github.com/keylase/nvidia-patch/commit/97a959fe95fa41370341c17f3a137a151ef2317a#diff-0a4f8ba240035344f40ec13f1857d73e43f174394b6deba7a3b577c89647d4bbR170

Will fix.

**Comment by jailuthra** [comment]
@pschroedl @specializedtom let me know if it works now. restore the backup driver first via: `./patch.sh -r`
then pull from master again and run: `./patch.sh`

**Comment by specializedtom** [comment]
yes, the new patch now works with livepool. Thanks.

**Comment by leillo1975** [comment]
> @pschroedl @specializedtom let me know if it works now. restore the backup driver first via: `./patch.sh -r` then pull from master again and run: `./patch.sh`
I think it will be better for everyone if I leave this in more expert hands. I am very sorry

**Comment by spider3000** [comment]
> livepool

Apologies for the off-topic question, but what's livepool?

**Comment by specializedtom** [comment]
> > livepool
> 
> Apologies for the off-topic question, but what's livepool?

Livepool is a crypto-mining pool, but not a mining-pool in the strictest sense (unlike bitcoin). Livepool allows you to transcode videos via the livepeer blockchain and receive passive income for the work that gets allocated to you.You can run it in the background in conjunction with any GPU intensive process, as it requires very little overhead. (Don't expect life-changing wealth from it though ... ;) ) . You can also stake LPT and receive passive income from the Livepeer network as well. 

Check out the livepool project here. https://www.livepool.io/ , as well as the livepeer blockchain. https://livepeer.org/
