### ISSUE TITLE
Windows 11 Support

### ISSUE THREAD

**Issue by SilentMystification** [keylase/nvidia-patch#453]
The most recent `472.12` driver is not compatible with Windows 11, not out of the box at least. Is there any support for removing the session limit from a Windows 11 install?

**Comment by thisisawesome1994** [comment]
I think no driver is supported on Windows 11, since offset is wrong.
I guess you need to wait for support.

**Comment by jailuthra** [comment]
Yep hoping to get my hands on Win11 and reverse the drivers for the new offset(s).

I've recently become the maintainer of this repo, so still ramping up, thanks for your patience.

**Comment by thisisawesome1994** [comment]
Do you need a license, or a new computer? You can get a license on
royalcdkeys for cheap. Also, if your pc doesn't support win11, Just use the
no tpm mod.

Op do 23 dec. 2021 11:02 schreef Jai Luthra ***@***.***>:

**Comment by thisisawesome1994** [comment]
Do you need a license, or a new computer? You can get a license on royalcdkeys for cheap. Also, if your pc doesn't support win11, Just use the no tpm mod.

**Comment by jeremypsl** [comment]
Is Windows 11 still not supported ?

**Comment by jeremypsl** [comment]
No one try it on W11 ?
Is W11 works different from W10 ?

**Comment by jailuthra** [comment]
Unassigning myself, if someone from the community wants to pick this up, please go ahead!

**Comment by custom90gt** [comment]
I can confirm that it does not allow more than two streams on windows 11 in its current state.  It would be awesome if someone could get this working on Win 11.

**Comment by flashmasta** [comment]
Is there some documentation on finding the offset?  I would be happy to contribute to Win11 patches but I'm not sure where to start.

**Comment by don17sch** [comment]
I tested the existing Windows patch for 516.59 using this method https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch

I was able to get it working with the current drivers and patches already released for windows 10 on this repo

**Comment by Espionage724** [comment]
I can also confirm the patch from this repo works on Windows 11 (22000.795) with driver 512.77. The ffmpeg test works, and Oculus Link works fine too.

**Comment by jailuthra** [comment]
Thanks for testing. Will update the readme to make it clearer that win10/win11 are both supported.
