### ISSUE TITLE
This project is dead, isn't it?

### ISSUE THREAD

**Issue by iriecolorado** [keylase/nvidia-patch#454]
Hello,

My question is: ...
Is this project dead?  Is there anything like it for Windows that works?

**Comment by itsTyrion** [comment]
Why, because it's not fully updated only days after a driver update?

**Comment by federicotorrielli** [comment]
**cringe alert**

**Comment by Snawoot** [comment]
Hello!

It's not really dead, but I'll not maintain it further. I've opened issue and updated projects main page with corresponding notice. From now it's maintained by community - I'll accept only pull requests and applications for maintainer role.

Speaking of alternatives, I'd like to recommend [nvlax](https://github.com/illnyang/nvlax).
I haven't tested it (I don't even have nvidia gpu), but looks good.

**Comment by iriecolorado** [comment]
> 
> 
> Why, because it's not fully updated only days after a driver update?

The Windows side has been dead for 2 months.
