### ISSUE TITLE
Project is looking for a maintainer

### ISSUE THREAD

**Issue by Snawoot** [keylase/nvidia-patch#456]
Hello,

I'm stepping down as a maintainer of this project. If there is someone who'd like to maintain this project further, please respond to this issue and I'll ask @keylase to provide write access to this repo after some screening.

**Comment by Jaybonaut** [comment]
Is it being abandoned because something changed?

**Comment by jailuthra** [comment]
I'm interested!

**Comment by iriecolorado** [comment]
Fingers crossed whoever takes over make this work for people on Windows that aren't software developers.  Asking people to install dev environments and write their own code is a pretty substantial hurdle.

**Comment by keylase** [comment]
> Fingers crossed whoever takes over make this work for people on Windows that aren't software developers. Asking people to install dev environments and build their own code is a pretty substantial hurdle.

Which the most convenient way to work on a Window?

**Comment by Drapersniper** [comment]
Y'all should try to keep this issue clean and relevant, this issue is specifically for people wanting to apply to become maintainers (not discussions about how to do something on windows)

**Comment by Snawoot** [comment]
New maintainer elected: meet @jailuthra!
