### ISSUE TITLE
driver 470.82.00

### ISSUE THREAD

**Issue by sakurachan00** [keylase/nvidia-patch#460]
this line should be "    ["470.82.00"]='libnvidia-encode.so' "
https://github.com/keylase/nvidia-patch/blob/d4ee5b4d6ee1911b34c6a5054ec272d26b241e91/patch.sh#L286

**Comment by leillo1975** [comment]
You are absolutely right. Sorry, it's my fault

**Comment by jailuthra** [comment]
My bad, I missed this during review.
@leillo1975 you'll probably need to update your fork before fixing it.

**Comment by leillo1975** [comment]
I create a new Pull Request:
https://github.com/keylase/nvidia-patch/pull/462
Sorry

**Comment by jailuthra** [comment]
No worries, thanks for the fix.
