### ISSUE TITLE
New driver support (version 496.76) - (patch download included)

### ISSUE THREAD

**Issue by reloxx13** [keylase/nvidia-patch#465]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 496.76
- OS: Win10x64
- [x] I'm willing to participate in testing of new patch version

[nvEncodeAPI64_patched_496.76.zip](https://github.com/keylase/nvidia-patch/files/7550242/nvEncodeAPI64_patched_496.76.zip)

created with https://github.com/illnyang/nvlax patcher

**Comment by BionicAlice** [comment]
Not having luck with the patched dll. Still limited to max 3 nvenc streams

**Comment by nyanmisaka** [comment]
```
[h264_nvenc @ 00000263452059c0] OpenEncodeSessionEx failed: out of memory (10): (no details)
[h264_nvenc @ 00000263452059c0] No capable devices found
```
Also failed on Win10 64bit with GTX 1650.

**Comment by Jaybonaut** [comment]
Just swinging by, currently using 472.12, has there been any progress from these wonderful people to go beyond this driver version yet for those of us using Windows and Plex?  I had been using the Win_1337_Apply_Patch_v1.9 by DFoX up until this point.  Apparently something changed?  Apologies for my ignorance in advance.

**Comment by reloxx13** [comment]
up for another try?

i tested it with plex and i could transcode 6 multiple streams at once. but i think my test is not that reliable with plex.

[win10x64_497.09_patched.zip](https://github.com/keylase/nvidia-patch/files/7644006/win10x64_497.09_patched.zip)


again created with https://github.com/illnyang/nvlax patcher

> ```
> [h264_nvenc @ 00000263452059c0] OpenEncodeSessionEx failed: out of memory (10): (no details)
> [h264_nvenc @ 00000263452059c0] No capable devices found
> ```
> 
> Also failed on Win10 64bit with GTX 1650.

this does not look like a limit error.

> Not having luck with the patched dll. Still limited to max 3 nvenc streams. Thanks for trying though. I don't know why it does not work, but I am on windows10x64 .Nvidia card is 1660ti.

isnt the orginal nvidia limit 2 ? be sure u dont have set other limits as u can do in plex (e.g.: max simultaneous streams per user)

**Comment by nyanmisaka** [comment]
I can confirm this is the limit error.
https://stackoverflow.com/questions/46393526/ffmpeg-cuda-encode-openencodesessionex-failed-out-of-memory

The original encoding session limit is 3.
Will try it after I upgraded to 497.09.

**Comment by Jaybonaut** [comment]
It was 2 for years but a little while back they changed it to 3.

**Comment by nyanmisaka** [comment]
I replaced the `nvEncodeAPI64.dll` in System32 with your patched one, but the limit error still exists on my GTX 1650.

My driver version is 497.09 game ready driver `497.09-desktop-win10-win11-64bit-international-dch-whql.exe`. Is there something wrong?

**Comment by nyanmisaka** [comment]
https://github.com/illnyang/nvlax/issues/6

**Comment by Shawak** [comment]
> I replaced the `nvEncodeAPI64.dll` in System32 with your patched one, but the limit error still exists on my GTX 1650.
> 
> My driver version is 497.09 game ready driver `497.09-desktop-win10-win11-64bit-international-dch-whql.exe`. Is there something wrong?

Did you also replace `C:\Windows\SysWOW64\nvEncodeAPI.dll`?

**Comment by reloxx13** [comment]
> > I replaced the `nvEncodeAPI64.dll` in System32 with your patched one, but the limit error still exists on my GTX 1650.
> > My driver version is 497.09 game ready driver `497.09-desktop-win10-win11-64bit-international-dch-whql.exe`. Is there something wrong?
> 
> Did you also replace `C:\Windows\SysWOW64\nvEncodeAPI.dll`?

no

**Comment by jailuthra** [comment]
closing this as latest windows driver is now supported.
