### ISSUE TITLE
New driver support (version 470.86)

### ISSUE THREAD

**Issue by snek100** [keylase/nvidia-patch#467]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 470.86
- GPU Model: GTX 1060
- OS: Debian unstable with Gnome 41.1
- [x] I'm willing to participate in testing of new patch version
- (please ask if i left out any information)

**Comment by jailuthra** [comment]
@snek100 can you test #468? if it works i'll merge!

**Comment by snek100** [comment]
> @snek100 can you test #468? if it works i'll merge!

ok, i will test it.

**Comment by snek100** [comment]
> > @snek100 can you test #468? if it works i'll merge!
> 
> ok, i will test it.

yup, it works!
