### ISSUE TITLE
Question: Parsec Not Working After Patching Nvidia Drivers

### ISSUE THREAD

**Issue by scottruzal** [keylase/nvidia-patch#471]
Hi,

I recently installed and patched the 472.12 Studio Driver on Windows 10. The patch seemed to be successful, but I noticed that my computer was no longer showing up as a host in Parsec for game streaming. I imported the registry values that are supposed to act as a workaround for the binary signature mismatch, but my computer is still not showing up as a host in Parsec.

Has anyone encountered this issue or might know of a potential fix?

Environment (please complete the following information):

    OS: Windows 10
    GPU model: Nvidia GTX-1070
    Patch commit used: 69efb24
    Nvidia driver version: 472.12 Studio Driver

**Comment by alexonpeace** [comment]
Found any fix for this?
In my case parsec shows up but when I try to host it crashes and restarts itself (parsec)
