### ISSUE TITLE
New driver support (version 495.46)

### ISSUE THREAD

**Issue by ShayBox** [keylase/nvidia-patch#473]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 495.46
- GPU Model: GTX 1080 Ti
- OS: ArchLinux
- [x] I'm willing to participate in testing of new patch version
Arch just updated to 495.46

**Comment by fkortsagin** [comment]
Changed both the patch-fbc.sh and patch.sh by adding the 495.46 and it seems to work,tested on Arch Linux with OBS nvfbc
patch-fbc.sh on pastebin:
https://pastebin.com/qaqjeafB
patch.sh on pastebin:
https://pastebin.com/qm6cg7cJ

Hope it helps!

**Comment by jailuthra** [comment]
Fixed in #474
