### ISSUE TITLE
New driver support (version 470.94)

### ISSUE THREAD

**Issue by DirtYiCE** [keylase/nvidia-patch#475]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 470.94
- GPU Model: GT 640
- OS: Gentoo
- [x] I'm willing to participate in testing of new patch version

**Comment by jailuthra** [comment]
Can you test if #480 works for you? If yes I'll merge it :)

**Comment by DirtYiCE** [comment]
Oh, the signatures from the previous version, I wanted to test them but I forgot about it. Anyway, I tested it now:
NvFBC + obs: OK
NVENC obs single stream: OK
To be honest, the NVENC patch is kinda pointless with this card, since it can't even keep up with a single full-HD stream, but at least it looks like it doesn't break things.

**Comment by jailuthra** [comment]
Thanks, will merge!
