### ISSUE TITLE
New driver support (version 472.84)

### ISSUE THREAD

**Issue by gthbububba** [keylase/nvidia-patch#478]
Are we seeing support for 472.84 Quadro? Maybe as a christmas gift?
Thx a lot

**Comment by jailuthra** [comment]
@gthbububba Can you test if #481 works for you? If it does I'll merge it.
Also let me know which system you're testing it on (i.e. is your Quadro running on a windows server or on standard Win10)

**Comment by gthbububba** [comment]
Thanks a lot.

Win21H2
DCH drivers:
https://de.download.nvidia.com/Windows/Quadro_Certified/472.84/472.84-quadro-rtx-desktop-notebook-win10-win11-64bit-international-dch-whql.exe

Patch went through (I didn't see any change in the patch regarding to 472.12_nvencodeapi.1337 and 472.12_nvencodeapi64.1337 as these seem to be he same patches just with an updated version number).

Was not yet able to test the concurrent nvenc streams but driver is stable after patching.

Merry xmas!
