### ISSUE TITLE
GeForce RTX 3090 not connect to mining rig. What to do?

### ISSUE THREAD

**Issue by DarkComputerMiner** [keylase/nvidia-patch#484]
Hello,
I am currently running a 4 GPU mining rig. 
GPU: 4 GeForce RTX 3060
CPU: Intel Core i5 10400
RAM: Team Group T-Force Delta 2x 32 GB
Motherboard: MSI MPG Z570 Gaming Carbon WiFi
PSU: MonTech Gold 850 Watt 2x

I want to add a Zotac Gaming GeForce RTX 3090 to this rig. I am a beginner, so I have absolutely no experience with this stuff. 
There are 5 PCI-E slots on my motherboard. Whenever I add my GeForce RTX 3090, nothing happens. It doesn't show up on Device Manager. Everything is compatible(I think).

I tried: 
1. All Different PCI-E Lanes
2. Checking all cables
3. Taking all cables off and putting them back on
4. NVIDIA Gaming Experience doesn't recognize the GPU either. 
When I remove all other GPU's and only use that one, NVIDIA Gaming Experience says that it doesn't see a NVIDIA Card. 
5. Tried restarting rig

What should I do???

**Comment by jailuthra** [comment]
Closing because not relevant to the project.
