### ISSUE TITLE
CentOS problem

### ISSUE THREAD

**Issue by Saentist** [keylase/nvidia-patch#5]
I try to use CentOS with QSV and NVEnc on same 
but after installing Driver Version: 396.24 and bash ./patch.sh
I get some strange messages 

> [root@AsRock nvidia-patch]# bash ./patch.sh
Detected nvidia driver version: 396.24
Attention! Backup not found. Copy current libnvidia-encode to backup.
cp: не могат да се получат атрибутите на „/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.396.24“: Няма такъв файл или директория
sha1sum: /opt/nvidia/libnvidia-encode-backup/libnvidia-encode.so.396.24: Няма такъв файл или директория
./patch.sh: line 76: /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.396.24: Няма такъв файл или директория
sha1sum: /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.396.24: Няма такъв файл или директория
ldconfig: /lib64/libva.so.1 не е символна връзка

Patched!

under CentOS installer use this dirs
cat /var/lib/nvidia/dirs

> /usr/src/nvidia-396.24/nvidia
/usr/src/nvidia-396.24
/usr/src/nvidia-396.24/common/inc
/usr/src/nvidia-396.24/common
/usr/lib64/xorg/modules/extensions
/usr/lib64/xorg/modules
/usr/lib64/xorg
/usr/share/nvidia
/usr/share/glvnd/egl_vendor.d
/usr/share/glvnd
/usr/lib64/xorg/modules/drivers
/usr/share/doc/NVIDIA_GLX-1.0
/usr/share/doc/NVIDIA_GLX-1.0/sample
/usr/src/nvidia-396.24/nvidia-uvm
/usr/src/nvidia-396.24/nvidia-uvm/hwref/volta/gv100
/usr/src/nvidia-396.24/nvidia-uvm/hwref/volta
/usr/src/nvidia-396.24/nvidia-uvm/hwref
/usr/src/nvidia-396.24/nvidia-uvm/hwref/pascal/gp100
/usr/src/nvidia-396.24/nvidia-uvm/hwref/pascal
/usr/src/nvidia-396.24/nvidia-uvm/hwref/kepler/gk104
/usr/src/nvidia-396.24/nvidia-uvm/hwref/kepler
/usr/share/egl/egl_external_platform.d
/usr/share/egl
/usr/src/nvidia-396.24/nvidia-modeset
/usr/src/nvidia-396.24/nvidia-drm
/usr/share/doc/NVIDIA_GLX-1.0/html
/usr/lib/tls
/usr/lib/vdpau
/etc/vulkan/icd.d
/etc/vulkan

**Comment by Saentist** [comment]
`git diff
diff --git a/patch.sh b/patch.sh
index 474f2b9..83ccf54 100755
--- a/patch.sh
+++ b/patch.sh
@@ -59,7 +59,7 @@ fi
 if [[ $rollback_flag ]]; then
     if [[ -f $backup_path/libnvidia-encode.so.$driver_version ]]; then
         cp $backup_path/libnvidia-encode.so.$driver_version \
-           /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.$driver_version
+           /usr/lib/libnvidia-encode.so.$driver_version
         echo "Restore from backup libnvidia-encode.so.$driver_version"
     else
         echo "Backup not found. Try to patch first."
@@ -69,13 +69,13 @@ else
     if [[ ! -f $backup_path/libnvidia-encode.so.$driver_version ]]; then
         echo "Attention! Backup not found. Copy current libnvidia-encode to backup."
         mkdir -p $backup_path
-        cp /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.$driver_version \
+        cp /usr/lib/libnvidia-encode.so.$driver_version \
            $backup_path/libnvidia-encode.so.$driver_version
     fi
     sha1sum $backup_path/libnvidia-encode.so.$driver_version
     sed "$patch" $backup_path/libnvidia-encode.so.$driver_version > \
-      /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.$driver_version
-    sha1sum /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.$driver_version
+      /usr/lib/libnvidia-encode.so.$driver_version
+    sha1sum /usr/lib/libnvidia-encode.so.$driver_version
     ldconfig
     echo "Patched!"
 fi
`
this fix issue, error about libva still persist
`bash ./patch.sh
Detected nvidia driver version: 396.24
Attention! Backup not found. Copy current libnvidia-encode to backup.
7380401327d0c3dd93fcd738e9bcd23b7dceb915  /opt/nvidia/libnvidia-encode-backup/libnvidia-encode.so.396.24
7380401327d0c3dd93fcd738e9bcd23b7dceb915  /usr/lib/libnvidia-encode.so.396.24
ldconfig: /lib64/libva.so.1 не е символна връзка

Patched!
`

**Comment by tomashavlas** [comment]
path to library should be `/usr/lib64/libnvidia-encode.so.$driver_version`, not `/usr/lib/libnvidia-encode.so.$driver_version`

**Comment by keylase** [comment]
How often do you use centos?
Is it really necessary to add centos support to the patch?

**Comment by Saentist** [comment]
I use it continuously because Intel's QSV work only on this OS without problems
Flussonic can use both QSV and NVENC in same time E3 v2-v5 Xeon's, gen 3-5 i3-i5-i7
minus one GPU card when anyone have CPU video and PCI-E slots finish ;)

**Comment by keylase** [comment]
Ok. I'l add centos in two-days. I hope for your help in testing 😃 

Offtop: Can you create step-by-step instruction for qsv enabling? I thinking about new script (for very lazy people) with scenario: 
1. install nvenc (if supporting by hardware)
2. patch nvenc (if exist nvenc)
3. install qsv (if supporting by hardware)

**Comment by Saentist** [comment]
QSV cannot be installed so easy
http://streambuilder.pro/enabling-iqsv
https://github.com/mzyy94/QSV-on-Linux

intel need to learn how to write software and make modules not modified kernel ;)

**Comment by keylase** [comment]
#10
