### ISSUE TITLE
511.79 is now listed as supported here

### ISSUE THREAD

**Issue by Jaybonaut** [keylase/nvidia-patch#504]
Hello,

My question is: ...
Is this working again?  Has anyone tried it?

**Comment by jailuthra** [comment]
Yes I tested on Win10 while creating the new patch #502, worked for me. 

Let me know if you face any issues

**Comment by Jaybonaut** [comment]
I wonder why we went through so many updates without being able to use the old method and then suddenly we get these new ones.  If this is working again, that's wonderful/amazing and very much appreciated

**Comment by jailuthra** [comment]
> I wonder why we went through so many updates without being able to use the old method and then suddenly we get these new ones.

Because when the driver bytecode changes significantly, somebody needs to go through the disassembly to find the artificial limit again, which requires some time commitment. Patches welcome :)
