### ISSUE TITLE
New driver support (version 390.147)

### ISSUE THREAD

**Issue by coldfire7** [keylase/nvidia-patch#507]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 390.147
- GPU Model: Quadro P600
- OS: Ubuntu 20.04.4 LTS
- [x] I'm willing to participate in testing of new patch version

**Comment by jailuthra** [comment]
@coldfire7 can you test if #508 works for you? will merge if it does.

**Comment by coldfire7** [comment]
Patched successfully!
```
root@galaxy: /tmp/nvidia-patch 
$ bash ./patch.sh
Detected nvidia driver version: 390.147
Attention! Backup not found. Copying current libnvidia-encode.so to backup.
63e48dd9f8685c2e7c9577041e5daf9594e19fb7  /opt/nvidia/libnvidia-encode-backup/libnvidia-encode.so.390.147
d32604494c1ae628698e147fd5271538a7ec7a26  /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.390.147
Patched!
```
But couldn't test it since the `ffmpeg` test I usually run isn't supported and Jellyfin requires a newer driver `455.28 or newer`.
```
[h264_nvenc @ 0x561be806f100] [error] Driver does not support the required nvenc API version. Required: 9.1 Found: 8.1
```
