### ISSUE TITLE
Works with Plex Media Server!

### ISSUE THREAD

**Issue by niXta1** [keylase/nvidia-patch#51]
**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 (Windows not tested)
 - GPU model: GTX 1050Ti

**Additional context**
Plex has updated ffmpeg with the v1.15 (plexpass) release and the patch now works perfectly!
Pair it with this script for full HW transcoding:
https://forums.plex.tv/t/hardware-accelerated-decode-nvidia-for-linux/233510/172

**Comment by edasque** [comment]
Can't wait for this to hit the docker image

**Comment by Snawoot** [comment]
Thank you, @niXta1!

Merged PR #52 which reflects info collected by you in main doc file. I'll keep this issue open for a while to let people know.

**Comment by niXta1** [comment]
>Can't wait for this to hit the docker image

@edasque here is an pre scripted (hw nvdec added) docker image: https://hub.docker.com/r/adnanklink/plex-norelay-hwdecoding

**Comment by imayo** [comment]
I tried this for 418.81 on Windows 10 64 bits and is not working.
Our software uses NVENC and after testing I was not able to run more than 2 NVENC instances. My concers are in why is nvcuvid.dll being patched, as far as I know this dll was the old one with CUDA enc/dec implementations. New NVENC encoder implementation seems to not rely on nvcuvid.dll, it is not even loaded into our server process, in contrast when using NVENC the one loaded is:

NVIDIA Video Encoder API, Version 8.0
C:\Windows\System32\nvEncodeAPI64.dll

Could this patch be made for this DLL?

**Comment by niXta1** [comment]
>I tried this for 418.81 on Windows 10 64 bits and is not working. ...

@imayo We would need to know the arguments for the ffmpeg. Can you confirm which ffmpeg version it is?

ffmpeg directly, emby and plex on linux works so it feels like it should work - if plex really uses nvdec+nvenc.

**Comment by Snawoot** [comment]
At this moment it is still unclear if mentioned above technique works for Plex on Windows. If it has NVENC/NVDEC-capable ffmpeg and it is possible to make similar wrapper enabling required FFmpeg options, then full HW support can be achieved. If it hasn't - sad, but nothing to do here, it's Plex issue.

Either way I consider work on this issue completed.

**Comment by niXta1** [comment]
>At this moment it is still unclear if mentioned above technique works for Plex on Windows. If it has NVENC/NVDEC-capable ffmpeg and it is possible to make similar wrapper enabling required FFmpeg options, then full HW support can be achieved. If it hasn't - sad, but nothing to do here, it's Plex issue. ...

@Snawoot I've got an answer on plex forums that it's still using dxva2+mf. It should be possible to use a script to force NVDEC/ENC but that is outside the scope of this patch.
All in all, Great Success!
