### ISSUE TITLE
Question: My CUDA drive is 470.86, when I use the command `bash patch.sh`, it seemly doesn't work successfully.

### ISSUE THREAD

**Issue by fhkong** [keylase/nvidia-patch#510]
Hello,

My question is: 
When I use the command `bash patch.sh` on my server with 2080Ti, It seemly does not work. And the output is following.
Detected nvidia driver version: 470.86
Backup exists and driver file differ from backup. Skipping patch.

**Comment by jailuthra** [comment]
>  Backup exists and driver file differ from backup. Skipping patch.

@fhkong this means patch is already applied, can you [test](https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch) if session limit is still there?

In any case might be helpful to restore original driver using `./patch.sh -r` and apply again `./patch.sh`
