### ISSUE TITLE
Vulkan loader/tools update breaks the use of nvfbc?

### ISSUE THREAD

**Issue by xpander69** [keylase/nvidia-patch#512]
Hello,

Sorry if its not the right place to ask, maybe it needs to be asked on the obs plugin github directly, but has anyone else noticed that updating vulkan loader/tools breaks the fbc plugin working with OBS. It keeps spamming `invalid external buffer capabilities` when starting OBS from command line.
Downgrading the packages makes it work again.

```
xpander@archlinux ~ $ sudo downgrade vulkan-tools  vulkan-icd-loader
loading packages...
warning: downgrading package vulkan-icd-loader (1.3.207-1 => 1.2.203-1)
warning: downgrading package vulkan-tools (1.3.207-1 => 1.2.203-2)
```
RTX 3080
Arch Linux
510.54 drivers

Sorry if its wrong place to ask for it

**Comment by jailuthra** [comment]
Yes this is a known issue (see #511), unrelated to this patch.

Keeping this open for a while to prevent further duplicates.
