### ISSUE TITLE
will the 3080 patch work for a 3080ti?

### ISSUE THREAD

**Issue by mcfalld** [keylase/nvidia-patch#519]
Hello,
I don't see anything for the 3080ti, would the patch for the 3080 work for it?

**Comment by mcfalld** [comment]
awesome thanks for the info, will i need to stop updating my graphics driver after the patch?

**Comment by jailuthra** [comment]
@mcfalld you can still update drivers, but don't update immediately when a new release is out - as sometimes getting a new patch out takes a while.
