### ISSUE TITLE
New driver support (version 510.68.02)

### ISSUE THREAD

**Issue by JayRovacsek** [keylase/nvidia-patch#521]
- Nvidia driver version: 510.68.02
- GPU Model: GTX 1060
- OS: NixOS 22.05
- [x] I'm willing to participate in testing of new patch version

Looks like the new patch has only been out a day or two - have made the assumption that given the [described changeset](https://www.nvidia.com/download/driverResults.aspx/187526/en-us) the previous 510.60.02 patch will likely be fine and have already rebuild with the same patch applied in terms of NVENC patch (what could go wrong, right? :smile:)

**Comment by Jaybonaut** [comment]
You mean version 512.59?

**Comment by jailuthra** [comment]
@JayRovacsek can you send a PR if the older patch for 510.60.02 worked for you?

**Comment by aklsh** [comment]
@JayRovacsek yes, the patch for 510.60.02 worked for 510.68.02. I haven't tried out the NvFBC patch yet. Will try it and make a PR.

**Comment by JayRovacsek** [comment]
Hey all, apologies for the slow reply; that would be awesome thanks @aklsh 😍 - I also haven't tested the NvFBC patch for this version but can confirm again that version [510.60.02](https://github.com/JayRovacsek/nix-config/blob/a92a3fd7eb8c0e756585fcf91eeb87fa4e891da9/modules/nvidia/nvenc-unlock.nix#L173) patch appears to work against [510.68.02](https://github.com/JayRovacsek/nix-config/blob/a92a3fd7eb8c0e756585fcf91eeb87fa4e891da9/modules/nvidia/nvenc-unlock.nix#L175)

@aklsh - also happy to create the PR, but if I do it will be in a day or two when I'm able to test the NvFBC patch also 👍
