### ISSUE TITLE
New driver support (version 515.43.04)

### ISSUE THREAD

**Issue by Centterm** [keylase/nvidia-patch#528]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 515.43
- GPU Model: 1660 TI
- OS: Ubuntu 20.04
- [x] I'm willing to participate in testing of new patch version

This is the version the new cuda 11.7 ships per default. Support would be appreciated.

**Comment by Centterm** [comment]
I just saw the PR https://github.com/keylase/nvidia-patch/pull/526/files which I have tested and it does **not** seems to work for me!

**Comment by jailuthra** [comment]
@Centterm can you test #529 for nvenc? I've updated with the latest bytecode.

**Comment by LionHeartP** [comment]
Confirmed it works but there is a typo on the .so line looking for a 510 driver instead. Here's the multiple ffmpeg NVENC stream start that confirms I can open 4 different sessions.
`fmpeg -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda \
-f lavfi -i testsrc -t 50 \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 4M -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 1M -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 8M -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 6M -f null -  
bash: fmpeg: command not found
[lionheartp@endeavourPC ~]$ ffmpeg -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -f lavfi -i testsrc -t 50 -vf hwupload -c:a copy -c:v h264_nvenc -b:v 4M -f null - -vf hwupload -c:a copy -c:v h264_nvenc -b:v 1M -f null - -vf hwupload -c:a copy -c:v h264_nvenc -b:v 8M -f null - -vf hwupload -c:a copy -c:v h264_nvenc -b:v 6M -f null -  
ffmpeg version n5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Passing a number to -vsync is deprecated, use a string argument as described in the manual.
Input #0, lavfi, from 'testsrc':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 320x240 [SAR 1:1 DAR 4:3], 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_nvenc))
  Stream #0:0 -> #1:0 (rawvideo (native) -> h264 (h264_nvenc))
  Stream #0:0 -> #2:0 (rawvideo (native) -> h264 (h264_nvenc))
  Stream #0:0 -> #3:0 (rawvideo (native) -> h264 (h264_nvenc))
Press [q] to stop, [?] for help
Output #0, null, to 'pipe:':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #0:0: Video: h264 (Main), cuda(pc, gbr/unknown/unknown, progressive), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 4000 kb/s, 25 fps, 25 tbn
    Metadata:
      encoder         : Lavc59.18.100 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 0/0/4000000 buffer size: 8000000 vbv_delay: N/A
Output #1, null, to 'pipe:':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #1:0: Video: h264 (Main), cuda(pc, gbr/unknown/unknown, progressive), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 1000 kb/s, 25 fps, 25 tbn
    Metadata:
      encoder         : Lavc59.18.100 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 0/0/1000000 buffer size: 2000000 vbv_delay: N/A
Output #2, null, to 'pipe:':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #2:0: Video: h264 (Main), cuda(pc, gbr/unknown/unknown, progressive), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 8000 kb/s, 25 fps, 25 tbn
    Metadata:
      encoder         : Lavc59.18.100 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 0/0/8000000 buffer size: 16000000 vbv_delay: N/A
Output #3, null, to 'pipe:':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #3:0: Video: h264 (Main), cuda(pc, gbr/unknown/unknown, progressive), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 6000 kb/s, 25 fps, 25 tbn
    Metadata:
      encoder         : Lavc59.18.100 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 0/0/6000000 buffer size: 12000000 vbv_delay: N/A
frame= 1250 fps=129 q=8.0 Lq=9.0 q=9.0 q=9.0 size=N/A time=00:15:19.44 bitrate=N/A speed=94.6x    
video:44350kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
`

**Comment by jailuthra** [comment]
@LionHeartP thanks for testing and pointing out the typo. Will fix and merge!
