### ISSUE TITLE
New driver support (version 510.73.05)

### ISSUE THREAD

**Issue by Foexle11** [keylase/nvidia-patch#533]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: [510.73.05-0ubuntu0.20.04.1]
- GPU Model: [RTX 2070 Super]
- OS: [Linux Mint Cinnamon 20.3]
- [x] I'm willing to participate in testing of new patch version (of cause ^^)

**Comment by jailuthra** [comment]
@Foexle11 let me know if #534 works for you!

**Comment by arifwn** [comment]
@Foexle11 #534 is working on my system (510.73.05, ubuntu 20.04.1, GTX 1650). NVENC/NvFBC with Sunshine is working.

**Comment by hooyap** [comment]
> > The patch-fbc.sh does indeed work without any problems. (Tested with OBS) The patch.sh seems to install, but when I'll try to verify the install via `https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch` I get an Error:
> > ```
> > [hwupload @ 0x5619affd9880] A hardware device reference is required to upload frames to.
> > [Parsed_hwupload_0 @ 0x5619affdbbc0] Query format failed for 'Parsed_hwupload_0': Invalid argument
> > Error reinitializing filters!
> > Failed to inject frame into filter network: Invalid argument
> > Error while processing the decoded data for stream #0:0
> > Conversion failed!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Don't know if thats an issue on my side, never used that part of the patch, only for fbc ^^
> 
> I also got this error:
> 
> ```shell
> $ env ffmpeg -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda \
> -f lavfi -i testsrc -t 50 \
> -vf hwupload -c:a copy -c:v h264_nvenc -b:v 4M -f null - \
> -vf hwupload -c:a copy -c:v h264_nvenc -b:v 1M -f null - \
> -vf hwupload -c:a copy -c:v h264_nvenc -b:v 8M -f null - \
> -vf hwupload -c:a copy -c:v h264_nvenc -b:v 6M -f null -
> ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
>   built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
>   configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
>   libavutil      56. 31.100 / 56. 31.100
>   libavcodec     58. 54.100 / 58. 54.100
>   libavformat    58. 29.100 / 58. 29.100
>   libavdevice    58.  8.100 / 58.  8.100
>   libavfilter     7. 57.100 /  7. 57.100
>   libavresample   4.  0.  0 /  4.  0.  0
>   libswscale      5.  5.100 /  5.  5.100
>   libswresample   3.  5.100 /  3.  5.100
>   libpostproc    55.  5.100 / 55.  5.100
> Input #0, lavfi, from 'testsrc':
>   Duration: N/A, start: 0.000000, bitrate: N/A
>     Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 320x240 [SAR 1:1 DAR 4:3], 25 tbr, 25 tbn, 25 tbc
> Stream mapping:
>   Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_nvenc))
>   Stream #0:0 -> #1:0 (rawvideo (native) -> h264 (h264_nvenc))
>   Stream #0:0 -> #2:0 (rawvideo (native) -> h264 (h264_nvenc))
>   Stream #0:0 -> #3:0 (rawvideo (native) -> h264 (h264_nvenc))
> Press [q] to stop, [?] for help
> [hwupload @ 0x56235368c0c0] A hardware device reference is required to upload frames to.
> [Parsed_hwupload_0 @ 0x56235368bfc0] Query format failed for 'Parsed_hwupload_0': Invalid argument
> Error reinitializing filters!
> Failed to inject frame into filter network: Invalid argument
> Error while processing the decoded data for stream #0:0
> Conversion failed!
> ```
> 
> Following examples on [Using FFmpeg with NVIDIA GPU Hardware Acceleration](https://docs.nvidia.com/video-technologies/video-codec-sdk/pdf/Using_FFmpeg_with_NVIDIA_GPU_Hardware_Acceleration.pdf) I was able init device and verify NVENC patch:
> 
> ```
> -init_hw_device cuda=foo:bar -filter_hw_device foo
> ```
> 
> Verify Patch:
> 
> ```
> env ffmpeg -y -vsync 0 -init_hw_device cuda=foo:bar -filter_hw_device foo -hwaccel cuda -hwaccel_output_format cuda \
> -f lavfi -i testsrc -t 50 \
> -vf hwupload -c:a copy -c:v h264_nvenc -b:v 4M -f null - \
> -vf hwupload -c:a copy -c:v h264_nvenc -b:v 1M -f null - \
> -vf hwupload -c:a copy -c:v h264_nvenc -b:v 8M -f null - \
> -vf hwupload -c:a copy -c:v h264_nvenc -b:v 6M -f null -
> ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
>   built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
>   configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
>   libavutil      56. 31.100 / 56. 31.100
>   libavcodec     58. 54.100 / 58. 54.100
>   libavformat    58. 29.100 / 58. 29.100
>   libavdevice    58.  8.100 / 58.  8.100
>   libavfilter     7. 57.100 /  7. 57.100
>   libavresample   4.  0.  0 /  4.  0.  0
>   libswscale      5.  5.100 /  5.  5.100
>   libswresample   3.  5.100 /  3.  5.100
>   libpostproc    55.  5.100 / 55.  5.100
> Input #0, lavfi, from 'testsrc':
>   Duration: N/A, start: 0.000000, bitrate: N/A
>     Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 320x240 [SAR 1:1 DAR 4:3], 25 tbr, 25 tbn, 25 tbc
> Stream mapping:
>   Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_nvenc))
>   Stream #0:0 -> #1:0 (rawvideo (native) -> h264 (h264_nvenc))
>   Stream #0:0 -> #2:0 (rawvideo (native) -> h264 (h264_nvenc))
>   Stream #0:0 -> #3:0 (rawvideo (native) -> h264 (h264_nvenc))
> Press [q] to stop, [?] for help
> Output #0, null, to 'pipe:':
>   Metadata:
>     encoder         : Lavf58.29.100
>     Stream #0:0: Video: h264 (h264_nvenc) (Main), cuda, 320x240 [SAR 1:1 DAR 4:3], q=-1--1, 4000 kb/s, 25 fps, 25 tbn, 25 tbc
>     Metadata:
>       encoder         : Lavc58.54.100 h264_nvenc
>     Side data:
>       cpb: bitrate max/min/avg: 0/0/4000000 buffer size: 8000000 vbv_delay: -1
> Output #1, null, to 'pipe:':
>   Metadata:
>     encoder         : Lavf58.29.100
>     Stream #1:0: Video: h264 (h264_nvenc) (Main), cuda, 320x240 [SAR 1:1 DAR 4:3], q=-1--1, 1000 kb/s, 25 fps, 25 tbn, 25 tbc
>     Metadata:
>       encoder         : Lavc58.54.100 h264_nvenc
>     Side data:
>       cpb: bitrate max/min/avg: 0/0/1000000 buffer size: 2000000 vbv_delay: -1
> Output #2, null, to 'pipe:':
>   Metadata:
>     encoder         : Lavf58.29.100
>     Stream #2:0: Video: h264 (h264_nvenc) (Main), cuda, 320x240 [SAR 1:1 DAR 4:3], q=-1--1, 8000 kb/s, 25 fps, 25 tbn, 25 tbc
>     Metadata:
>       encoder         : Lavc58.54.100 h264_nvenc
>     Side data:
>       cpb: bitrate max/min/avg: 0/0/8000000 buffer size: 16000000 vbv_delay: -1
> [h264_nvenc @ 0x555ec3b3dbc0] OpenEncodeSessionEx failed: out of memory (10)
> Error initializing output stream 3:0 -- Error while opening encoder for output stream #3:0 - maybe incorrect parameters such as bit_rate, rate, width or height
> Conversion failed!
> ```
> 
> The NVENC patch verification failed but it was expected since I didn't apply the patch, but I was able to actually do the check sucessfuly.

work for me, thanks!
