### ISSUE TITLE
Invalid 1337-file

### ISSUE THREAD

**Issue by lazerpld** [keylase/nvidia-patch#55]
I have a ZOTAC 1050 TI GPU.
Windows 10 x64
Downloaded and installed the nvidia driver version 418.81
Rebooted.
Downloaded the patch tool version 1.9
Downloaded the 1337 file for 418.81

When trying to add the file to the tool, it sais the the 1337 file is invalid.
Am I doing something wrong?

**Comment by Snawoot** [comment]
Hi!

Please check your downloaded file size. It has to be about 62 bytes long.

If not, see step 3 of [this instruction](https://github.com/keylase/nvidia-patch/tree/master/win#step-by-step-guide) how to download files. Also downloading entire repo as ZIP archive worth trying if nothing helps.

**Comment by lazerpld** [comment]
Hi Snawroot. Im sorry for my ignorance. I have now got a 62 byte file. Thank you so much. I am very excited to try this out on my plex. Is it true that i need to perform a reinstallation of plex for this patch to work?

**Comment by Snawoot** [comment]
We have related to Plex discussion [here](https://github.com/keylase/nvidia-patch/issues/51). Guys achieved results with Plex on Linux, but I'm not sure if it is applicable to Windows. Probably if new Plex for Windows has under the hood ffmpeg with NVENC/NVDEC support, one can build similar wrapper with option enabling full HW support.
