### ISSUE TITLE
Window Artefacts - 1660 Super, Ubuntu 20.04,  515.57 drivers

### ISSUE THREAD

**Issue by peliopoulos** [keylase/nvidia-patch#550]
Window artefacts after I apply the patch (windows not clearing  when I switch apps or move windows)

1. bash ./patch.sh
2. close window, switch windows of move windows (occurs a few minutes after applying patch)

 - OS: Ubuntu 20.04
 - GPU model: GTS 1660 Super
 - Patch commit used: not sure, is it this one? d23260bdee7982be422071ab45e1bb11c8fe2daf 
 - Nvidia driver version: 515.57

Notes:
- The -c option shows that the driver is supported.
- When I remove the patch (applying the -r switch) window behaviour improves
- The card is brand new

**Comment by jailuthra** [comment]
Can someone else try and reproduce this issue?

I highly doubt graphics/window rendering pipeline has anything to do with changing a single conditional in the encode driver.

FWIW I've faced artefacts and window glitches on linux with nvidia drivers in general, even unpatched.

**Comment by reloxx13** [comment]
Even if it is caused by the patch, i dont think that we can do sth about it.     
Its more like something in nvidias code (or the window manager programm or the ubunut ui) acting stange when the limit is unlocked.

**Comment by peliopoulos** [comment]
I tried removing the patch and the artefacts still appear even with new drivers. I didn't realize what a hot mess nVidia drivers are on Linux.  Thanks for looking at my issue!
