### ISSUE TITLE
New driver support (version 516.93 Studio)

### ISSUE THREAD

**Issue by WoodburyMan** [keylase/nvidia-patch#552]
- Nvidia driver version: 516.93 Studio Driver
- GPU Model: RTX 3080 /  GTX 1050 Ti
- OS: Windows 11 / Windows 10
- I'm willing to participate in testing of new patch version

**Comment by jailuthra** [comment]
@WoodburyMan can you test if #555 removes the encoder limit for you? Steps [here](https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch#windows)
