### ISSUE TITLE
ERROR: cannot detect driver directory

### ISSUE THREAD

**Issue by ASOwnerYT** [keylase/nvidia-patch#560]
**Describe the bug**
When I run `sudo ./patch-fbc.sh` I get this error:
```
Detected nvidia driver version: 515.65.01
ERROR: cannot detect driver directory
```

**To Reproduce**
1. Clone the repository
2. Run `sudo ./patch-fbc.sh`
3. Get error

**Environment (please complete the following information):**
 - OS: Nobara 36 (based on Fedora 36)
 - GPU model: GTX 1050 (mobile)
 - Patch commit used: Latest on master branch (86e009af74a31c3d31e64fdc402e92b47090e550)
 - Nvidia driver version: 515.65.01

**Additional context**
Patching NVENC with `sudo ./patch.sh` seems to work perfectly fine, but patching NVFBC doesn't

**Comment by mpisat** [comment]
I also have the same issue when I use driver from ubuntu APT.

**Comment by monitor-ap** [comment]
Running into this too. Running Ubuntu 20.04 both patches report ERROR: cannot detect driver directory. Worked fine on a server with the exact same setup 2 days ago.

**Comment by JoeITCanuck** [comment]
Same issue as well, but on an older driver even! I am running Debian 11 w/GTX 1650

Detected nvidia driver version: 470.141.03
ERROR: cannot detect driver directory

**Comment by jailuthra** [comment]
Can someone check where fbc driver lib has moved to?

The script currently checks here:
https://github.com/keylase/nvidia-patch/blob/a8325ee950b1bdb5bb46b0607199134d8c718f53/patch-fbc.sh#L322-L327

**Comment by wael444** [comment]
```
/usr/lib/libnvidia-fbc.so -> libnvidia-fbc.so.1*
/usr/lib/libnvidia-fbc.so.1 -> libnvidia-fbc.so.515.65.01*
/usr/lib/libnvidia-fbc.so.515.65.01*
```

**Comment by ASOwnerYT** [comment]
Still having the same issue on the latest version of Nobara 37. Running patch.sh works but not patch-fbc.sh

**Comment by jailuthra** [comment]
Where is the .so file for nvfbc on your system?

**Comment by ASOwnerYT** [comment]
No idea

**Comment by ASOwnerYT** [comment]
> `find /lib /usr -name "*nvidia-fbc*"`...

That command doesn't return anything at all, looks like the nvfbc driver is missing on Nobara.
