### ISSUE TITLE
Question: Is it possible to use NvFBC with FFmpeg?

### ISSUE THREAD

**Issue by wael444** [keylase/nvidia-patch#564]
Hello,

My question is: Is it possible to use NvFBC with FFmpeg?

I already use NVENC with FFmpeg and x11grab, but do i need OBS for NvFBC capability?

**Comment by jailuthra** [comment]
I don't believe so. But please ask on ffmpeg forums, this is not the best place for generic queries about ffmpeg/nvfbc :)
