### ISSUE TITLE
Does the nvEncodeAPI64.dll have to be replaced again after each boot?

### ISSUE THREAD

**Issue by githubbapoopa** [keylase/nvidia-patch#572]
Does the nvEncodeAPI64.dll have to be replaced after each boot on Windows as stated here?:

https://forum.robotflow.ai/t/how-to-crack-nvidias-nvenc-video-encoding-sessions-limit/45

If so, why is there no info on the main page?

People patch the files in good faith and think it's all done....

**Comment by jailuthra** [comment]
Can you test if that is actually the case? Try applying patch, [test if session limit is removed](https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch) then reboot and test again.

I have not seen this behaviour before but I have not actually tested on windows since a while.

**Comment by reloxx13** [comment]
nooo, not needed after reboot.

The test is optional.

**Comment by jailuthra** [comment]
Added link to the test in win readme #575
