### ISSUE TITLE
New driver support (version 522.30-nsd)

### ISSUE THREAD

**Issue by cp3oDOTcom** [keylase/nvidia-patch#578]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: [522.30-nsd]
- GPU Model: [RTX 3090]
- OS: [Win10_x64]
- [x] I'm willing to participate in testing of new patch version

**Comment by jailuthra** [comment]
@cp3oDOTcom can you test if #579 removes the encoder limit for you?

https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch#windows

**Comment by cp3oDOTcom** [comment]
Works Great - Thank You So Much...

![C__WINDOWS_system32_cmd exe 11_1_2022 7_26_50 AM](https://user-images.githubusercontent.com/47932865/199232161-b9c011c7-3531-4117-b0b3-1bb1eca9accd.png)
