### ISSUE TITLE
Getting 504 during git clone. Unable to download patch 11/23/2022

### ISSUE THREAD

**Issue by dougbillings** [keylase/nvidia-patch#582]
Hello,

More of a notification than a question: I am getting a 504 during git clone. Unable to download patch 11/23/2022. 

path: git clone https://ipfs.io/ipns/Qmed4r8yrBP162WK1ybd1DJWhLUi4t6mGuBoB9fLtjxR7u nvidia-patch

**Comment by dougbillings** [comment]
used main site and it worked. mirror is down

**Comment by jailuthra** [comment]
I will be removing the mirror from the readme. The previous maintainer added it, and I don't plan to maintain it. If someone wants to volunteer with a new mirror please reach out.
