### ISSUE TITLE
New driver support (version Quadro 526.67)

### ISSUE THREAD

**Issue by cichy45** [keylase/nvidia-patch#585]
- Nvidia driver version: R525 U1 (526.67)
- GPU Model: Quadro P400
- OS: Windows 10 64bit

I would like to ask for update to include newest Quadro drivers. They are required for support of newest FFMPEG version. Newest drivers 472.84 supported by this patch will give following error in FFMPEG when trying to test if unlock was successful:

[h264_nvenc @ 000001f87fa2e740] Driver does not support the required nvenc API version. Required: 12.0 Found: 11.1
[h264_nvenc @ 000001f87fa2e740] The minimum required Nvidia driver for nvenc is 522.25 or newer
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

I can test the patch if someone would be kind enough to create it. Many thanks!

**Comment by jailuthra** [comment]
@cichy45 Can you test #586? Steps to confirm > 3 encode streams work are here https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch

If it works I'll merge it!

**Comment by cichy45** [comment]
@jailuthra I can confirm it is working. Thank you for this patch.
