### ISSUE TITLE
New driver support (version Studio 527.56)

### ISSUE THREAD

**Issue by SnowDrifterr** [keylase/nvidia-patch#595]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: [Studio 527.56]
- GPU Model: [3080ti]
- OS: [Win11]
- [yes] I'm willing to participate in testing of new patch version

**Comment by jailuthra** [comment]
Can you test the patch for 527.56 DCH that was merged yesterday?

It is the same version as the studio variant.
