### ISSUE TITLE
support other version?

### ISSUE THREAD

**Issue by deepch** [keylase/nvidia-patch#6]
you can add support 

 Driver Version: 396.26

**Comment by helldweller** [comment]
Added

**Comment by me-vlad** [comment]
patch also works for version 396.37

**Comment by keylase** [comment]
added 396.37 https://github.com/keylase/nvidia-patch/commit/5452435877f212e8fa249897b10af3be530e769b

**Comment by keylase** [comment]
added 396.37 https://github.com/keylase/nvidia-patch/commit/5452435877f212e8fa249897b10af3be530e769b
