### ISSUE TITLE
support for 474.14

### ISSUE THREAD

**Issue by testermania** [keylase/nvidia-patch#610]
Latest driver for 6x series.

https://us.download.nvidia.com/Windows/474.14/474.14-desktop-win10-win11-64bit-international-dch-whql.exe

**Comment by jailuthra** [comment]
Can you test if the patches in #614 remove the encoder limit for you?

Use these steps: https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch#windows

**Comment by testermania** [comment]
![Capture](https://user-images.githubusercontent.com/61498468/217221593-11d7ffbc-b62b-4059-b07c-dd452da86829.PNG)

**Comment by jailuthra** [comment]
Looks like an issue in the name of the dll nvcleanstall is using. Please raise a bug with them.

Can you please try with the manual patching steps?

**Comment by jailuthra** [comment]
Oh also looks like your FFmpeg version is too new that it has dropped support for the older nivida drivers. You might need to use some other application to test.
