### ISSUE TITLE
Patch won't install

### ISSUE THREAD

**Issue by The-NinthWave** [keylase/nvidia-patch#613]
System is Debian11
I had added the non-free repository and installed the NVIDIA drivers using 
`apt-install nvidia-driver` which installed 470.161.03

The drivers were working well in Docker containers but since it's a Quadro, I am limited to 3 stream.

Downloaded the drivers version patch and when I executed .run, I got this message.

All containers were stopper and the VM rebooted prior to execute the .run

```
ERROR: An NVIDIA kernel module 'nvidia-modeset' appears to already be loaded in your kernel.  This may be because it is in use (for example, by an X server, a CUDA
         program, or the NVIDIA Persistence Daemon), but this may also happen if your kernel was configured without support for module unloading.  Please be sure to
         exit any programs that may be using the GPU(s) before attempting to upgrade your driver.  If no GPU-based programs are running, you know that your kernel
         supports module unloading, and you still receive this message, then an error may have occurred that has corrupted an NVIDIA kernel module's usage count, for
         which the simplest remedy is to reboot your computer.

```

**Environment (please complete the following information):**
 - OS: Debian 11
 - GPU model: Quadro P600 (GP107)
 - Patch commit used: [e.g. 5b828a6d91a14e7bf4f93b31d220e7687ceb638c]
 - Nvidia driver version: 470.161.03

**Comment by The-NinthWave** [comment]
I have removed/purged the last driver and installed to the latest.
So one may discard this.

**Comment by jailuthra** [comment]
> Downloaded the drivers version patch and when I executed .run, I got this message.

I don't understand -- `.run` file is the driver installer. The patch can be applied once driver is installed using `patch.sh`

Closing this issue as your second comment seems to indicate you solved it.
