### ISSUE TITLE
driver 525

### ISSUE THREAD

**Issue by Khubaib21** [keylase/nvidia-patch#622]
Hello,

My question is: when ever i try to patch it . its says sudo./patch-fbc.sh: No such file or directory

any fixes? using pop os

**Comment by glitchsys** [comment]
Looks like you didn't put a space between sudo and ./patch-fbc.sh   you should be running "sudo ./patch-fbc.sh"  note the space in between.

If you are putting a space between, you should make sure you download the git repo first.

# cd /tmp
# wget https://github.com/keylase/nvidia-patch/archive/refs/heads/master.zip
# unzip master.zip
# cd nvidia-patch-master/
# sudo ./patch-fbc.sh
