### ISSUE TITLE
Original research English translation page leads to 404 error

### ISSUE THREAD

**Issue by OneOfMany07** [keylase/nvidia-patch#629]
[3rd party English translation](https://weekly-geekly.github.io/articles/262563/index.html)

On main page (Code link at top) is invalid/missing.  I was curious to read through it and I sadly don't speak or read Russian.

This isn't an urgent thing, but thought I'd record it in case it was easy for someone else to fix.

**Comment by jailuthra** [comment]
Wayback machine has them saved:

[Original Russian](https://web.archive.org/web/20201111201711/https://habr.com/en/post/262563/)

[English translation](https://web.archive.org/web/20190904221644/https://weekly-geekly.github.io/articles/262563/index.html)

I will update the README.md with these links.

**Comment by dumbasPL** [comment]
tip: remove the `text-align: center;` from `.page` using dev tools for better readability.
```js
document.querySelector('.page').style.textAlign = 'inherit';
```
