### ISSUE TITLE
New Patch Request: Patch version 515.105.01

### ISSUE THREAD

**Issue by ArtPiece55** [keylase/nvidia-patch#640]
Hello,

Just wanted to ask whether you are planning on adding support for the newly updated nvidia-driver-515 which is the version 515.105.01 and if so, approximate time frames?
PS. sorry if this was already asked, couldn't find any info.

**Comment by jailuthra** [comment]
Can you test if #641 removes the encoder limit for you?

Here are the steps https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch

**Comment by ArtPiece55** [comment]
> Can you test if #641 removes the encoder limit for you?
> 
> Here are the steps https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch

Thank you, yes, it works with patch 515.105.01.
Tested with GPU's: GTX 1660 ti, RTX 2060, and NVIDIA T600
