### ISSUE TITLE
Patch not working on recent Debian [Bullseye-470.182.03] repo update

### ISSUE THREAD

**Issue by TechInMD** [keylase/nvidia-patch#642]
**Describe the bug**
After installing the latest repository maintained package **Debian [Bullseye-470.182.03]** and applying the patch to the new driver installation, the install completes without error but the device can no longer create more than 3 simultaneous threads.

**To Reproduce**
(All steps performed with root privileges)
1. run ¨apt update;apt full-upgrade¨ 
2. complete installation of new driver packages (and reboot for gits and shiggles)
3. clone git (Patch commit used: [e8fd7f7fa0452d91b19d34eb8fcfafd445b665c0])
4. apply patch.sh
5. test with any thread configuration script that has more than 3 threads.

**Expected behavior**
To be able to perform rendering with more than 3 threads.

**Output listings**
I do not have the direct logs, but any test with more than 3 threads results in the ¨CreateBitstreamBuffer failed: out of memory (10)¨ error. I took note of the README information pertaining to this. I modified the test script with -surfaces 8 as suggested. It returned an error that the surfaces switch requires a value of 16 - 64. I adjusted the script accordingly to no avail. 

**Environment (please complete the following information):**
 - OS: [LMDE 5 **base: Debian 11.2 bullseye/Kernel: 5.10.0-22-amd64]**
 - GPU model: [GT 730 (ASUSTek GK208B)]
 - Patch commit used: [e8fd7f7fa0452d91b19d34eb8fcfafd445b665c0]
 - Nvidia driver version: [e.g. 470.182.03]

**Additional context**
I was able to revert to a recent Timeshift backup, restoring version 470.161.03, which is able to be patched without issue. Using the same thread tests (including the -surfaces 16 changes) I can create multiple threads with data sizes up to [512MB.] For more gits and shiggles I used -surfaces 64 and still got many threads.

Here is a copy of the command I am using for my tests:

ffmpeg -y -hwaccel cuda -hwaccel_output_format cuda \
-f lavfi -i testsrc -t 50 \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 1M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 2M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 4M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 8M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 16M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 32M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 64M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 128M -surfaces 64  -f null - \
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 512M -surfaces 64  -f null - \

**Comment by jailuthra** [comment]
Thanks for reporting the issue, looks like wrong bytecode was being changed in the merged patch in #631 

@TechInMD can you test if #643 fixes the issue?
