### ISSUE TITLE
nsd 531.61 ?

### ISSUE THREAD

**Issue by kirk29974** [keylase/nvidia-patch#651]
Hello,

My question is: ...
Good evening, you could also have the patch for the nvidia studio 531.61 drivers, at the moment there is only the one for the game drivers.
For information, the new driver game 532.03 was released yesterday

**Comment by jailuthra** [comment]
Hi @kirk29974 since the past few releases nvidia markets the same exact driver as DCH (game ready) also as NSD (studio driver)

You can try using the dch 531.61 patch with studio driver and test if session limit is removed (use the steps in the Wiki)

**Comment by kirk29974** [comment]
doesn't work, I had already done it but it gives me an error, while for the new game driver version I used the patch of the previous ones and it worked so for the 532.03 game drivers you can use the 531.79 one

**Comment by jailuthra** [comment]
What is the error you are facing?

I ran autopatch with the NSD driver:

`$ ./autopatch.py https://us.download.nvidia.com/Windows/531.61/531.61-desktop-win10-win11-64bit-international-nsd-dch-whql.exe`

Got the exact same patches as the ones already present for 531.61 DCH:
```diff
diff --git a/win/win10_x64/nsd_531.61/nvencodeapi.1337 b/win/win10_x64/nsd_531.61/nvencodeapi.1337
new file mode 100644
index 0000000..6134b3f
--- /dev/null
+++ b/win/win10_x64/nsd_531.61/nvencodeapi.1337
@@ -0,0 +1,6 @@
+>nvencodeapi.dll^M
+000000000003DD17:89->33^M
+000000000003DD18:45->C0^M
+000000000003DD19:08->89^M
+000000000003DD1A:85->45^M
+000000000003DD1B:C0->08
\ No newline at end of file
diff --git a/win/win10_x64/nsd_531.61/nvencodeapi64.1337 b/win/win10_x64/nsd_531.61/nvencodeapi64.1337
new file mode 100644
index 0000000..d4447c2
--- /dev/null
+++ b/win/win10_x64/nsd_531.61/nvencodeapi64.1337
@@ -0,0 +1,5 @@
+>nvencodeapi64.dll^M
+0000000000042FD1:8B->33^M
+0000000000042FD2:F0->C0^M
+0000000000042FD3:85->8B^M
+0000000000042FD4:C0->F0
\ No newline at end of file
```
