### ISSUE TITLE
Nvidia changed something in the win installer >= 536.23 

### ISSUE THREAD

**Issue by reloxx13** [keylase/nvidia-patch#662]
In the latest dch driver nvidia changed the path of nvencodeapi64.dll inside the installer

the filesize also lost about ~200mb. i downloaded it twice to confirm.

https://us.download.nvidia.com/Windows/536.23/536.23-desktop-win10-win11-64bit-international-dch-whql.exe

536.23-desktop-win10-win11-64bit-international-dch-whql.exe

> ERROR: Das System kann die angegebene Datei nicht finden.
> C:\Users\XXX\AppData\Local\Temp\tmpg2el3c_b\nvencodeapi64.dl_
> 
> 
> 
> System ERROR:
> Das System kann die angegebene Datei nicht finden.
> Traceback (most recent call last):
>   File "autopatch.py", line 159, in make_patch
>     f = expand(tgt, sevenzip=sevenzip)
>   File "autopatch.py", line 128, in expand
>     raise ExtractException("Subprocess returned non-zero exit code.")
> __main__.ExtractException: Subprocess returned non-zero exit code.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "autopatch.py", line 280, in <module>
>     main()
>   File "autopatch.py", line 276, in main
>     patch_flow(*params, direct=args.direct, stdout=args.stdout)
>   File "autopatch.py", line 218, in patch_flow
>     patch = make_patch(installer_file,
>   File "autopatch.py", line 159, in make_patch
>     f = expand(tgt, sevenzip=sevenzip)
>   File "autopatch.py", line 118, in __exit__
>     os.remove(self.name)
> FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'C:\\Users\\XXX\\AppData\\Local\\Temp\\tmpg2el3c_b\\nvencodeapi64.dl_'

**Comment by reloxx13** [comment]
ah they just renamed it from `nvencodeapi64.dl_` to `nvencodeapi64.dll`

**Comment by jailuthra** [comment]
Fixed by #665
