### ISSUE TITLE
New driver support (version 536.25)

### ISSUE THREAD

**Issue by need4swede** [keylase/nvidia-patch#669]
- Nvidia driver version: [536.25]
- GPU Model: [Quadro T600]
- OS: [Windows 11]
- [x] I'm willing to participate in testing of new patch version

Currently when running the FFMPEG test, I get the following error:
`Driver does not support the required nvenc API version. Required: 12.1 Found: 12.0`
`The minimum required Nvidia driver for nvenc is (unknown) or newer`

I am running the latest supported driver version [526.67]

I tried using the latest driver version [536.25]. but the patch tool gave me an offset error. I'm assuming this means that it's not working.

**Comment by jailuthra** [comment]
@need4swede can you test if you can apply patch at #670 cleanly.

And also if ffmpeg test works for you after it.

**Comment by need4swede** [comment]
Tested - it works. Thank you!

**Comment by need4swede** [comment]
Tested - it works. Thank you!
