### ISSUE TITLE
Error using a newer patch file

### ISSUE THREAD

**Issue by niklas2233** [keylase/nvidia-patch#686]
**Describe the bug**
Gives error when running the script about flakpak drivers

**To Reproduce**
1. Run bash ./patch.sh

**Expected behavior**
It would work
**Output listings**
Gives error:
./patch.sh: line 1: get_flatpak_driver_path: command not found
sha1sum: '"/."': No such file or directory
sha1sum: '"/."': No such file or directory
./patch.sh: line 1: payload:allShortcutsEnabled:false: command not found

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - GPU model: GTX 1070
 - Patch commit used: 2d31a42d8da0050a63d4f466ddd1244321e2ef52
 - Nvidia driver version: 535.54.03

**Additional context**
commit 84e433fbbe01a288f1a82e73c28ede1cdc30db00 does work but not the newest one

**Comment by PavlegG** [comment]
Were you able to resolve the error?
I got exactly the same error.

./patch.sh: line 1: get_flatpak_driver_path: command not found
sha1sum: '"/."': No such file or directory
sha1sum: '"/."': No such file or directory
./patch.sh: line 1: payload:allShortcutsEnabled:false: command not found

OS: Ubuntu Server 22.04 
GPU model: GTX 1050
Nvidia driver version: 525.125.06

**Comment by booze87** [comment]
same here!

**Comment by cfoo** [comment]
Same errors. Also on Ubuntu 22.04 server. 

Older version works fine.

**Comment by cfoo** [comment]
Download the file directly from the repo or use raw mode to grab the content of the shell script. The link from the README is broken.

**Comment by jailuthra** [comment]
Not able to reproduce with same driver version on Arch Linux:

```
jai@uda0497096:~/git/nvidia-patch(master)$ sudo bash ./patch.sh -f
WARNING: Flatpak flag enabled (-f), modifying ONLY the Flatpak driver.
Detected nvidia driver version: 535.54.03
Attention! Backup not found. Copying current libnvidia-encode.so to backup.
be5e586ddc57413ce57ea4fcfd72a1c9420b7bf6  /opt/nvidia/libnvidia-encode-backup/libnvidia-encode.so.535.54.03.flatpak
27be9a0802c59942648326549f271f291b6cd070  /var/lib/flatpak/runtime/org.freedesktop.Platform.GL.nvidia-535-54-03/x86_64/1.4/c0dedfdb960f7b8fcabf82952434386e78df17589c028184b787bf86368af724/files/lib/libnvidia-encode.so.535.54.03
Patched!
```

I don't see a reason why it fails on Ubuntu, still will keep this open for a few more weeks in case somebody wants to send a patch.

**Comment by jailuthra** [comment]
Not able to reproduce with same driver version on Arch Linux:

```
$ sudo bash ./patch.sh -f
WARNING: Flatpak flag enabled (-f), modifying ONLY the Flatpak driver.
Detected nvidia driver version: 535.54.03
Attention! Backup not found. Copying current libnvidia-encode.so to backup.
be5e586ddc57413ce57ea4fcfd72a1c9420b7bf6  /opt/nvidia/libnvidia-encode-backup/libnvidia-encode.so.535.54.03.flatpak
27be9a0802c59942648326549f271f291b6cd070  /var/lib/flatpak/runtime/org.freedesktop.Platform.GL.nvidia-535-54-03/x86_64/1.4/c0dedfdb960f7b8fcabf82952434386e78df17589c028184b787bf86368af724/files/lib/libnvidia-encode.so.535.54.03
Patched!
```

I don't see a reason why it fails on Ubuntu, still will keep this open for a few more weeks in case somebody wants to send a patch.

**Comment by jailuthra** [comment]
@cfoo can you point me to which link in README.md is broken?

**Comment by cfoo** [comment]
Sorry, not broken. If you mistakenly copied the link [NVENC patch](https://github.com/keylase/nvidia-patch/blob/master/patch.sh) listed on the main repo and use wget to grab it. You'll have a broken file and exact errors as indicated by OP. 

There is nothing wrong with the patch.sh file. It's the method in which people are downloading them that is wrong.

**Comment by Grand-Cherokee** [comment]
> Download the file directly from the repo or use raw mode to grab the content of the shell script. The link from the README is broken.

Confirmed. patch.sh only works if you right click "save link as" on raw file.
---the other (wrong, erroneous) way produces a 1 line file that begins with {"payload":.........blahblah..etc....
