### ISSUE TITLE
New driver support (version 535.86.10) and (version 535.98)

### ISSUE THREAD

**Issue by nichols89ben** [keylase/nvidia-patch#687]
- Nvidia driver version: 535.86.10
- GPU Model: GTX 1660
- OS: Ubuntu 22.04.2
- I'm willing to participate in testing of new patch version

**Comment by timsainb** [comment]
It looks like the driver isn’t hosted yet as in 535.86.05 https://www.nvidia.com/download/driverResults.aspx/209261/en-us/

**Comment by nichols89ben** [comment]
> It looks like the driver isn’t hosted yet as in 535.86.05 https://www.nvidia.com/download/driverResults.aspx/209261/en-us/

Yeah im not sure why, I noticed that to. But when my kernal updated this week it bumped the driver up too. It does look posed here though. 

https://github.com/NVIDIA/open-gpu-kernel-modules

**Comment by a0s** [comment]
Its already present at http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/

**Comment by pilonull** [comment]
Looks like there is now driver 535.98

https://www.nvidia.com/Download/driverResults.aspx/210317/en-us/
