### ISSUE TITLE
535.104.05 patches not actually altering the driver

### ISSUE THREAD

**Issue by mwsduelle** [keylase/nvidia-patch#694]
**Describe the bug**
535.104.05 patch/patch-fbc doesn't actually change the files for me

**Expected behavior**
NVENC streams uncapped, NvFBC enabled

**Output listings**
```
Detected nvidia driver version: 535.104.05
08e29ec86fcc6ed5f6e7d3731681cd0ca046f2be  /opt/nvidia/libnvidia-encode-backup/libnvidia-encode.so.535.104.05
08e29ec86fcc6ed5f6e7d3731681cd0ca046f2be  /usr/lib64/libnvidia-encode.so.535.104.05
Patched!
```

```
Detected nvidia driver version: 535.104.05
a3ef646c70b819d496ba94447586726d38d86030  /opt/nvidia/libnvidia-fbc-backup/libnvidia-fbc.so.535.104.05
a3ef646c70b819d496ba94447586726d38d86030  /usr/lib64/libnvidia-fbc.so.535.104.05
Patched!
```

Trying to force NvFBC in Sunshine results:
```
[2023:08:26:19:03:57]: Info: Sunshine version: 0.20.0
[2023:08:26:19:03:57]: Warning: Failed to create system tray
[2023:08:26:19:03:57]: Error: Unable to initialize capture method
[2023:08:26:19:03:57]: Error: Platform failed to initialize
[2023:08:26:19:03:57]: Info: Trying encoder [nvenc]
[2023:08:26:19:03:58]: Info: Encoder [nvenc] failed
[2023:08:26:19:03:58]: Error: Couldn't find any working encoder matching [nvenc]
```

**Environment (please complete the following information):**
 - OS: Garuda Linux 
 - GPU model: NVIDIA GeForce RTX 2070 SUPER Mobile / Max-Q
 - Patch commit used: e800f66a18dcb2af3cfc2a505d7a582536682002
 - Nvidia driver version: 535.104.05

**Additional context**
I did a diff check and md5sum check and the files are the same.

**Comment by jailuthra** [comment]
can't reproduce.

the patch bytecode looks correct to me (i checked the binary) - and it applies on my system leading to different md5sum hashes on the backup v/s installed library.
