### ISSUE TITLE
Silent code for windows ffmpeg 10 streams 

### ISSUE THREAD

**Issue by wazerstar** [keylase/nvidia-patch#70]
Hello,
Wanted to have the bat file for windows with doing the ffmpeg trick for 10 streams with null silent and without popup.

Here's a simple autoit code for if anybody wants.

compile it and make sure you add ffmpeg to the dir of ffmpegNull10StreamsSilent.exe

```
#Region ;**** Directives created by AutoIt3Wrapper_GUI ****
#AutoIt3Wrapper_Outfile_x64=ffmpegNull10StreamsSilent.exe
#AutoIt3Wrapper_UseX64=y
#EndRegion ;**** Directives created by AutoIt3Wrapper_GUI ****

#include <WinAPIFiles.au3>
$ffmpegCMD = ("-y -f lavfi -i nullsrc=s=256x256:d=5 -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null - -c:v h264_nvenc -f null -")
run(@scriptdir & "\" & "ffmpeg.exe" & " " & $ffmpegCMD,@ScriptDir, @SW_HIDE, $STDERR_CHILD+$STDOUT_CHILD)
```

**Comment by Snawoot** [comment]
Thank you for sharing this! I'll keep this issue open and pinned until we'll have dedicated and fast replacement for ffmpeg to do this job.

**Comment by Snawoot** [comment]
Adding some context: this code is silent replacement for [this](https://github.com/keylase/nvidia-patch/tree/master/win#d3d-encoding-sessions) recipe.
