### ISSUE TITLE
New driver support (version 535.104.12)

### ISSUE THREAD

**Issue by Nostradamus1973** [keylase/nvidia-patch#704]
**Please provide details about your environment (please complete the following information)**

Good morning,

- Nvidia driver version: 535.104.12
- GPU Model: GTX 1650
- OS: Kubuntu 23.04
- [x] I'm willing to participate in testing of new patch version

Thank you and have a nice day.

**Comment by JustPlainGarak** [comment]
Nvidia driver version: 535.104.12
    GPU Model: Quadro P400
    OS: Rocky Linux 8
    I'm willing to participate in testing of new patch version

**Comment by Nostradamus1973** [comment]
Good morning @JustPlainGarak,

 I see you're here for the same reason as me. The last time this happened, they presented me with a sample to try and verify and within a few days of filing an issue it was fixed, I guess this time is different.
To avoid this issue, have you downgraded your version to one supported by the patch? I'm seriously thinking about doing that until this is resolved.

Have a great day.

**Comment by jailuthra** [comment]
@Nostradamus1973 can you test the PR #703?
