### ISSUE TITLE
New driver support (version 537.72 Vulkan Beta)

### ISSUE THREAD

**Issue by Koekieezz** [keylase/nvidia-patch#715]
- Nvidia driver version: 537.72 Vulkan Beta
- GPU Model: RTX 3060Ti
- OS: Win 11 22H2
- [x] I'm willing to participate in testing of new patch version

**Comment by jailuthra** [comment]
@Koekieezz can you test if #716 fixes the issue for you? 

Steps to test are [in the wiki](https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch#windows)
