### ISSUE TITLE
New driver support (version NFB 545.29.02)

### ISSUE THREAD

**Issue by PartTheSeas** [keylase/nvidia-patch#719]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: [545.29.02]
- GPU Model: [RTX 3090]
- OS: [Manjaro unstable branch/Arch]
- [x] I'm willing to participate in testing of new patch version: Definitely

Hey there guys, I'm not sure if you patch NFB drivers from Nvidia, but if you do I'd love to test and run those. The currently latest version is NFB version 545.29.02.

If you happen to find the time, of course!

Cheers guys and have a great day! :100:

**Comment by jailuthra** [comment]
@PartTheSeas can you test if #721 removes the limits for you?
Steps to test are [in the wiki](https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch#linux)

**Comment by PartTheSeas** [comment]
@jailuthra Wow thank you for such a quick response! I wasn't expecting that. Confirmed working for me! Thank you so much!

Just as a hint, there has been an error printed, but the patch went through still (Not sure if it's interesting for you). ffmpeg tested as well, no errors, but:

```
sudo bash ./patch.sh                                                                                 
[sudo] Passwort für donatus: 
Detected nvidia driver version: 545.29.02
./patch.sh: Zeile 285: [[: 545.29: Syntaxfehler: Ungültiger arithmetischer Operator. (Fehlerverursachendes Zeichen ist ".29").
libnvidia-encode.so
Attention! Backup not found. Copying current libnvidia-encode.so to backup.
82b15502dcde49dfdba62b33c348e92821629538  /opt/nvidia/libnvidia-encode-backup/libnvidia-encode.so.545.29.02
c9667da8ee484a472b43d6b5a14f4d7273d8a689  /usr/lib64/libnvidia-encode.so.545.29.02
Patched!

```
Sorry for not printing it in English. It says "Syntax error: Invalid arithmetic Operator. (Error causing sign is".29")."

**Comment by jailuthra** [comment]
Thanks @PartTheSeas - and yes that error print is useful, looks like I missed an edge case in recent changes to the script. Will fix, thanks!
