### ISSUE TITLE
New driver support (version 536.40)

### ISSUE THREAD

**Issue by Soiltasun** [keylase/nvidia-patch#727]
- Nvidia driver version: 536.40
- GPU Model: GeForce RTX 4060 OC Low Profile 8G
- OS: Win10
- [x] I'm willing to participate in testing of new patch version, if it's eligible

Looking to purchase this low profile card for Jellyfin in a SFF unit. Appreciate to know if this version can either be supported or if an existing driver will work.

Attached is [ListDevices.txt](https://github.com/keylase/nvidia-patch/files/13351467/ListDevices.txt) from driver '536.40-desktop-win10-win11-64bit-international-dch-whql.exe' FWIW

**Comment by jailuthra** [comment]
The patch already supports driver version 536.40, check the win/README.md file

**Comment by Soiltasun** [comment]
TY
