### ISSUE TITLE
New driver support (version 512.36)

### ISSUE THREAD

**Issue by AnrayAnn** [keylase/nvidia-patch#735]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version:  512.36
- GPU Model: GTX 3080 Laptop
- OS: Windows 11 22H2
- I'm willing to participate in testing of new patch version

**Comment by jailuthra** [comment]
@AnrayAnn do you have a download link for that driver version?

**Comment by AnrayAnn** [comment]
I only have a link from my laptop service supporter
https://newdriverdl.lenovo.com.cn/newlenovo/alldriversupload/101181/nvidiavga-2GY706AFB98XH1C0.exe
I also have the file

**Comment by jailuthra** [comment]
@AnrayAnn no plans to support custom OEM drivers. Please update to the latest Nvidia drivers from https://www.nvidia.com/en-us/geforce/news/the-medium-game-ready-driver/

If you cannot upgrade at all, I recommend trying out the driver patch in the repo for one of the existing 512.xx versions.

**Comment by AnrayAnn** [comment]
I see Thanks.
