### ISSUE TITLE
patch.sh not working in linuxserver.io unRAID nvidia release?

### ISSUE THREAD

**Issue by cannonf0dder** [keylase/nvidia-patch#75]
Hopefully someone here can assist me. I installed linuxserver.io unRAID nvidia distro RC6.7.0 rc4. I can see, by running nvidia-smi, that HW encoding is happening. After I did that, I was informed of this patch to remove the 2 stream limit.

When running the patch, which is located in /mnt/user, I get the following output:

Linux 4.19.23-Unraid.
Last login: Sat Mar 9 12:11:43 -0600 2019 on /dev/pts/0.
root@XXXXXXX:~# cd /mnt/user
root@XXXXXXX:/mnt/user# bash ./patch.sh
./patch.sh: line 2: $'\r': command not found
: invalid option nameet: pipefail
root@XXXXXXX:/mnt/user#

Is there something I need to modify in the script to get this to work with the linuxserver.io build? Perhaps the path to the driver or driver backup?

Any help would be appreciated. I've attached the patch.sh file that I'm using, but renamed to txt.
[patch.txt](https://github.com/keylase/nvidia-patch/files/2948714/patch.txt)

**Comment by Snawoot** [comment]
Hi!

First issue: your file contains CRLF line terminators. It looks like it was not just renamed, but re-saved with something like notepad.exe on Windows. Please use file with proper (original) contents.

**Comment by cannonf0dder** [comment]
That's exactly what the problem was! Thank you!
