### ISSUE TITLE
535.43.24 support (AV1 enc/dec)

### ISSUE THREAD

**Issue by TimCook1** [keylase/nvidia-patch#754]
Nvidia has started releasing beta drivers that support AV1 enc/dec support.  The latest version is 535.43.24, would be great to be able to unlock streams on these versions.

https://developer.nvidia.com/vulkan-driver

- Nvidia driver version: 535.43.24
- GPU Model: -
- OS: Ubuntu 22.04.3
- [x] I'm willing to participate in testing of new patch version

**Comment by jailuthra** [comment]
@TimCook1 Nvidia released 535.43.25 immediately afterwards, so I have patched that (same patch should work on older driver too I guess).

Can you test it unlocks the encoder for you? Steps are [in the wiki](https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch#linux)

**Comment by TimCook1** [comment]
root@server1:/home/user/nvidia# ./patch.sh
Detected nvidia driver version: 535.43.24
libnvidia-encode.so
Error: Could not find bytes '\xe8\xa5\x9e\xfe\xff\x85\xc0\x41\x89\xc4' to patch in '/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.535.43.24'.


I believe these drivers are a unique branch for Vulkan support so they may differ from the mainline.

**Comment by TimCook1** [comment]
That worked with .25

Detected nvidia driver version: 535.43.25
libnvidia-encode.so
Attention! Backup not found. Copying current libnvidia-encode.so to backup.
585b6b05499ca35b41e8aa2e571ef51a26acb677  /opt/nvidia/libnvidia-encode-backup/libnvidia-encode.so.535.43.25
84a17cfcd21e1a1e77be49bf4657af13169de645  /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.535.43.25
Patched!
