### ISSUE TITLE
New driver support (version 550.54.14)

### ISSUE THREAD

**Issue by turtle-ttl-ltd** [keylase/nvidia-patch#763]
Nvidia driver version: 550.54.14
GPU Model: GTX 1080Ti
OS: Debian 12
[x] I'm willing to participate in testing of new patch version.

This is the Nvidia driver bundled in with CUDA 12.4

**Comment by PartTheSeas** [comment]
Was about to place the same request :+1:

**Comment by mklooss** [comment]
it is not the same as before :/

Error: Could not find bytes '\xe8\x35\x54\xfe\xff\x85\xc0\x41\x89\xc4' to patch in '/usr/lib/x86_64-linux-gnu/nvidia/current//libnvidia-encode.so.550.54.14'.

**Comment by PartTheSeas** [comment]
So a patch is not possible? :fearful:

**Comment by mklooss** [comment]
patching would be possible, but not the easy way

**Comment by PartTheSeas** [comment]
Damn! I hope somebody can even do it the hard way :grin: Would be awful if this great patch cannot be applied anymore. Using Plex, Emby and Tdarr without this patch is simply not possible :(

**Comment by PartTheSeas** [comment]
Awesome :heart_eyes: Thank you guys :partying_face:
