### ISSUE TITLE
What is the patch 551.68 DCH (Hotfix) for when Nvidia version is 551.76?

### ISSUE THREAD

**Issue by Anuruddha094** [keylase/nvidia-patch#770]
Hi,

What is the patch 551.68 DCH (Hotfix) for. Nvidia didn't release any driver with that version number. Did you mean 551.76? I guess this is a typo. Please confirm.

Thank you

**Comment by djmaniac** [comment]
No - this is correct - 551.68 DCH (Hotfix) is official:
https://nvidia.custhelp.com/app/answers/detail/a_id/5525
https://international.download.nvidia.com/Windows/551.68hf/551.68-desktop-notebook-win10-win11-64bit-international-dch.hf.exe
