### ISSUE TITLE
Question: nvenc restriction on 550.67 gone?

### ISSUE THREAD

**Issue by detiam** [keylase/nvidia-patch#776]
Today I update the driver version to 550.67, try https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch without patch, and it just keeps running without any error, is the nvenc restriction on 550.67 gone?

**Comment by alansari** [comment]
nvenc concurrent streams has been officially increased to 8 last i checkd.  NvFBC is still locked behind a driver level restriction

**Comment by drat0s** [comment]
> nvenc concurrent streams has been officially increased to 8 last i checkd.


This is correct, they were increased to 8 somewhere around the end of January 2024.   
https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new
