### ISSUE TITLE
Does it compatible with PPA driver?

### ISSUE THREAD

**Issue by damdinsharav** [keylase/nvidia-patch#78]
Just discovered this wonderful project.

I wish I know earlier.

I see that it's suggesting to compile nvidia driver from source but does it compatible with 

https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa ?

**Comment by Snawoot** [comment]
Hi!

Yes, currently patch matches driver version in PPA and compatible with it. But it is not guaranteed patch will be always up to date to latest driver. Therefore, unlock solution may become unavailable to you after another regular PPA package upgrade. Also you have to re-apply patch after every package update or reinstall.
