### ISSUE TITLE
New driver support 535.171.04

### ISSUE THREAD

**Issue by JuniperMS** [keylase/nvidia-patch#783]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 535.171.04
- GPU Model: P1000
- OS: Ubuntu 22.04.4 LTS
- [x] I'm willing to participate in testing of new patch version!

**Comment by pilonull** [comment]
Man, I just want to say... nvidia ubuntu drivers drive me batshit crazy. I have tried pinning and everything else to try to prevent the nvidia driver from auto-updating on my ubuntu 22.04.4 VM... but it always just updates itself whenever it feels like it. True pain in the ass.

**Comment by JuniperMS** [comment]
Me, too. I used to edit the patch.sh file in nano and add the driver version number at the end of the others, but it doesn't seem to work anymore. :(

**Comment by zackoch** [comment]
@JuniperMS I just tested adding `["535.171.04"]='s/\xe8\xa5\x9f\xfe\xff\x85\xc0\x41\x89\xc4/\xe8\xa5\x9f\xfe\xff\x29\xc0\x41\x89\xc4/g'` and the patch for multiple streams appears to work fine.

**Comment by JuniperMS** [comment]
Maybe I had a typo in my attempt yesterday. I just added the exact line above and it worked. I feel silly now.
