### ISSUE TITLE
cp: cannot stat ‘/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.390.87’: No such file or directory

### ISSUE THREAD

**Issue by montasar8** [keylase/nvidia-patch#79]
i am trying to install the driver in a fresh ubuntu 14 with ppa driver 390.87 but it fails backing up 
cp: cannot stat ‘/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.390.87’: No such file or directory
 anyone have the same problem ?

**Comment by Snawoot** [comment]
Hi!

Please post output of following commands: `nvidia-smi` and `uname -m`

**Comment by montasar8** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:02:00.0  On |                  N/A |
|  0%   42C    P8     6W / 151W |    342MiB /  8118MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1070    Off  | 00000000:03:00.0 Off |                  N/A |
|  0%   41C    P8     6W / 151W |      2MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1070    Off  | 00000000:A1:00.0 Off |                  N/A |
|  0%   43C    P8     7W / 151W |      2MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1446      G   /usr/lib/xorg/Xorg                           195MiB |
|    0      2552      G   compiz                                       145MiB |

4.4.0-142-generic #168~14.04.1-Ubuntu SMP Sat Jan 19 11:26:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kotuk** [comment]
check here: https://github.com/kotuk/nvidia-patch/blob/master/patch.sh fixed for your system

**Comment by montasar8** [comment]
thanks , that solved the problem

**Comment by Snawoot** [comment]
Full-featured fix merged via #80
