### ISSUE TITLE
run error:  ./patch.sh: 8: Syntax error: newline unexpected

### ISSUE THREAD

**Issue by rockmyhouse** [keylase/nvidia-patch#790]
**Describe the bug**
First time running patch and it errors when running the command:
./patch.sh: 8: Syntax error: newline unexpected
The file was run with privileges.

**To Reproduce**
1.   myname@nas2:~/nvidia_driver$ sudo chmod +x patch.sh
2.   myname@nas2:~/nvidia_driver$ sudo ./patch.sh

**Expected behavior**
clean execution of patch script.

**Output listings**
myname@nas2:~/nvidia_driver$ sudo ./patch.sh
./patch.sh: 8: Syntax error: newline unexpected

**Environment (please complete the following information):**
 - OS:  Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-105-generic x86_64)
 - GPU model: GeForce GTX 1050 Ti
 - Patch commit used: d56fe0c8aeb306238e63ae535251f181
 - Nvidia driver version: 535.171.04

**Additional context**
I'm a novice linux user and may be doing this wrong :)

**Comment by jailuthra** [comment]
Can you do `cat patch.sh` to make sure your patch was downloaded correctly.

Some folks in the past have downloaded the html page instead of raw file from github :)
