### ISSUE TITLE
Add support for rtx cards. Driver version 411.63  

### ISSUE THREAD

**Issue by Krypto12** [keylase/nvidia-patch#8]

**Comment by Snawoot** [comment]
Hello, @Krypto12!

What is your OS?

**Comment by montasar8** [comment]
is it possible to add support for rtx cards 411.63 . ?

**Comment by Snawoot** [comment]
@montasar8 as far as I know latest released driver for Linux has version 410.66. Probably you are talking about windows driver. Some clues about patching windows driver can be found in [this repo](https://github.com/Matviy/nvidia-NVENC-multi-session-patch).

**Comment by montasar8** [comment]
yes i mean driver 410 for ubuntu desktop 
the rtx cards will not work with driver 396

**Comment by Snawoot** [comment]
@montasar8 There are still unaccepted [pull request](https://github.com/keylase/nvidia-patch/pull/10) from @ilyaevseev which adds support for 410.48 driver. I think it is worth to try if 410.48 byte sequence will work for 410.66. Or just use 410.48 driver.

**Comment by montasar8** [comment]
> @montasar8 There are still unaccepted [pull request](https://github.com/keylase/nvidia-patch/pull/10) from @ilyaevseev which adds support for 410.48 driver. I think it is worth to try if 410.48 byte sequence will work for 410.66. Or just use 410.48 driver.

it works with 410.73

**Comment by Snawoot** [comment]
Resolved by #11
