### ISSUE TITLE
New driver version v555.52.04 Linux

### ISSUE THREAD

**Issue by sthgi** [keylase/nvidia-patch#801]
- Nvidia driver version: [e.g. v555.52.04]
- GPU Model: [Quadro T1000]
- OS: [Linux]
- [x] I'm willing to participate in testing of new patch version

**Comment by mrbaiwei** [comment]
> On the 550 branch, _550.90.07_ also arrived: https://www.nvidia.com/Download/driverResults.aspx/226768/en-us/
> 
> I hope the OP doesn't mind me hijacking this issue. I just thought that all the new Linux releases may well be handled all at once.

Same issue. pls support this version.

**Comment by jailuthra** [comment]
#800 fixes this
