### ISSUE TITLE
Patch fails when attempting to use with vMix

### ISSUE THREAD

**Issue by avsoundguy** [keylase/nvidia-patch#81]
Attempting to to use this patch for use with vMix software (on Windows 10 64-bit) but when trying to activate more than 2 NVENC sessions it fails. Is there any possibility of getting the patch to work with vMix?  

vMix is a Live Streaming and Recording software and vMix includes some open source libraries.   
FFMPEG 
This software uses code of FFmpeg licensed under the LGPLv2.1 and its source can be downloaded here  FFmpeg was compiled using the following command line: ./configure --toolchain=msvc --enable-shared --disable-static --arch=amd64 --enable-zlib ./make  

FFmpeg Command Line 
This software utilises the FFmpeg command line software licensed under the GPLv3. Its source can be downloaded here The command line software incorporates x264 and libfaac, the source code and licenses for both can be found in the download above.

**Comment by Snawoot** [comment]
Hi!

It seems vMix uses 32-bit version of ffmpeg even on 64bit platforms. Please read README carefully and try [this workaround](https://github.com/keylase/nvidia-patch/tree/master/win#d3d11-and-32-bit-apps-encoding-sessions) for 32-bit apps.

**Comment by avsoundguy** [comment]
Ran the NvencSessionLimitBump.exe file and it works like a charm, the 2 encoder limit is removed for vMix, I also used RunAsService to add the "bump exe" as a service and it works very well to keep it loaded during reboots.  Thanks for all the work being done here.
