### ISSUE TITLE
New driver support (version  550.90.07) - Required for Manjaro

### ISSUE THREAD

**Issue by Abvit-eve** [keylase/nvidia-patch#810]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 550.90.07 
- GPU Model: GTX 4080
- OS: Manjaro 24.0.2
- [x] I'm willing to participate in testing of new patch version

This is the current version set my the Manjaro automated NVIDIA driver tools and it's not supported by the patch

**Comment by jailuthra** [comment]
This is already fixed in #809
Please check before creating issues
