### ISSUE TITLE
New driver support (version 535.183.01)

### ISSUE THREAD

**Issue by gcormier** [keylase/nvidia-patch#811]
- Nvidia driver version: 535.183.01
- GPU Model: GTX 2060 6gb
- OS: Ubuntu 22.04 LTS
- [x] I'm willing to participate in testing of new patch version

**Comment by jailuthra** [comment]
@gcormier can you test if #812 removes the limit for you?

you can refer to the [wiki](https://github.com/keylase/nvidia-patch/wiki/Verify-NVENC-patch#linux) for the ffmpeg command to test encoding 9 sessions (nvidia limits to 8 without the patch)

**Comment by gcormier** [comment]
Confirmed working! Thanks for the quick response.
