### ISSUE TITLE
Updated Win_1337_Apply_Patch Now Supports DLL Unlocking for Windows Driver Version 556.12 and Above

### ISSUE THREAD

**Issue by ramhaidar** [keylase/nvidia-patch#828]
**Description:**
For those encountering issues with unlocking DLL files while patching NVIDIA drivers using the `Win_1337_Patch` tool, an updated version is now available. This update resolves the problem of access denied errors during the patching process.

**Unlock DLL Explanation:**
"Unlocking DLL" in this context refers to the process of removing system-level protections that prevent modification of certain DLL files, such as `nvEncodeAPI.dll` and "nvEncodeAPI64.dll". These protections can include file ownership and permission settings that restrict changes to the file. The updated patching tool can modify these settings to allow the necessary changes to be made.

**Access Denied Issue:**
As detailed in [issue #795](https://github.com/keylase/nvidia-patch/issues/795#issuecomment-2225573296), the "access denied" error occurs due to the ownership and permission settings on these files. By default, these DLL files are owned by "TrustedInstaller," and the permissions set do not allow for modifications by standard administrative accounts. The updated patch tool addresses this by changing the file ownership to "Administrators" and granting full control permissions, allowing the necessary modifications to proceed.

**Update Details:**
The updated version (v2.0) of `Win_1337_Apply_Patch` is available in my fork [ramhaidar/Win_1337_Apply_Patch](https://github.com/ramhaidar/Win_1337_Apply_Patch). This version includes support for unlocking necessary DLL files, ensuring a smooth patching process. This tool works on NVIDIA driver version 556.12 and above, which is the version where the “access denied” problem occurs.

![sshot-20240728-114120](https://github.com/user-attachments/assets/c4df2a61-2a09-457c-81a7-28b05532cab3)

**Reason for Fork Release:**
The update has been implemented in the main repository [Deltafox79/Win_1337_Apply_Patch](https://github.com/Deltafox79/Win_1337_Apply_Patch), but the official build hasn't been released yet. The repository owner, [@Deltafox79](https://github.com/Deltafox79), might be occupied and hasn't had the chance to compile and release the new build. Meanwhile, users can access the updated version from my fork.

**Alternative Patch Method:**
For users who prefer to use a PowerShell script for patching, I have also provided a script in the repository [ramhaidar/Win_1337_Apply_Patch_Powershell](https://github.com/ramhaidar/Win_1337_Apply_Patch_Powershell). This script provides similar functionality to the GUI tool.

**Acknowledgements:**
Special thanks to [@VorlonCD](https://github.com/VorlonCD) for sharing the workaround that greatly helped in addressing this issue.

**Next Steps:**
You can download and use the GUI version from my fork or the PowerShell script until the official release is updated. Feel free to reach out if there are any questions or issues!

**Comment by Jaybonaut** [comment]
Note to users:  grab the 2.1 version, the 2.0 version did not work.

**Comment by ramhaidar** [comment]
> Note to users: grab the 2.1 version, the 2.0 version did not work.

yes, I apologize, there was some code that caused the “Unlock DLL” feature to not work in version 2.0 and I have fixed it in version 2.1, enjoy.

**Comment by jailuthra** [comment]
@ramhaidar thanks for fixing the patch application tool on windows, and the powershell script.

Can you send a PR updating the documentation to point to your repository and script?
