### ISSUE TITLE
New driver support (version 550.107.02)

### ISSUE THREAD

**Issue by ACheshirov** [keylase/nvidia-patch#829]
- Nvidia driver version: 550.107.02
- GPU Model: RTX 3070
- OS: Ubuntu 22.04.4 LTS

**Comment by MrKindlyWolf** [comment]
same issue here

Nvidia driver version: 550.107.02
GPU Model: RTX 4060
OS: Proxmox

**Comment by smitty-nieto** [comment]
Same here. Just bumped to 550.107.02. Could use a new patch :)
