### ISSUE TITLE
New driver support (version 535.183.06)

### ISSUE THREAD

**Issue by nichols89ben** [keylase/nvidia-patch#836]
- Nvidia driver version: 535.183.06
- GPU Model: NVIDIA GeForce GTX 1660 SUPER
- OS: Ubuntu 22.04 jammy
- [x] I'm willing to participate in testing of new patch version

**Comment by Gelmo** [comment]
@nichols89ben I can only find 535.183.06 in aarch64 (https://international.download.nvidia.com/tesla/535.183.06/NVIDIA-Linux-aarch64-535.183.06.run), not amd64. Can you point me to the download for the amd64 driver, or are you using aarch64?

**Comment by BrokenR3C0RD** [comment]
>  Can you point me to the download for the amd64 driver, or are you using aarch64?
@Gelmo 535.183.06 on AMD64 can be found here: https://us.download.nvidia.com/tesla/535.183.06/NVIDIA-Linux-x86_64-535.183.06.run
This is currently the version of the NVIDIA driver provided by `nvidia-kernel-dkms` on Debian `backports` and `unstable`: https://packages-picconi.debian.org/bookworm-backports/nvidia-kernel-dkms

**Comment by BrokenR3C0RD** [comment]
Not sure how to determine the NvFBC patches (as I don't use NvFBC), but adding this to the patch list worked for me:
```
["535.183.06"]='s/\xe8\xa5\x9f\xfe\xff\x85\xc0\x41\x89\xc4/\xe8\xa5\x9f\xfe\xff\x29\xc0\x41\x89\xc4/g'
```

**Comment by Gelmo** [comment]
Thanks @BrokenR3C0RD I downloaded it and confirm that the search/replace phrase which worked for the rest of the 535 series works for FBC as well. Creating a PR
