### ISSUE TITLE
New driver support (version 560.35.03)

### ISSUE THREAD

**Issue by johnthomas00** [keylase/nvidia-patch#839]
- Nvidia driver version: 560.35.03      CUDA Version: 12.6
- GPU Model: NVIDIA GeForce RTX 3070 Ti
- OS: Debian GNU/Linux 12 (bookworm)
- [x] I'm willing to participate in testing of new patch version

Repo: https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/
Driver: https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/nvidia-driver_560.35.03-1_amd64.deb

**Comment by PartTheSeas** [comment]
+1'ing this :)

**Comment by PartTheSeas** [comment]
Awesome! The Nvidia patch worked perfectly for me.

However, it somehow didn't work for my flatpak drivers, which printed:

```
sudo bash ./patch.sh -f                                                             
WARNING: Flatpak flag enabled (-f), modifying ONLY the Flatpak driver.
Detected nvidia driver version: 560.35.03
libnvidia-encode.so
grep: /var/lib/flatpak/runtime/org.freedesktop.Platform.GL.nvidia-560-35-03/x86_64/1.4/95bd067590a86b5017bdf686c96d14a58e0f0ad0f42100af12a3489c78427d26/files/lib/libnvidia-encode.so.560.35.03: No such file or directory
grep: /var/lib/flatpak/runtime/org.freedesktop.Platform.GL.nvidia-560-35-03/x86_64/1.4/95bd067590a86b5017bdf686c96d14a58e0f0ad0f42100af12a3489c78427d26/files/lib/libnvidia-encode.so.560.35.03: No such file or directory
Error: Could not find bytes '\xe8\x35\x3e\xfe\xff\x85\xc0\x41\x89\xc4' to patch in '/var/lib/flatpak/runtime/org.freedesktop.Platform.GL.nvidia-560-35-03/x86_64/1.4/95bd067590a86b5017bdf686c96d14a58e0f0ad0f42100af12a3489c78427d26/files/lib/libnvidia-encode.so.560.35.03'.
```

**Comment by Gelmo** [comment]
> Awesome! The Nvidia patch worked perfectly for me.
> 
> However, it somehow didn't work for my flatpak drivers, which printed:
> 
> ```
> sudo bash ./patch.sh -f                                                             
> WARNING: Flatpak flag enabled (-f), modifying ONLY the Flatpak driver.
> Detected nvidia driver version: 560.35.03
> libnvidia-encode.so
> grep: /var/lib/flatpak/runtime/org.freedesktop.Platform.GL.nvidia-560-35-03/x86_64/1.4/95bd067590a86b5017bdf686c96d14a58e0f0ad0f42100af12a3489c78427d26/files/lib/libnvidia-encode.so.560.35.03: No such file or directory
> grep: /var/lib/flatpak/runtime/org.freedesktop.Platform.GL.nvidia-560-35-03/x86_64/1.4/95bd067590a86b5017bdf686c96d14a58e0f0ad0f42100af12a3489c78427d26/files/lib/libnvidia-encode.so.560.35.03: No such file or directory
> Error: Could not find bytes '\xe8\x35\x3e\xfe\xff\x85\xc0\x41\x89\xc4' to patch in '/var/lib/flatpak/runtime/org.freedesktop.Platform.GL.nvidia-560-35-03/x86_64/1.4/95bd067590a86b5017bdf686c96d14a58e0f0ad0f42100af12a3489c78427d26/files/lib/libnvidia-encode.so.560.35.03'.
> ```

This is saying that it can't find the file it's trying to patch. Are you certain you rebooted after the update? Run the following and then check if the resulting file actually exists:
```
flatpak info --show-location "org.freedesktop.Platform.GL.nvidia-560.35.03"
```

**Comment by PartTheSeas** [comment]
I'm sorry for the false alarm. 

I've installed the latest 560 drivers for my distro (Arch), rebooted and then switched to the nvidia open dkms package and forgot to reboot.

Flatpak patched here perfectly as well, sorry! And thank you for patching this @Gelmo <3

**Comment by Gelmo** [comment]
> I'm sorry for the false alarm.
> 
> I've installed the latest 560 drivers for my distro (Arch), rebooted and then switched to the nvidia open dkms package and forgot to reboot.
> 
> Flatpak patched here perfectly as well, sorry! And thank you for patching this @Gelmo <3

Excellent, thanks for confirming. No prob, was a quick search in a hex viewer. Maybe later tonight i'll look at other 560's
