### ISSUE TITLE
kernel panic after running 16 ffmpeg in 2 hours

### ISSUE THREAD

**Issue by kinmioliu** [keylase/nvidia-patch#847]
**Describe the bug**
kernel panic after running 16 ffmpeg in 2 hours

**To Reproduce**
1.  run command `time python3 ffmpeg.py 16 100000`, it will run 16 ffmpeg encoders in parallel and loop for 100000 times.

**Expected behavior**
No kernel panic.

**Output listings**
Kernel panic - not syncing: Fatal exception

**Environment (please complete the following information):**
 - OS: 20.04.1-Ubuntu
 - GPU model: RTX 4090
 - Patch commit used: b46777dcd07bf01aafb186b2c247f56c5a513e07
 - Nvidia driver version: 525.89.02

**Additional context**
1. I found a similar issue https://github.com/keylase/nvidia-patch/issues/235, but I don't think it is relative to power/temp/memory cause I logged all statistics, they are normal. I guess other critical resources were racing during the encoding, leading to the driver crash and eventually the kernel panic.

2. I tried increasing the number of parallelism from 9 to 22, all caused kernel panic. The survival time is not a linear with the num of parallelism,  but the more parallelism, the shorter the survival time.

 Any thoughts about this kernel panic?

```
# ffmpeg.py
import subprocess
from concurrent.futures import ThreadPoolExecutor
import sys

streams = int(sys.argv[1])

loops = int(sys.argv[2])

command_template = f"ffmpeg -y -vsync 0 -init_hw_device cuda=foo:bar -filter_hw_device foo -hwaccel cuda -hwaccel_output_format cuda -f lavfi -i testsrc -t 10 -vf hwupload -c:a copy -c:v h264_nvenc -b:v 4M -f null -"

commands = [f"{command_template}" for i in range(streams)]

count = 0

def run_command(cmd):
    subprocess.run(cmd, shell=True, check=True)
    print(f"================== loop {cmd} {count}===========")
    count += 1

with ThreadPoolExecutor(max_workers=streams) as executor:
    for i in range(loops):
        executor.map(run_command, commands)
```

**Comment by jailuthra** [comment]
This is not the appropriate project for bugs in FFmpeg or NVENC/NVDEC libraries.
