### ISSUE TITLE
New driver support (version 550.120)

### ISSUE THREAD

**Issue by joshrandall8478** [keylase/nvidia-patch#849]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 550.120
- GPU Model: GTX 1060 3GB
- OS: OpenSUSE Tumbleweed
- [x] I'm willing to participate in testing of new patch version

Latest version of `nvidia-driver-g06` for OpenSUSE Tumbleweed.

**Comment by jailuthra** [comment]
@joshrandall8478 can you test #850? Steps to test are in the wiki
