### ISSUE TITLE
New driver support (version 535.216)

### ISSUE THREAD

**Issue by cizekmilan** [keylase/nvidia-patch#866]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 535.216.03
- GPU Model: NVIDIA T400 4GB
- OS: Ubuntu 22.04
- [x] I'm willing to participate in testing of new patch version

**Comment by cizekmilan** [comment]
I added...
`["535.216.03"]='s/\xe8\xa5\x9f\xfe\xff\x85\xc0\x41\x89\xc4/\xe8\xa5\x9f\xfe\xff\x29\xc0\x41\x89\xc4/g'`

and driver was successfully patched.

`
Detected nvidia driver version: 535.216.03
libnvidia-encode.so
Attention! Backup not found. Copying current libnvidia-encode.so to backup.
5b0f89765b325912b1f90434b3cbb7ca0d0c2b30  /opt/nvidia/libnvidia-encode-backup/libnvidia-encode.so.535.216.03
6380f06538930a1b51fa02975cd93503b5fdd51b  /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.535.216.03
Patched!
`

**Comment by ssamjh** [comment]
Running Debian 12 and have got version `535.216.01` installed, which is not supported.

**Comment by jailuthra** [comment]
@ssamjh support added now.
