### ISSUE TITLE
Driver not found after switching from distro managed  to Nvidia's .run installer

### ISSUE THREAD

**Issue by jeames00** [keylase/nvidia-patch#871]
**Describe the bug**
Running `sudo bash ./patch.sh` results in:

```
Detected nvidia driver version: 560.35.05
Patch for this (560.35.05) nvidia driver not found.
```

**To Reproduce**
Previously working OK via OpenSUSE's package manager (550.127.05). It became an issue after uninstalling this and installing drivers and cuda support using Nvidia's .run installer (560.35.05).

**Output listings**
`nvidia-smi`

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.05              Driver Version: 560.35.05      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650 ...    Off |   00000000:01:00.0  On |                  N/A |
| 26%   34C    P8              8W /  100W |     280MiB /   4096MiB |      6%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      3249      G   /usr/bin/Xorg.bin                             130MiB |
|    0   N/A  N/A      3422      C   ...libexec/gnome-remote-desktop-daemon         63MiB |
|    0   N/A  N/A      3452      G   /usr/bin/gnome-shell                           33MiB |
|    0   N/A  N/A      3489      G   ...libexec/gnome-remote-desktop-daemon          0MiB |
|    0   N/A  N/A      4206      G   /usr/bin/alacritty                              8MiB |
|    0   N/A  N/A     18264      G   ...36237facd4afa9ba134386695b47abd2aa8         35MiB |
+-----------------------------------------------------------------------------------------+
```

**Environment (please complete the following information):**
 - OS: OpenSUSE Tumbleweed
 - GPU model: 1650 Super
 - Patch commit used: fafd28f299857a8b6794b58b46ae0374c7a4bb2f (also tried via master .ZIP file)
 - Nvidia driver version: 560.35.05

**Additional context**
Nvidia library .SO files appear to be directly within **/usr/lib/** and **/usr/lib64/**

**Comment by jailuthra** [comment]
i can't seem to find 560.35.05 on nvidia's website. do you have a link?

anyway i think the patch for 560.35.03 should work there, you can make the edits locally if you want.

**Comment by jeames00** [comment]
It's mentioned on this project's front page, the second last one in the list.
```
560.35.03	YES	YES	[Driver link](http://international.download.nvidia.com/XFree86/Linux-x86_64/560.35.03/NVIDIA-Linux-x86_64-560.35.03.run)
```

**Comment by jeames00** [comment]
Ahh I was confused, didn't notice the difference (xxx.xx.03 vs xxx.xx.05). I ended up with '.05' after installing the latest CUDA Toolkit 12.6 Update 3.

https://developer.download.nvidia.com/compute/cuda/12.6.3/local_installers/cuda_12.6.3_560.35.05_linux.run

Thanks, I'll see what I can do.

**Comment by jeames00** [comment]
> anyway i think the patch for 560.35.03 should work there, you can make the edits locally if you want.

I assume I just need to add an entry in the "declare -A patch list" statement? I don't know what those sed replacement strings are about, how do I construct one for version '560.35.05'?

**Comment by jailuthra** [comment]
can you test if #873 works for you?

**Comment by jeames00** [comment]
> can you test if #873 works for you?

Yes I can confirm that works, thank you!
