### ISSUE TITLE
New driver support (version 565.77)

### ISSUE THREAD

**Issue by Ja4e** [keylase/nvidia-patch#875]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: [ 565.77]
- GPU Model: [RTX 3070 Laptop Max-Q]
- OS: [Arch Linux 6.12.3-arch1-1]
- [x] I'm willing to participate in testing of new patch version

**Comment by joshuataylor** [comment]
https://www.nvidia.com/en-us/drivers/details/237587/

https://international.download.nvidia.com/XFree86/Linux-x86_64/565.77/NVIDIA-Linux-x86_64-565.77.run

**Comment by GenocideStomper** [comment]
Sorry I'm confused, is / will this version be supported?
