### ISSUE TITLE
New driver support (version 565.77)

### ISSUE THREAD

**Issue by AnnabellaRenee87** [keylase/nvidia-patch#878]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 565.77
- GPU Model: RTX 4060
- OS: UNRAID 7.0 RC2
- [x] I'm willing to participate in testing of new patch version

https://www.nvidia.com/en-us/drivers/details/237587/

**Comment by jimmon89** [comment]
**Please provide details about your environment (please complete the following information)**
- Nvidia driver version: 565.77
- GPU Model: RTX 3060
- OS: CachyOS (Arch Derivative)
- [x] I'm willing to participate in testing of new patch version

i'll throw my hat in as well
