### ISSUE TITLE
HEVC B Frame Support

### ISSUE THREAD

**Issue by damdinsharav** [keylase/nvidia-patch#98]
Hello,

Now that GTX 1650 (TU117) released it says doesn't  support HEVC B Frame. I'm wondering if it's hardware or software level limitation.
If it's software restriction can we override on driver level?

**Comment by Snawoot** [comment]
Hello,

It appears to be hardware limitation since TU117 uses outdated Volta NVENC chip (according to full specs on [product page](https://www.nvidia.com/en-us/geforce/graphics-cards/gtx-1650/)), which belongs to previous generation. We do not expect we'll fix that.

**Comment by vans163** [comment]
useless card, such a sad release. There is no reason to use this over a gtx 1050ti for a mini build, and if you want passive cooling + have the $$$, rtx 4000 series does the job for mini itx performance.
