### ISSUE TITLE
DCH Driver Support

### ISSUE THREAD

**Issue by tekman13** [keylase/nvidia-patch#99]
I needed to install DCH drivers instead of standard drivers for my Quadro P400. I downloaded the latest (430.39) directly from NVidia but now im getting an error when patching with 1337. it says:

Offset [E2877] wrong
Set 0x48 -> I expected 0x74

is this specifically because Im using the DCH driver?

**Comment by Snawoot** [comment]
Hi!

DCH driver has same offset as Standard driver, I just checked it. Please make sure you selected proper file for patching and "Fix offset" checkbox is checked (it is set by default). If nothing helps, attach your nvcuvid.dll to this issue.

**Comment by tekman13** [comment]
Figured it out. Windows installed version 397.xx from windows update, and when i installed the 430.39 package, it didnt actually update the driver attached to the device. It patched now.. thanks!
